// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live/chat_room.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatCallBackReq struct {
	CallId               string   `protobuf:"bytes,1,opt,name=callId,proto3" json:"callId"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp"`
	ChatType             string   `protobuf:"bytes,3,opt,name=chat_type,json=chatType,proto3" json:"chat_type"`
	GroupId              string   `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	From                 string   `protobuf:"bytes,5,opt,name=from,proto3" json:"from"`
	To                   string   `protobuf:"bytes,6,opt,name=to,proto3" json:"to"`
	MsgId                string   `protobuf:"bytes,7,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	Payload              *Payload `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload"`
	SecurityVersion      string   `protobuf:"bytes,9,opt,name=securityVersion,proto3" json:"securityVersion"`
	Security             string   `protobuf:"bytes,10,opt,name=security,proto3" json:"security"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCallBackReq) Reset()         { *m = ChatCallBackReq{} }
func (m *ChatCallBackReq) String() string { return proto.CompactTextString(m) }
func (*ChatCallBackReq) ProtoMessage()    {}
func (*ChatCallBackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{0}
}

func (m *ChatCallBackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCallBackReq.Unmarshal(m, b)
}
func (m *ChatCallBackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCallBackReq.Marshal(b, m, deterministic)
}
func (m *ChatCallBackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCallBackReq.Merge(m, src)
}
func (m *ChatCallBackReq) XXX_Size() int {
	return xxx_messageInfo_ChatCallBackReq.Size(m)
}
func (m *ChatCallBackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCallBackReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCallBackReq proto.InternalMessageInfo

func (m *ChatCallBackReq) GetCallId() string {
	if m != nil {
		return m.CallId
	}
	return ""
}

func (m *ChatCallBackReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChatCallBackReq) GetChatType() string {
	if m != nil {
		return m.ChatType
	}
	return ""
}

func (m *ChatCallBackReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *ChatCallBackReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChatCallBackReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatCallBackReq) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *ChatCallBackReq) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChatCallBackReq) GetSecurityVersion() string {
	if m != nil {
		return m.SecurityVersion
	}
	return ""
}

func (m *ChatCallBackReq) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

type Payload struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

type ChatCallBackResp struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Payload              string   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCallBackResp) Reset()         { *m = ChatCallBackResp{} }
func (m *ChatCallBackResp) String() string { return proto.CompactTextString(m) }
func (*ChatCallBackResp) ProtoMessage()    {}
func (*ChatCallBackResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{2}
}

func (m *ChatCallBackResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCallBackResp.Unmarshal(m, b)
}
func (m *ChatCallBackResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCallBackResp.Marshal(b, m, deterministic)
}
func (m *ChatCallBackResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCallBackResp.Merge(m, src)
}
func (m *ChatCallBackResp) XXX_Size() int {
	return xxx_messageInfo_ChatCallBackResp.Size(m)
}
func (m *ChatCallBackResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCallBackResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCallBackResp proto.InternalMessageInfo

func (m *ChatCallBackResp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ChatCallBackResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ChatCallBackResp) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateChatRoomReq struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	AnchorName           string   `protobuf:"bytes,2,opt,name=anchorName,proto3" json:"anchorName"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomReq) Reset()         { *m = CreateChatRoomReq{} }
func (m *CreateChatRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomReq) ProtoMessage()    {}
func (*CreateChatRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{3}
}

func (m *CreateChatRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomReq.Unmarshal(m, b)
}
func (m *CreateChatRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateChatRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomReq.Merge(m, src)
}
func (m *CreateChatRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomReq.Size(m)
}
func (m *CreateChatRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomReq proto.InternalMessageInfo

func (m *CreateChatRoomReq) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *CreateChatRoomReq) GetAnchorName() string {
	if m != nil {
		return m.AnchorName
	}
	return ""
}

func (m *CreateChatRoomReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type CreateChatRoomResp struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomResp) Reset()         { *m = CreateChatRoomResp{} }
func (m *CreateChatRoomResp) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomResp) ProtoMessage()    {}
func (*CreateChatRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{4}
}

func (m *CreateChatRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomResp.Unmarshal(m, b)
}
func (m *CreateChatRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomResp.Marshal(b, m, deterministic)
}
func (m *CreateChatRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomResp.Merge(m, src)
}
func (m *CreateChatRoomResp) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomResp.Size(m)
}
func (m *CreateChatRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomResp proto.InternalMessageInfo

func (m *CreateChatRoomResp) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

type CreateUserReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{5}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResp struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResp) Reset()         { *m = CreateUserResp{} }
func (m *CreateUserResp) String() string { return proto.CompactTextString(m) }
func (*CreateUserResp) ProtoMessage()    {}
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{6}
}

func (m *CreateUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResp.Unmarshal(m, b)
}
func (m *CreateUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResp.Marshal(b, m, deterministic)
}
func (m *CreateUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResp.Merge(m, src)
}
func (m *CreateUserResp) XXX_Size() int {
	return xxx_messageInfo_CreateUserResp.Size(m)
}
func (m *CreateUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResp proto.InternalMessageInfo

func (m *CreateUserResp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type JoinRoomReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	SourceTag            string   `protobuf:"bytes,2,opt,name=sourceTag,proto3" json:"sourceTag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{7}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

func (m *JoinRoomReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *JoinRoomReq) GetSourceTag() string {
	if m != nil {
		return m.SourceTag
	}
	return ""
}

type RobotJoinRoomReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	ChatRoomId           string   `protobuf:"bytes,2,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotJoinRoomReq) Reset()         { *m = RobotJoinRoomReq{} }
func (m *RobotJoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*RobotJoinRoomReq) ProtoMessage()    {}
func (*RobotJoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{8}
}

func (m *RobotJoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotJoinRoomReq.Unmarshal(m, b)
}
func (m *RobotJoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotJoinRoomReq.Marshal(b, m, deterministic)
}
func (m *RobotJoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotJoinRoomReq.Merge(m, src)
}
func (m *RobotJoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_RobotJoinRoomReq.Size(m)
}
func (m *RobotJoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotJoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_RobotJoinRoomReq proto.InternalMessageInfo

func (m *RobotJoinRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RobotJoinRoomReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

type JoinRoomResp struct {
	AppId                string      `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId"`
	AppKey               string      `protobuf:"bytes,2,opt,name=appKey,proto3" json:"appKey"`
	Token                string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	UserId               int32       `protobuf:"varint,4,opt,name=userId,proto3" json:"userId"`
	Uuid                 string      `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid"`
	LikeTally            int32       `protobuf:"varint,6,opt,name=likeTally,proto3" json:"likeTally"`
	Liked                int32       `protobuf:"varint,7,opt,name=liked,proto3" json:"liked"`
	HistMess             []*HistMess `protobuf:"bytes,8,rep,name=histMess,proto3" json:"histMess"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomResp) Reset()         { *m = JoinRoomResp{} }
func (m *JoinRoomResp) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResp) ProtoMessage()    {}
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{9}
}

func (m *JoinRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResp.Unmarshal(m, b)
}
func (m *JoinRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResp.Marshal(b, m, deterministic)
}
func (m *JoinRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResp.Merge(m, src)
}
func (m *JoinRoomResp) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResp.Size(m)
}
func (m *JoinRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResp proto.InternalMessageInfo

func (m *JoinRoomResp) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *JoinRoomResp) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *JoinRoomResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinRoomResp) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinRoomResp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *JoinRoomResp) GetLikeTally() int32 {
	if m != nil {
		return m.LikeTally
	}
	return 0
}

func (m *JoinRoomResp) GetLiked() int32 {
	if m != nil {
		return m.Liked
	}
	return 0
}

func (m *JoinRoomResp) GetHistMess() []*HistMess {
	if m != nil {
		return m.HistMess
	}
	return nil
}

type HistMess struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname"`
	LevelId              int32    `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId"`
	UserId               int32    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content"`
	IsBarrage            int32    `protobuf:"varint,6,opt,name=isBarrage,proto3" json:"isBarrage"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistMess) Reset()         { *m = HistMess{} }
func (m *HistMess) String() string { return proto.CompactTextString(m) }
func (*HistMess) ProtoMessage()    {}
func (*HistMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{10}
}

func (m *HistMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistMess.Unmarshal(m, b)
}
func (m *HistMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistMess.Marshal(b, m, deterministic)
}
func (m *HistMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistMess.Merge(m, src)
}
func (m *HistMess) XXX_Size() int {
	return xxx_messageInfo_HistMess.Size(m)
}
func (m *HistMess) XXX_DiscardUnknown() {
	xxx_messageInfo_HistMess.DiscardUnknown(m)
}

var xxx_messageInfo_HistMess proto.InternalMessageInfo

func (m *HistMess) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *HistMess) GetLevelId() int32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *HistMess) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HistMess) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *HistMess) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *HistMess) GetIsBarrage() int32 {
	if m != nil {
		return m.IsBarrage
	}
	return 0
}

func (m *HistMess) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SendGiftReq struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId"`
	GifId                int32    `protobuf:"varint,2,opt,name=gifId,proto3" json:"gifId"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendGiftReq) Reset()         { *m = SendGiftReq{} }
func (m *SendGiftReq) String() string { return proto.CompactTextString(m) }
func (*SendGiftReq) ProtoMessage()    {}
func (*SendGiftReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{11}
}

func (m *SendGiftReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendGiftReq.Unmarshal(m, b)
}
func (m *SendGiftReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendGiftReq.Marshal(b, m, deterministic)
}
func (m *SendGiftReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendGiftReq.Merge(m, src)
}
func (m *SendGiftReq) XXX_Size() int {
	return xxx_messageInfo_SendGiftReq.Size(m)
}
func (m *SendGiftReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendGiftReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendGiftReq proto.InternalMessageInfo

func (m *SendGiftReq) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *SendGiftReq) GetGifId() int32 {
	if m != nil {
		return m.GifId
	}
	return 0
}

func (m *SendGiftReq) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type SendGiftResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendGiftResp) Reset()         { *m = SendGiftResp{} }
func (m *SendGiftResp) String() string { return proto.CompactTextString(m) }
func (*SendGiftResp) ProtoMessage()    {}
func (*SendGiftResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{12}
}

func (m *SendGiftResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendGiftResp.Unmarshal(m, b)
}
func (m *SendGiftResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendGiftResp.Marshal(b, m, deterministic)
}
func (m *SendGiftResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendGiftResp.Merge(m, src)
}
func (m *SendGiftResp) XXX_Size() int {
	return xxx_messageInfo_SendGiftResp.Size(m)
}
func (m *SendGiftResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendGiftResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendGiftResp proto.InternalMessageInfo

type SendMessReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	Barrage              int32    `protobuf:"varint,3,opt,name=barrage,proto3" json:"barrage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessReq) Reset()         { *m = SendMessReq{} }
func (m *SendMessReq) String() string { return proto.CompactTextString(m) }
func (*SendMessReq) ProtoMessage()    {}
func (*SendMessReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{13}
}

func (m *SendMessReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessReq.Unmarshal(m, b)
}
func (m *SendMessReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessReq.Marshal(b, m, deterministic)
}
func (m *SendMessReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessReq.Merge(m, src)
}
func (m *SendMessReq) XXX_Size() int {
	return xxx_messageInfo_SendMessReq.Size(m)
}
func (m *SendMessReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessReq proto.InternalMessageInfo

func (m *SendMessReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *SendMessReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendMessReq) GetBarrage() int32 {
	if m != nil {
		return m.Barrage
	}
	return 0
}

type SendMessResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessResp) Reset()         { *m = SendMessResp{} }
func (m *SendMessResp) String() string { return proto.CompactTextString(m) }
func (*SendMessResp) ProtoMessage()    {}
func (*SendMessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{14}
}

func (m *SendMessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessResp.Unmarshal(m, b)
}
func (m *SendMessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessResp.Marshal(b, m, deterministic)
}
func (m *SendMessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessResp.Merge(m, src)
}
func (m *SendMessResp) XXX_Size() int {
	return xxx_messageInfo_SendMessResp.Size(m)
}
func (m *SendMessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessResp proto.InternalMessageInfo

type ToggleLikeReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleLikeReq) Reset()         { *m = ToggleLikeReq{} }
func (m *ToggleLikeReq) String() string { return proto.CompactTextString(m) }
func (*ToggleLikeReq) ProtoMessage()    {}
func (*ToggleLikeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{15}
}

func (m *ToggleLikeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleLikeReq.Unmarshal(m, b)
}
func (m *ToggleLikeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleLikeReq.Marshal(b, m, deterministic)
}
func (m *ToggleLikeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleLikeReq.Merge(m, src)
}
func (m *ToggleLikeReq) XXX_Size() int {
	return xxx_messageInfo_ToggleLikeReq.Size(m)
}
func (m *ToggleLikeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleLikeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleLikeReq proto.InternalMessageInfo

func (m *ToggleLikeReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

type ToggleLikeResp struct {
	UserLiked            int32    `protobuf:"varint,1,opt,name=userLiked,proto3" json:"userLiked"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleLikeResp) Reset()         { *m = ToggleLikeResp{} }
func (m *ToggleLikeResp) String() string { return proto.CompactTextString(m) }
func (*ToggleLikeResp) ProtoMessage()    {}
func (*ToggleLikeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{16}
}

func (m *ToggleLikeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleLikeResp.Unmarshal(m, b)
}
func (m *ToggleLikeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleLikeResp.Marshal(b, m, deterministic)
}
func (m *ToggleLikeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleLikeResp.Merge(m, src)
}
func (m *ToggleLikeResp) XXX_Size() int {
	return xxx_messageInfo_ToggleLikeResp.Size(m)
}
func (m *ToggleLikeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleLikeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleLikeResp proto.InternalMessageInfo

func (m *ToggleLikeResp) GetUserLiked() int32 {
	if m != nil {
		return m.UserLiked
	}
	return 0
}

type LeaveRoomReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomReq) Reset()         { *m = LeaveRoomReq{} }
func (m *LeaveRoomReq) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomReq) ProtoMessage()    {}
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{17}
}

func (m *LeaveRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomReq.Unmarshal(m, b)
}
func (m *LeaveRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomReq.Marshal(b, m, deterministic)
}
func (m *LeaveRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomReq.Merge(m, src)
}
func (m *LeaveRoomReq) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomReq.Size(m)
}
func (m *LeaveRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomReq proto.InternalMessageInfo

func (m *LeaveRoomReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *LeaveRoomReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LeaveRoomResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomResp) Reset()         { *m = LeaveRoomResp{} }
func (m *LeaveRoomResp) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResp) ProtoMessage()    {}
func (*LeaveRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{18}
}

func (m *LeaveRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResp.Unmarshal(m, b)
}
func (m *LeaveRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResp.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResp.Merge(m, src)
}
func (m *LeaveRoomResp) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResp.Size(m)
}
func (m *LeaveRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResp proto.InternalMessageInfo

type FollowUserReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserReq) Reset()         { *m = FollowUserReq{} }
func (m *FollowUserReq) String() string { return proto.CompactTextString(m) }
func (*FollowUserReq) ProtoMessage()    {}
func (*FollowUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{19}
}

func (m *FollowUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserReq.Unmarshal(m, b)
}
func (m *FollowUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserReq.Marshal(b, m, deterministic)
}
func (m *FollowUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserReq.Merge(m, src)
}
func (m *FollowUserReq) XXX_Size() int {
	return xxx_messageInfo_FollowUserReq.Size(m)
}
func (m *FollowUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserReq proto.InternalMessageInfo

func (m *FollowUserReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *FollowUserReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FollowUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type FollowUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserResp) Reset()         { *m = FollowUserResp{} }
func (m *FollowUserResp) String() string { return proto.CompactTextString(m) }
func (*FollowUserResp) ProtoMessage()    {}
func (*FollowUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{20}
}

func (m *FollowUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserResp.Unmarshal(m, b)
}
func (m *FollowUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserResp.Marshal(b, m, deterministic)
}
func (m *FollowUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserResp.Merge(m, src)
}
func (m *FollowUserResp) XXX_Size() int {
	return xxx_messageInfo_FollowUserResp.Size(m)
}
func (m *FollowUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserResp proto.InternalMessageInfo

type IncomeNotifyReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	Income               float32  `protobuf:"fixed32,3,opt,name=Income,proto3" json:"Income"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncomeNotifyReq) Reset()         { *m = IncomeNotifyReq{} }
func (m *IncomeNotifyReq) String() string { return proto.CompactTextString(m) }
func (*IncomeNotifyReq) ProtoMessage()    {}
func (*IncomeNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{21}
}

func (m *IncomeNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomeNotifyReq.Unmarshal(m, b)
}
func (m *IncomeNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomeNotifyReq.Marshal(b, m, deterministic)
}
func (m *IncomeNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomeNotifyReq.Merge(m, src)
}
func (m *IncomeNotifyReq) XXX_Size() int {
	return xxx_messageInfo_IncomeNotifyReq.Size(m)
}
func (m *IncomeNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomeNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncomeNotifyReq proto.InternalMessageInfo

func (m *IncomeNotifyReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *IncomeNotifyReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IncomeNotifyReq) GetIncome() float32 {
	if m != nil {
		return m.Income
	}
	return 0
}

type IncomeNotifyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncomeNotifyResp) Reset()         { *m = IncomeNotifyResp{} }
func (m *IncomeNotifyResp) String() string { return proto.CompactTextString(m) }
func (*IncomeNotifyResp) ProtoMessage()    {}
func (*IncomeNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{22}
}

func (m *IncomeNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomeNotifyResp.Unmarshal(m, b)
}
func (m *IncomeNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomeNotifyResp.Marshal(b, m, deterministic)
}
func (m *IncomeNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomeNotifyResp.Merge(m, src)
}
func (m *IncomeNotifyResp) XXX_Size() int {
	return xxx_messageInfo_IncomeNotifyResp.Size(m)
}
func (m *IncomeNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomeNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_IncomeNotifyResp proto.InternalMessageInfo

type GiftNotifyReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	GiftId               int32    `protobuf:"varint,3,opt,name=giftId,proto3" json:"giftId"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiftNotifyReq) Reset()         { *m = GiftNotifyReq{} }
func (m *GiftNotifyReq) String() string { return proto.CompactTextString(m) }
func (*GiftNotifyReq) ProtoMessage()    {}
func (*GiftNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{23}
}

func (m *GiftNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiftNotifyReq.Unmarshal(m, b)
}
func (m *GiftNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiftNotifyReq.Marshal(b, m, deterministic)
}
func (m *GiftNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiftNotifyReq.Merge(m, src)
}
func (m *GiftNotifyReq) XXX_Size() int {
	return xxx_messageInfo_GiftNotifyReq.Size(m)
}
func (m *GiftNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GiftNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GiftNotifyReq proto.InternalMessageInfo

func (m *GiftNotifyReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *GiftNotifyReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GiftNotifyReq) GetGiftId() int32 {
	if m != nil {
		return m.GiftId
	}
	return 0
}

func (m *GiftNotifyReq) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type SystemNotifyReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	NotifyRange          int32    `protobuf:"varint,2,opt,name=notifyRange,proto3" json:"notifyRange"`
	NotifyContent        string   `protobuf:"bytes,3,opt,name=notifyContent,proto3" json:"notifyContent"`
	NotifyType           int32    `protobuf:"varint,4,opt,name=notifyType,proto3" json:"notifyType"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemNotifyReq) Reset()         { *m = SystemNotifyReq{} }
func (m *SystemNotifyReq) String() string { return proto.CompactTextString(m) }
func (*SystemNotifyReq) ProtoMessage()    {}
func (*SystemNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{24}
}

func (m *SystemNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemNotifyReq.Unmarshal(m, b)
}
func (m *SystemNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemNotifyReq.Marshal(b, m, deterministic)
}
func (m *SystemNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemNotifyReq.Merge(m, src)
}
func (m *SystemNotifyReq) XXX_Size() int {
	return xxx_messageInfo_SystemNotifyReq.Size(m)
}
func (m *SystemNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SystemNotifyReq proto.InternalMessageInfo

func (m *SystemNotifyReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SystemNotifyReq) GetNotifyRange() int32 {
	if m != nil {
		return m.NotifyRange
	}
	return 0
}

func (m *SystemNotifyReq) GetNotifyContent() string {
	if m != nil {
		return m.NotifyContent
	}
	return ""
}

func (m *SystemNotifyReq) GetNotifyType() int32 {
	if m != nil {
		return m.NotifyType
	}
	return 0
}

type SystemNotifyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemNotifyResp) Reset()         { *m = SystemNotifyResp{} }
func (m *SystemNotifyResp) String() string { return proto.CompactTextString(m) }
func (*SystemNotifyResp) ProtoMessage()    {}
func (*SystemNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{25}
}

func (m *SystemNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemNotifyResp.Unmarshal(m, b)
}
func (m *SystemNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemNotifyResp.Marshal(b, m, deterministic)
}
func (m *SystemNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemNotifyResp.Merge(m, src)
}
func (m *SystemNotifyResp) XXX_Size() int {
	return xxx_messageInfo_SystemNotifyResp.Size(m)
}
func (m *SystemNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_SystemNotifyResp proto.InternalMessageInfo

type GetChatRoomInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatRoomInfoReq) Reset()         { *m = GetChatRoomInfoReq{} }
func (m *GetChatRoomInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomInfoReq) ProtoMessage()    {}
func (*GetChatRoomInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{26}
}

func (m *GetChatRoomInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomInfoReq.Unmarshal(m, b)
}
func (m *GetChatRoomInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomInfoReq.Marshal(b, m, deterministic)
}
func (m *GetChatRoomInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomInfoReq.Merge(m, src)
}
func (m *GetChatRoomInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomInfoReq.Size(m)
}
func (m *GetChatRoomInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomInfoReq proto.InternalMessageInfo

type GetChatRoomInfoResp struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId"`
	AppKey               string   `protobuf:"bytes,2,opt,name=appKey,proto3" json:"appKey"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatRoomInfoResp) Reset()         { *m = GetChatRoomInfoResp{} }
func (m *GetChatRoomInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomInfoResp) ProtoMessage()    {}
func (*GetChatRoomInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{27}
}

func (m *GetChatRoomInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomInfoResp.Unmarshal(m, b)
}
func (m *GetChatRoomInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomInfoResp.Marshal(b, m, deterministic)
}
func (m *GetChatRoomInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomInfoResp.Merge(m, src)
}
func (m *GetChatRoomInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomInfoResp.Size(m)
}
func (m *GetChatRoomInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomInfoResp proto.InternalMessageInfo

func (m *GetChatRoomInfoResp) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetChatRoomInfoResp) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GetChatRoomInfoResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetChatRoomInfoResp) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetChatRoomInfoResp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type InsufficientBalanceNoticeReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsufficientBalanceNoticeReq) Reset()         { *m = InsufficientBalanceNoticeReq{} }
func (m *InsufficientBalanceNoticeReq) String() string { return proto.CompactTextString(m) }
func (*InsufficientBalanceNoticeReq) ProtoMessage()    {}
func (*InsufficientBalanceNoticeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{28}
}

func (m *InsufficientBalanceNoticeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsufficientBalanceNoticeReq.Unmarshal(m, b)
}
func (m *InsufficientBalanceNoticeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsufficientBalanceNoticeReq.Marshal(b, m, deterministic)
}
func (m *InsufficientBalanceNoticeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsufficientBalanceNoticeReq.Merge(m, src)
}
func (m *InsufficientBalanceNoticeReq) XXX_Size() int {
	return xxx_messageInfo_InsufficientBalanceNoticeReq.Size(m)
}
func (m *InsufficientBalanceNoticeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsufficientBalanceNoticeReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsufficientBalanceNoticeReq proto.InternalMessageInfo

func (m *InsufficientBalanceNoticeReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *InsufficientBalanceNoticeReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type InsufficientBalanceNoticeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsufficientBalanceNoticeResp) Reset()         { *m = InsufficientBalanceNoticeResp{} }
func (m *InsufficientBalanceNoticeResp) String() string { return proto.CompactTextString(m) }
func (*InsufficientBalanceNoticeResp) ProtoMessage()    {}
func (*InsufficientBalanceNoticeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{29}
}

func (m *InsufficientBalanceNoticeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsufficientBalanceNoticeResp.Unmarshal(m, b)
}
func (m *InsufficientBalanceNoticeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsufficientBalanceNoticeResp.Marshal(b, m, deterministic)
}
func (m *InsufficientBalanceNoticeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsufficientBalanceNoticeResp.Merge(m, src)
}
func (m *InsufficientBalanceNoticeResp) XXX_Size() int {
	return xxx_messageInfo_InsufficientBalanceNoticeResp.Size(m)
}
func (m *InsufficientBalanceNoticeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InsufficientBalanceNoticeResp.DiscardUnknown(m)
}

var xxx_messageInfo_InsufficientBalanceNoticeResp proto.InternalMessageInfo

type GetChatRoomOnlineUserReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatRoomOnlineUserReq) Reset()         { *m = GetChatRoomOnlineUserReq{} }
func (m *GetChatRoomOnlineUserReq) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomOnlineUserReq) ProtoMessage()    {}
func (*GetChatRoomOnlineUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{30}
}

func (m *GetChatRoomOnlineUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomOnlineUserReq.Unmarshal(m, b)
}
func (m *GetChatRoomOnlineUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomOnlineUserReq.Marshal(b, m, deterministic)
}
func (m *GetChatRoomOnlineUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomOnlineUserReq.Merge(m, src)
}
func (m *GetChatRoomOnlineUserReq) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomOnlineUserReq.Size(m)
}
func (m *GetChatRoomOnlineUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomOnlineUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomOnlineUserReq proto.InternalMessageInfo

func (m *GetChatRoomOnlineUserReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *GetChatRoomOnlineUserReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetChatRoomOnlineUserReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type OnlineUser struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname"`
	LevelId              int32    `protobuf:"varint,4,opt,name=levelId,proto3" json:"levelId"`
	Sex                  int32    `protobuf:"varint,5,opt,name=sex,proto3" json:"sex"`
	Contribution         int64    `protobuf:"varint,6,opt,name=contribution,proto3" json:"contribution"`
	IsManage             int32    `protobuf:"varint,7,opt,name=isManage,proto3" json:"isManage"`
	IsBan                int32    `protobuf:"varint,8,opt,name=isBan,proto3" json:"isBan"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineUser) Reset()         { *m = OnlineUser{} }
func (m *OnlineUser) String() string { return proto.CompactTextString(m) }
func (*OnlineUser) ProtoMessage()    {}
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{31}
}

func (m *OnlineUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineUser.Unmarshal(m, b)
}
func (m *OnlineUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineUser.Marshal(b, m, deterministic)
}
func (m *OnlineUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineUser.Merge(m, src)
}
func (m *OnlineUser) XXX_Size() int {
	return xxx_messageInfo_OnlineUser.Size(m)
}
func (m *OnlineUser) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineUser.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineUser proto.InternalMessageInfo

func (m *OnlineUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OnlineUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *OnlineUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *OnlineUser) GetLevelId() int32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *OnlineUser) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *OnlineUser) GetContribution() int64 {
	if m != nil {
		return m.Contribution
	}
	return 0
}

func (m *OnlineUser) GetIsManage() int32 {
	if m != nil {
		return m.IsManage
	}
	return 0
}

func (m *OnlineUser) GetIsBan() int32 {
	if m != nil {
		return m.IsBan
	}
	return 0
}

type GetChatRoomOnlineUserResp struct {
	List                 []*OnlineUser `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetChatRoomOnlineUserResp) Reset()         { *m = GetChatRoomOnlineUserResp{} }
func (m *GetChatRoomOnlineUserResp) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomOnlineUserResp) ProtoMessage()    {}
func (*GetChatRoomOnlineUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{32}
}

func (m *GetChatRoomOnlineUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomOnlineUserResp.Unmarshal(m, b)
}
func (m *GetChatRoomOnlineUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomOnlineUserResp.Marshal(b, m, deterministic)
}
func (m *GetChatRoomOnlineUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomOnlineUserResp.Merge(m, src)
}
func (m *GetChatRoomOnlineUserResp) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomOnlineUserResp.Size(m)
}
func (m *GetChatRoomOnlineUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomOnlineUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomOnlineUserResp proto.InternalMessageInfo

func (m *GetChatRoomOnlineUserResp) GetList() []*OnlineUser {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetChatRoomOnlineUserResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UpgradeNotifyReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeNotifyReq) Reset()         { *m = UpgradeNotifyReq{} }
func (m *UpgradeNotifyReq) String() string { return proto.CompactTextString(m) }
func (*UpgradeNotifyReq) ProtoMessage()    {}
func (*UpgradeNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{33}
}

func (m *UpgradeNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeNotifyReq.Unmarshal(m, b)
}
func (m *UpgradeNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeNotifyReq.Marshal(b, m, deterministic)
}
func (m *UpgradeNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeNotifyReq.Merge(m, src)
}
func (m *UpgradeNotifyReq) XXX_Size() int {
	return xxx_messageInfo_UpgradeNotifyReq.Size(m)
}
func (m *UpgradeNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeNotifyReq proto.InternalMessageInfo

func (m *UpgradeNotifyReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *UpgradeNotifyReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpgradeNotifyReq) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type UpgradeNotifyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeNotifyResp) Reset()         { *m = UpgradeNotifyResp{} }
func (m *UpgradeNotifyResp) String() string { return proto.CompactTextString(m) }
func (*UpgradeNotifyResp) ProtoMessage()    {}
func (*UpgradeNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{34}
}

func (m *UpgradeNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeNotifyResp.Unmarshal(m, b)
}
func (m *UpgradeNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeNotifyResp.Marshal(b, m, deterministic)
}
func (m *UpgradeNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeNotifyResp.Merge(m, src)
}
func (m *UpgradeNotifyResp) XXX_Size() int {
	return xxx_messageInfo_UpgradeNotifyResp.Size(m)
}
func (m *UpgradeNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeNotifyResp proto.InternalMessageInfo

type GetSDKOnlineUserStatusReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSDKOnlineUserStatusReq) Reset()         { *m = GetSDKOnlineUserStatusReq{} }
func (m *GetSDKOnlineUserStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetSDKOnlineUserStatusReq) ProtoMessage()    {}
func (*GetSDKOnlineUserStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{35}
}

func (m *GetSDKOnlineUserStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSDKOnlineUserStatusReq.Unmarshal(m, b)
}
func (m *GetSDKOnlineUserStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSDKOnlineUserStatusReq.Marshal(b, m, deterministic)
}
func (m *GetSDKOnlineUserStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDKOnlineUserStatusReq.Merge(m, src)
}
func (m *GetSDKOnlineUserStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetSDKOnlineUserStatusReq.Size(m)
}
func (m *GetSDKOnlineUserStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDKOnlineUserStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDKOnlineUserStatusReq proto.InternalMessageInfo

func (m *GetSDKOnlineUserStatusReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetSDKOnlineUserStatusResp struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSDKOnlineUserStatusResp) Reset()         { *m = GetSDKOnlineUserStatusResp{} }
func (m *GetSDKOnlineUserStatusResp) String() string { return proto.CompactTextString(m) }
func (*GetSDKOnlineUserStatusResp) ProtoMessage()    {}
func (*GetSDKOnlineUserStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{36}
}

func (m *GetSDKOnlineUserStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSDKOnlineUserStatusResp.Unmarshal(m, b)
}
func (m *GetSDKOnlineUserStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSDKOnlineUserStatusResp.Marshal(b, m, deterministic)
}
func (m *GetSDKOnlineUserStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDKOnlineUserStatusResp.Merge(m, src)
}
func (m *GetSDKOnlineUserStatusResp) XXX_Size() int {
	return xxx_messageInfo_GetSDKOnlineUserStatusResp.Size(m)
}
func (m *GetSDKOnlineUserStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDKOnlineUserStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDKOnlineUserStatusResp proto.InternalMessageInfo

func (m *GetSDKOnlineUserStatusResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetSDKChatRoomUsersReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize"`
	ChatRoomId           string   `protobuf:"bytes,3,opt,name=chatRoomId,proto3" json:"chatRoomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSDKChatRoomUsersReq) Reset()         { *m = GetSDKChatRoomUsersReq{} }
func (m *GetSDKChatRoomUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetSDKChatRoomUsersReq) ProtoMessage()    {}
func (*GetSDKChatRoomUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{37}
}

func (m *GetSDKChatRoomUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSDKChatRoomUsersReq.Unmarshal(m, b)
}
func (m *GetSDKChatRoomUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSDKChatRoomUsersReq.Marshal(b, m, deterministic)
}
func (m *GetSDKChatRoomUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDKChatRoomUsersReq.Merge(m, src)
}
func (m *GetSDKChatRoomUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetSDKChatRoomUsersReq.Size(m)
}
func (m *GetSDKChatRoomUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDKChatRoomUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDKChatRoomUsersReq proto.InternalMessageInfo

func (m *GetSDKChatRoomUsersReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetSDKChatRoomUsersReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetSDKChatRoomUsersReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

type ChatRoomUsers struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner"`
	Member               string   `protobuf:"bytes,2,opt,name=member,proto3" json:"member"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRoomUsers) Reset()         { *m = ChatRoomUsers{} }
func (m *ChatRoomUsers) String() string { return proto.CompactTextString(m) }
func (*ChatRoomUsers) ProtoMessage()    {}
func (*ChatRoomUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{38}
}

func (m *ChatRoomUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRoomUsers.Unmarshal(m, b)
}
func (m *ChatRoomUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRoomUsers.Marshal(b, m, deterministic)
}
func (m *ChatRoomUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRoomUsers.Merge(m, src)
}
func (m *ChatRoomUsers) XXX_Size() int {
	return xxx_messageInfo_ChatRoomUsers.Size(m)
}
func (m *ChatRoomUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRoomUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRoomUsers proto.InternalMessageInfo

func (m *ChatRoomUsers) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ChatRoomUsers) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

type GetSDKChatRoomUsersResp struct {
	List                 []*ChatRoomUsers `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total                int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetSDKChatRoomUsersResp) Reset()         { *m = GetSDKChatRoomUsersResp{} }
func (m *GetSDKChatRoomUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetSDKChatRoomUsersResp) ProtoMessage()    {}
func (*GetSDKChatRoomUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7246442795c9d7c, []int{39}
}

func (m *GetSDKChatRoomUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSDKChatRoomUsersResp.Unmarshal(m, b)
}
func (m *GetSDKChatRoomUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSDKChatRoomUsersResp.Marshal(b, m, deterministic)
}
func (m *GetSDKChatRoomUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDKChatRoomUsersResp.Merge(m, src)
}
func (m *GetSDKChatRoomUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetSDKChatRoomUsersResp.Size(m)
}
func (m *GetSDKChatRoomUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDKChatRoomUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDKChatRoomUsersResp proto.InternalMessageInfo

func (m *GetSDKChatRoomUsersResp) GetList() []*ChatRoomUsers {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetSDKChatRoomUsersResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*ChatCallBackReq)(nil), "proto.chatCallBackReq")
	proto.RegisterType((*Payload)(nil), "proto.payload")
	proto.RegisterType((*ChatCallBackResp)(nil), "proto.chatCallBackResp")
	proto.RegisterType((*CreateChatRoomReq)(nil), "proto.CreateChatRoomReq")
	proto.RegisterType((*CreateChatRoomResp)(nil), "proto.CreateChatRoomResp")
	proto.RegisterType((*CreateUserReq)(nil), "proto.CreateUserReq")
	proto.RegisterType((*CreateUserResp)(nil), "proto.CreateUserResp")
	proto.RegisterType((*JoinRoomReq)(nil), "proto.JoinRoomReq")
	proto.RegisterType((*RobotJoinRoomReq)(nil), "proto.RobotJoinRoomReq")
	proto.RegisterType((*JoinRoomResp)(nil), "proto.JoinRoomResp")
	proto.RegisterType((*HistMess)(nil), "proto.histMess")
	proto.RegisterType((*SendGiftReq)(nil), "proto.SendGiftReq")
	proto.RegisterType((*SendGiftResp)(nil), "proto.SendGiftResp")
	proto.RegisterType((*SendMessReq)(nil), "proto.SendMessReq")
	proto.RegisterType((*SendMessResp)(nil), "proto.SendMessResp")
	proto.RegisterType((*ToggleLikeReq)(nil), "proto.ToggleLikeReq")
	proto.RegisterType((*ToggleLikeResp)(nil), "proto.ToggleLikeResp")
	proto.RegisterType((*LeaveRoomReq)(nil), "proto.LeaveRoomReq")
	proto.RegisterType((*LeaveRoomResp)(nil), "proto.LeaveRoomResp")
	proto.RegisterType((*FollowUserReq)(nil), "proto.FollowUserReq")
	proto.RegisterType((*FollowUserResp)(nil), "proto.FollowUserResp")
	proto.RegisterType((*IncomeNotifyReq)(nil), "proto.IncomeNotifyReq")
	proto.RegisterType((*IncomeNotifyResp)(nil), "proto.IncomeNotifyResp")
	proto.RegisterType((*GiftNotifyReq)(nil), "proto.GiftNotifyReq")
	proto.RegisterType((*SystemNotifyReq)(nil), "proto.SystemNotifyReq")
	proto.RegisterType((*SystemNotifyResp)(nil), "proto.SystemNotifyResp")
	proto.RegisterType((*GetChatRoomInfoReq)(nil), "proto.GetChatRoomInfoReq")
	proto.RegisterType((*GetChatRoomInfoResp)(nil), "proto.GetChatRoomInfoResp")
	proto.RegisterType((*InsufficientBalanceNoticeReq)(nil), "proto.InsufficientBalanceNoticeReq")
	proto.RegisterType((*InsufficientBalanceNoticeResp)(nil), "proto.InsufficientBalanceNoticeResp")
	proto.RegisterType((*GetChatRoomOnlineUserReq)(nil), "proto.GetChatRoomOnlineUserReq")
	proto.RegisterType((*OnlineUser)(nil), "proto.onlineUser")
	proto.RegisterType((*GetChatRoomOnlineUserResp)(nil), "proto.GetChatRoomOnlineUserResp")
	proto.RegisterType((*UpgradeNotifyReq)(nil), "proto.UpgradeNotifyReq")
	proto.RegisterType((*UpgradeNotifyResp)(nil), "proto.UpgradeNotifyResp")
	proto.RegisterType((*GetSDKOnlineUserStatusReq)(nil), "proto.GetSDKOnlineUserStatusReq")
	proto.RegisterType((*GetSDKOnlineUserStatusResp)(nil), "proto.GetSDKOnlineUserStatusResp")
	proto.RegisterType((*GetSDKChatRoomUsersReq)(nil), "proto.GetSDKChatRoomUsersReq")
	proto.RegisterType((*ChatRoomUsers)(nil), "proto.chatRoomUsers")
	proto.RegisterType((*GetSDKChatRoomUsersResp)(nil), "proto.GetSDKChatRoomUsersResp")
}

func init() {
	proto.RegisterFile("live/chat_room.proto", fileDescriptor_d7246442795c9d7c)
}

var fileDescriptor_d7246442795c9d7c = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdb, 0x6e, 0x1c, 0x45,
	0x13, 0xd6, 0x1e, 0x66, 0xbd, 0x2e, 0x7b, 0x0f, 0xe9, 0xf8, 0xf7, 0x3f, 0x31, 0x01, 0xac, 0x56,
	0x90, 0x56, 0x42, 0x8a, 0x51, 0xc2, 0x2d, 0x37, 0x36, 0x4a, 0xb4, 0x39, 0x21, 0x8d, 0x9d, 0x08,
	0xb8, 0x09, 0xbd, 0xb3, 0xbd, 0xe3, 0x66, 0x67, 0xa6, 0xdb, 0xd3, 0x3d, 0x0e, 0xcb, 0x3d, 0x0f,
	0xc0, 0x6b, 0xf0, 0x0c, 0x3c, 0x09, 0x37, 0xbc, 0x0a, 0xea, 0xd3, 0x1c, 0x1c, 0x1c, 0x2c, 0x12,
	0x71, 0xb5, 0xfd, 0xd5, 0x4c, 0xd7, 0x57, 0xf5, 0x55, 0x75, 0xf5, 0x2c, 0xec, 0xa5, 0xec, 0x92,
	0x1e, 0xc5, 0xe7, 0x44, 0xbd, 0x2e, 0x38, 0xcf, 0xee, 0x8b, 0x82, 0x2b, 0x8e, 0x02, 0xf3, 0x83,
	0x7f, 0xeb, 0xc2, 0x44, 0x3f, 0x3a, 0x21, 0x69, 0x7a, 0x4c, 0xe2, 0x75, 0x44, 0x2f, 0xd0, 0x3e,
	0x0c, 0x62, 0x92, 0xa6, 0xf3, 0x65, 0xd8, 0x39, 0xec, 0xcc, 0xb6, 0x23, 0x87, 0xd0, 0x5d, 0xd8,
	0x56, 0x2c, 0xa3, 0x52, 0x91, 0x4c, 0x84, 0xdd, 0xc3, 0xce, 0xac, 0x17, 0xd5, 0x06, 0xf4, 0x11,
	0x6c, 0x1b, 0x0e, 0xb5, 0x11, 0x34, 0xec, 0x99, 0x8d, 0x43, 0x6d, 0x38, 0xdb, 0x08, 0x8a, 0xee,
	0xc0, 0x30, 0x29, 0x78, 0x29, 0x5e, 0xb3, 0x65, 0xd8, 0x37, 0xcf, 0xb6, 0x0c, 0x9e, 0x2f, 0x11,
	0x82, 0xfe, 0xaa, 0xe0, 0x59, 0x18, 0x18, 0xb3, 0x59, 0xa3, 0x31, 0x74, 0x15, 0x0f, 0x07, 0xc6,
	0xd2, 0x55, 0x1c, 0xfd, 0x0f, 0x06, 0x99, 0x4c, 0xf4, 0xe6, 0x2d, 0x63, 0x0b, 0x32, 0x99, 0xcc,
	0x97, 0x68, 0x06, 0x5b, 0x82, 0x6c, 0x52, 0x4e, 0x96, 0xe1, 0xf0, 0xb0, 0x33, 0xdb, 0x79, 0x30,
	0xb6, 0xc9, 0xdd, 0x77, 0xd6, 0xc8, 0x3f, 0x46, 0x33, 0x98, 0x48, 0x1a, 0x97, 0x05, 0x53, 0x9b,
	0x57, 0xb4, 0x90, 0x8c, 0xe7, 0xe1, 0xb6, 0xf1, 0x74, 0xd5, 0x8c, 0x0e, 0x60, 0xe8, 0x4d, 0x21,
	0xd8, 0x2c, 0x3c, 0xc6, 0xdb, 0x15, 0x1f, 0x7e, 0x05, 0xd3, 0xb6, 0x6c, 0x52, 0xa0, 0x3d, 0x08,
	0x2e, 0x49, 0xca, 0xac, 0x6c, 0xc3, 0xc8, 0x02, 0x9d, 0x5f, 0xcc, 0x97, 0xd4, 0x08, 0xb6, 0x1d,
	0x99, 0x35, 0x0a, 0xeb, 0xc0, 0xad, 0x52, 0x95, 0xdf, 0x04, 0x6e, 0x9d, 0x14, 0x94, 0x28, 0x7a,
	0x72, 0x4e, 0x54, 0xc4, 0x79, 0xa6, 0x0b, 0x72, 0x00, 0x43, 0x92, 0xc7, 0xe7, 0xbc, 0x70, 0x25,
	0x09, 0xa2, 0x0a, 0xa3, 0x4f, 0x00, 0xec, 0xfa, 0x05, 0xc9, 0x3c, 0x49, 0xc3, 0xa2, 0x8b, 0xa9,
	0xab, 0x3e, 0xf7, 0x4c, 0x0e, 0xe1, 0x2f, 0x01, 0x5d, 0x25, 0x92, 0x42, 0x7b, 0x8b, 0x1d, 0xae,
	0xca, 0xdf, 0xb0, 0xe0, 0xc7, 0x30, 0xb2, 0xbb, 0x5e, 0x4a, 0x5a, 0xb8, 0xd0, 0x4a, 0x49, 0x8b,
	0x5c, 0x93, 0xdb, 0xd7, 0x2b, 0xac, 0x9f, 0x09, 0x22, 0xe5, 0x1b, 0x5e, 0x2c, 0x5d, 0x60, 0x15,
	0xc6, 0xf7, 0x60, 0xdc, 0x74, 0x24, 0x85, 0xd6, 0xa9, 0x2c, 0x99, 0x27, 0x35, 0x6b, 0xfc, 0x14,
	0x76, 0x9e, 0x70, 0x96, 0x7b, 0x1d, 0xfe, 0x21, 0x3a, 0xdd, 0xa0, 0x92, 0x97, 0x45, 0x4c, 0xcf,
	0x48, 0xe2, 0x18, 0x6b, 0x03, 0x7e, 0x02, 0xd3, 0x88, 0x2f, 0xb8, 0x6a, 0x7a, 0xdc, 0x87, 0x81,
	0x0e, 0xd7, 0x79, 0xeb, 0x45, 0x0e, 0x5d, 0x61, 0xea, 0xbe, 0xa5, 0xc3, 0x9f, 0x1d, 0xd8, 0xad,
	0xfd, 0xd8, 0xda, 0x13, 0x21, 0xaa, 0xa8, 0x2c, 0xd0, 0xee, 0x89, 0x10, 0x4f, 0xe9, 0xc6, 0xb9,
	0x70, 0x48, 0xbf, 0xad, 0xf8, 0x9a, 0xe6, 0xae, 0x26, 0x16, 0x34, 0x82, 0xe9, 0x9b, 0x22, 0xfb,
	0x60, 0xbc, 0x32, 0x41, 0xad, 0x8c, 0x4e, 0x35, 0x65, 0x6b, 0x7a, 0x46, 0xd2, 0x74, 0x63, 0x0e,
	0x4a, 0x10, 0xd5, 0x06, 0xed, 0x5f, 0x03, 0x7b, 0x5c, 0x82, 0xc8, 0x02, 0xf4, 0x39, 0x0c, 0xcf,
	0x99, 0x54, 0xcf, 0xa9, 0x94, 0xe1, 0xf0, 0xb0, 0x37, 0xdb, 0x79, 0x30, 0x71, 0xe7, 0xc5, 0x9b,
	0xa3, 0xea, 0x05, 0xfc, 0x7b, 0xa7, 0x7e, 0x5b, 0x57, 0x32, 0x67, 0xf1, 0xba, 0x59, 0x65, 0x8f,
	0x75, 0x2f, 0xa7, 0xf4, 0x92, 0xa6, 0x4e, 0xa7, 0x20, 0xf2, 0xb0, 0x91, 0x4f, 0xaf, 0x95, 0x8f,
	0x56, 0xe5, 0x92, 0x28, 0x52, 0xb8, 0x51, 0xe0, 0x90, 0xf6, 0x14, 0xf3, 0x5c, 0xd1, 0x5c, 0xb9,
	0x54, 0x3d, 0xd4, 0xd9, 0x32, 0x79, 0x4c, 0x8a, 0x82, 0x24, 0xd4, 0x67, 0x5b, 0x19, 0xb4, 0x3e,
	0x66, 0xe8, 0xd8, 0xd9, 0x60, 0xd6, 0xf8, 0x39, 0xec, 0x9c, 0xd2, 0x7c, 0xf9, 0x98, 0xad, 0x94,
	0xab, 0x73, 0x51, 0x77, 0x4d, 0xe0, 0x4f, 0x81, 0x16, 0x2a, 0x61, 0xab, 0x2a, 0x74, 0x0b, 0xd0,
	0x14, 0x7a, 0x79, 0x99, 0xb9, 0xa8, 0xf5, 0x12, 0x8f, 0x61, 0xb7, 0x76, 0x27, 0x05, 0x26, 0xd6,
	0xbd, 0xd1, 0xec, 0x06, 0x8d, 0xd9, 0xc8, 0xac, 0xdb, 0xce, 0x2c, 0x84, 0xad, 0x85, 0xcb, 0xcb,
	0xd2, 0x79, 0xe8, 0x29, 0x2d, 0x85, 0x14, 0xf8, 0x08, 0x46, 0x67, 0x3c, 0x49, 0x52, 0xfa, 0x8c,
	0xad, 0xe9, 0x0d, 0x48, 0xf1, 0x7d, 0x18, 0x37, 0x37, 0x48, 0xa1, 0x65, 0xd4, 0x25, 0x78, 0x66,
	0x5a, 0xc3, 0x0a, 0x51, 0x1b, 0xf0, 0x23, 0xd8, 0x7d, 0x46, 0xc9, 0x25, 0xbd, 0xe9, 0x69, 0xab,
	0xcb, 0xdb, 0x6d, 0x96, 0x17, 0x4f, 0x60, 0xd4, 0xf0, 0x23, 0x05, 0x8e, 0x61, 0xf4, 0x88, 0xa7,
	0x29, 0x7f, 0xe3, 0x87, 0xc6, 0xbf, 0xf4, 0xec, 0x87, 0x8d, 0x99, 0x74, 0xbd, 0x7a, 0xd8, 0x68,
	0x8c, 0xa7, 0x30, 0x6e, 0x92, 0x98, 0x1a, 0x4d, 0xe6, 0x79, 0xcc, 0x33, 0xfa, 0x82, 0x2b, 0xb6,
	0xda, 0xbc, 0x0f, 0xf1, 0x3e, 0x0c, 0xac, 0x2b, 0x43, 0xdb, 0x8d, 0x1c, 0xc2, 0x08, 0xa6, 0x6d,
	0x0a, 0x29, 0xf0, 0x05, 0x8c, 0x74, 0x9b, 0x7c, 0x10, 0xd2, 0x84, 0xad, 0x54, 0x7d, 0x7c, 0x2c,
	0xf2, 0xdd, 0xd9, 0xaf, 0xbb, 0xf3, 0xd7, 0x0e, 0x4c, 0x4e, 0x37, 0x52, 0xd1, 0xac, 0x66, 0x6d,
	0x4f, 0xb6, 0xda, 0xeb, 0x21, 0xec, 0xe4, 0xf6, 0x25, 0x92, 0x27, 0xd4, 0x51, 0x36, 0x4d, 0xe8,
	0x1e, 0x8c, 0x2c, 0x3c, 0x71, 0x2d, 0x6b, 0xa5, 0x6e, 0x1b, 0x75, 0x56, 0xd6, 0xa0, 0xef, 0x77,
	0x17, 0x4c, 0xc3, 0xa2, 0xa5, 0x69, 0x87, 0x24, 0x05, 0xde, 0x03, 0xf4, 0x98, 0x2a, 0x7f, 0xe1,
	0xcc, 0xf3, 0x15, 0x8f, 0xe8, 0x05, 0xfe, 0xa5, 0x03, 0xb7, 0xdf, 0x32, 0xff, 0xf7, 0x23, 0x15,
	0xbf, 0x82, 0xbb, 0xf3, 0x5c, 0x96, 0xab, 0x15, 0x8b, 0x19, 0xcd, 0xd5, 0x31, 0x49, 0x49, 0x1e,
	0x9b, 0xca, 0xc6, 0xf4, 0x7d, 0xce, 0xc3, 0xa7, 0xf0, 0xf1, 0x3b, 0xfc, 0x4a, 0x81, 0x7f, 0x84,
	0xb0, 0x91, 0xff, 0x37, 0x79, 0xca, 0x72, 0x7a, 0xd3, 0xa3, 0x82, 0xa0, 0x2f, 0x48, 0x55, 0x47,
	0xb3, 0xb6, 0xf7, 0x6e, 0x42, 0x4f, 0xd9, 0xcf, 0x7e, 0xa8, 0x54, 0x18, 0xff, 0xd1, 0x01, 0xe0,
	0x15, 0xc3, 0xb5, 0x5d, 0x52, 0x8f, 0xe8, 0x6e, 0x6b, 0x44, 0x37, 0x2f, 0x82, 0xde, 0xf5, 0x17,
	0x41, 0xbf, 0x7d, 0x11, 0x4c, 0xa1, 0x27, 0xe9, 0x4f, 0x46, 0xec, 0x20, 0xd2, 0x4b, 0x84, 0x61,
	0x57, 0x4f, 0xc0, 0x82, 0x2d, 0x4a, 0xa5, 0x3f, 0xc6, 0x06, 0xe6, 0xf6, 0x6d, 0xd9, 0x34, 0x17,
	0x93, 0xcf, 0x49, 0xae, 0xd3, 0xb3, 0xf7, 0x58, 0x85, 0x75, 0xb5, 0xf5, 0xfc, 0xcf, 0xcd, 0x77,
	0x5f, 0x10, 0x59, 0x80, 0xbf, 0x85, 0x3b, 0xd7, 0x08, 0x29, 0x05, 0xfa, 0x0c, 0xfa, 0x29, 0x93,
	0x2a, 0xec, 0x98, 0x9b, 0xef, 0x96, 0xbb, 0xf9, 0x6a, 0x2d, 0x22, 0xf3, 0xd8, 0xf6, 0x91, 0x22,
	0xa9, 0xfb, 0xc0, 0xb5, 0x00, 0xff, 0x00, 0xd3, 0x97, 0x22, 0x29, 0xc8, 0xf2, 0x03, 0x0c, 0x13,
	0x7d, 0x39, 0x6b, 0x61, 0x5c, 0x6d, 0x2c, 0xc0, 0xb7, 0xe1, 0xd6, 0x15, 0x06, 0x29, 0xf0, 0x43,
	0x93, 0xd0, 0xe9, 0xd7, 0x4f, 0xeb, 0x5c, 0x4e, 0x15, 0x51, 0xa5, 0x7c, 0xc7, 0x09, 0xc7, 0x5f,
	0xc0, 0xc1, 0x75, 0x9b, 0xec, 0x67, 0xd6, 0x92, 0x28, 0xe2, 0x3f, 0xb3, 0xf4, 0x1a, 0x9f, 0xc3,
	0xbe, 0xdd, 0xe1, 0xa5, 0xd3, 0x7b, 0x0c, 0x87, 0x6f, 0xaf, 0xce, 0x35, 0xed, 0xd5, 0x6d, 0xb7,
	0xd7, 0x15, 0x4d, 0x7a, 0x6f, 0xdd, 0x49, 0x5f, 0xc1, 0x28, 0x6e, 0x72, 0x68, 0x31, 0xf8, 0x9b,
	0x9c, 0x16, 0xfe, 0x90, 0x1b, 0xa0, 0x53, 0xcb, 0x68, 0xb6, 0xa0, 0x55, 0xfb, 0x59, 0x84, 0xbf,
	0x83, 0xff, 0xff, 0x6d, 0xa0, 0x52, 0xa0, 0x59, 0xab, 0xbc, 0x7b, 0xae, 0xbc, 0x2d, 0xb2, 0x77,
	0x55, 0xf8, 0xf8, 0xee, 0xf7, 0x07, 0x17, 0x25, 0x2d, 0xe9, 0x13, 0xbe, 0x38, 0x12, 0xeb, 0xe4,
	0xc8, 0xec, 0x5f, 0x94, 0xab, 0x23, 0xfd, 0xef, 0x69, 0x31, 0x30, 0xf0, 0xe1, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0xb9, 0x2e, 0x8b, 0x4c, 0x0d, 0x00, 0x00,
}
