// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live/config.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigResp struct {
	LiveAppId            string   `protobuf:"bytes,1,opt,name=liveAppId,proto3" json:"liveAppId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResp) Reset()         { *m = ConfigResp{} }
func (m *ConfigResp) String() string { return proto.CompactTextString(m) }
func (*ConfigResp) ProtoMessage()    {}
func (*ConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_42bd284618f1c452, []int{0}
}

func (m *ConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResp.Unmarshal(m, b)
}
func (m *ConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResp.Marshal(b, m, deterministic)
}
func (m *ConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResp.Merge(m, src)
}
func (m *ConfigResp) XXX_Size() int {
	return xxx_messageInfo_ConfigResp.Size(m)
}
func (m *ConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResp proto.InternalMessageInfo

func (m *ConfigResp) GetLiveAppId() string {
	if m != nil {
		return m.LiveAppId
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfigResp)(nil), "proto.ConfigResp")
}

func init() {
	proto.RegisterFile("live/config.proto", fileDescriptor_42bd284618f1c452)
}

var fileDescriptor_42bd284618f1c452 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xc9, 0x2c, 0x4b,
	0xd5, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x5a, 0x5c, 0x5c, 0xce, 0x60, 0xe1, 0xa0, 0xd4, 0xe2, 0x02, 0x21, 0x19, 0x2e, 0x4e,
	0x90, 0x4a, 0xc7, 0x82, 0x02, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80,
	0x93, 0x4c, 0x94, 0x54, 0x61, 0x69, 0x6a, 0x69, 0xaa, 0x57, 0x7e, 0x92, 0x7e, 0x41, 0x76, 0xba,
	0x3e, 0xd8, 0x84, 0xa4, 0xd2, 0x34, 0x7d, 0x90, 0x92, 0x24, 0x36, 0x30, 0xd7, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0xf8, 0xdd, 0xe4, 0x6c, 0x00, 0x00, 0x00,
}
