// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live/family.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 家族主播列表
type FamilyListAnchorResp struct {
	List                 []*FamilyListAnchorResp_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FamilyListAnchorResp) Reset()         { *m = FamilyListAnchorResp{} }
func (m *FamilyListAnchorResp) String() string { return proto.CompactTextString(m) }
func (*FamilyListAnchorResp) ProtoMessage()    {}
func (*FamilyListAnchorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{0}
}

func (m *FamilyListAnchorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyListAnchorResp.Unmarshal(m, b)
}
func (m *FamilyListAnchorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyListAnchorResp.Marshal(b, m, deterministic)
}
func (m *FamilyListAnchorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyListAnchorResp.Merge(m, src)
}
func (m *FamilyListAnchorResp) XXX_Size() int {
	return xxx_messageInfo_FamilyListAnchorResp.Size(m)
}
func (m *FamilyListAnchorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyListAnchorResp.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyListAnchorResp proto.InternalMessageInfo

func (m *FamilyListAnchorResp) GetList() []*FamilyListAnchorResp_Item {
	if m != nil {
		return m.List
	}
	return nil
}

type FamilyListAnchorResp_Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	AnchorId             int32    `protobuf:"varint,2,opt,name=anchorId,proto3" json:"anchorId"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	Sex                  int32    `protobuf:"varint,5,opt,name=sex,proto3" json:"sex"`
	PlatformRatio        int32    `protobuf:"varint,6,opt,name=platformRatio,proto3" json:"platformRatio"`
	FamilyRatio          int32    `protobuf:"varint,7,opt,name=familyRatio,proto3" json:"familyRatio"`
	AnchorRatio          int32    `protobuf:"varint,8,opt,name=anchorRatio,proto3" json:"anchorRatio"`
	PaidPurviewStatus    int32    `protobuf:"varint,9,opt,name=paidPurviewStatus,proto3" json:"paidPurviewStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyListAnchorResp_Item) Reset()         { *m = FamilyListAnchorResp_Item{} }
func (m *FamilyListAnchorResp_Item) String() string { return proto.CompactTextString(m) }
func (*FamilyListAnchorResp_Item) ProtoMessage()    {}
func (*FamilyListAnchorResp_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{0, 0}
}

func (m *FamilyListAnchorResp_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyListAnchorResp_Item.Unmarshal(m, b)
}
func (m *FamilyListAnchorResp_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyListAnchorResp_Item.Marshal(b, m, deterministic)
}
func (m *FamilyListAnchorResp_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyListAnchorResp_Item.Merge(m, src)
}
func (m *FamilyListAnchorResp_Item) XXX_Size() int {
	return xxx_messageInfo_FamilyListAnchorResp_Item.Size(m)
}
func (m *FamilyListAnchorResp_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyListAnchorResp_Item.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyListAnchorResp_Item proto.InternalMessageInfo

func (m *FamilyListAnchorResp_Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *FamilyListAnchorResp_Item) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FamilyListAnchorResp_Item) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetPlatformRatio() int32 {
	if m != nil {
		return m.PlatformRatio
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetFamilyRatio() int32 {
	if m != nil {
		return m.FamilyRatio
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetAnchorRatio() int32 {
	if m != nil {
		return m.AnchorRatio
	}
	return 0
}

func (m *FamilyListAnchorResp_Item) GetPaidPurviewStatus() int32 {
	if m != nil {
		return m.PaidPurviewStatus
	}
	return 0
}

// 新增主播
type FamilyAddAnchorReq struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	AreaCode             string   `protobuf:"bytes,2,opt,name=areaCode,proto3" json:"areaCode"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyAddAnchorReq) Reset()         { *m = FamilyAddAnchorReq{} }
func (m *FamilyAddAnchorReq) String() string { return proto.CompactTextString(m) }
func (*FamilyAddAnchorReq) ProtoMessage()    {}
func (*FamilyAddAnchorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{1}
}

func (m *FamilyAddAnchorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyAddAnchorReq.Unmarshal(m, b)
}
func (m *FamilyAddAnchorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyAddAnchorReq.Marshal(b, m, deterministic)
}
func (m *FamilyAddAnchorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyAddAnchorReq.Merge(m, src)
}
func (m *FamilyAddAnchorReq) XXX_Size() int {
	return xxx_messageInfo_FamilyAddAnchorReq.Size(m)
}
func (m *FamilyAddAnchorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyAddAnchorReq.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyAddAnchorReq proto.InternalMessageInfo

func (m *FamilyAddAnchorReq) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *FamilyAddAnchorReq) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *FamilyAddAnchorReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

// 取消主播
type FamilyCancelAnchorReq struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyCancelAnchorReq) Reset()         { *m = FamilyCancelAnchorReq{} }
func (m *FamilyCancelAnchorReq) String() string { return proto.CompactTextString(m) }
func (*FamilyCancelAnchorReq) ProtoMessage()    {}
func (*FamilyCancelAnchorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{2}
}

func (m *FamilyCancelAnchorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyCancelAnchorReq.Unmarshal(m, b)
}
func (m *FamilyCancelAnchorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyCancelAnchorReq.Marshal(b, m, deterministic)
}
func (m *FamilyCancelAnchorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyCancelAnchorReq.Merge(m, src)
}
func (m *FamilyCancelAnchorReq) XXX_Size() int {
	return xxx_messageInfo_FamilyCancelAnchorReq.Size(m)
}
func (m *FamilyCancelAnchorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyCancelAnchorReq.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyCancelAnchorReq proto.InternalMessageInfo

func (m *FamilyCancelAnchorReq) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

// 修改家族主播数据
type FamilyModifyAnchorScaleReq struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	AnchorRatio          int32    `protobuf:"varint,2,opt,name=anchorRatio,proto3" json:"anchorRatio"`
	FamilyRatio          int32    `protobuf:"varint,3,opt,name=familyRatio,proto3" json:"familyRatio"`
	PlatformRatio        int32    `protobuf:"varint,4,opt,name=platformRatio,proto3" json:"platformRatio"`
	PaidPurviewStatus    int32    `protobuf:"varint,5,opt,name=paidPurviewStatus,proto3" json:"paidPurviewStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyModifyAnchorScaleReq) Reset()         { *m = FamilyModifyAnchorScaleReq{} }
func (m *FamilyModifyAnchorScaleReq) String() string { return proto.CompactTextString(m) }
func (*FamilyModifyAnchorScaleReq) ProtoMessage()    {}
func (*FamilyModifyAnchorScaleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{3}
}

func (m *FamilyModifyAnchorScaleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyModifyAnchorScaleReq.Unmarshal(m, b)
}
func (m *FamilyModifyAnchorScaleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyModifyAnchorScaleReq.Marshal(b, m, deterministic)
}
func (m *FamilyModifyAnchorScaleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyModifyAnchorScaleReq.Merge(m, src)
}
func (m *FamilyModifyAnchorScaleReq) XXX_Size() int {
	return xxx_messageInfo_FamilyModifyAnchorScaleReq.Size(m)
}
func (m *FamilyModifyAnchorScaleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyModifyAnchorScaleReq.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyModifyAnchorScaleReq proto.InternalMessageInfo

func (m *FamilyModifyAnchorScaleReq) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *FamilyModifyAnchorScaleReq) GetAnchorRatio() int32 {
	if m != nil {
		return m.AnchorRatio
	}
	return 0
}

func (m *FamilyModifyAnchorScaleReq) GetFamilyRatio() int32 {
	if m != nil {
		return m.FamilyRatio
	}
	return 0
}

func (m *FamilyModifyAnchorScaleReq) GetPlatformRatio() int32 {
	if m != nil {
		return m.PlatformRatio
	}
	return 0
}

func (m *FamilyModifyAnchorScaleReq) GetPaidPurviewStatus() int32 {
	if m != nil {
		return m.PaidPurviewStatus
	}
	return 0
}

// 家族详情
type FamilyDetailResp struct {
	FamilyId             int32    `protobuf:"varint,1,opt,name=familyId,proto3" json:"familyId"`
	PlatformRatio        int32    `protobuf:"varint,2,opt,name=platformRatio,proto3" json:"platformRatio"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName"`
	Income               string   `protobuf:"bytes,4,opt,name=income,proto3" json:"income"`
	AddUpIncome          string   `protobuf:"bytes,5,opt,name=addUpIncome,proto3" json:"addUpIncome"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyDetailResp) Reset()         { *m = FamilyDetailResp{} }
func (m *FamilyDetailResp) String() string { return proto.CompactTextString(m) }
func (*FamilyDetailResp) ProtoMessage()    {}
func (*FamilyDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{4}
}

func (m *FamilyDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyDetailResp.Unmarshal(m, b)
}
func (m *FamilyDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyDetailResp.Marshal(b, m, deterministic)
}
func (m *FamilyDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyDetailResp.Merge(m, src)
}
func (m *FamilyDetailResp) XXX_Size() int {
	return xxx_messageInfo_FamilyDetailResp.Size(m)
}
func (m *FamilyDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyDetailResp proto.InternalMessageInfo

func (m *FamilyDetailResp) GetFamilyId() int32 {
	if m != nil {
		return m.FamilyId
	}
	return 0
}

func (m *FamilyDetailResp) GetPlatformRatio() int32 {
	if m != nil {
		return m.PlatformRatio
	}
	return 0
}

func (m *FamilyDetailResp) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *FamilyDetailResp) GetIncome() string {
	if m != nil {
		return m.Income
	}
	return ""
}

func (m *FamilyDetailResp) GetAddUpIncome() string {
	if m != nil {
		return m.AddUpIncome
	}
	return ""
}

// 家族主播收益请求
type FamilyAnchorIncomeReq struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyAnchorIncomeReq) Reset()         { *m = FamilyAnchorIncomeReq{} }
func (m *FamilyAnchorIncomeReq) String() string { return proto.CompactTextString(m) }
func (*FamilyAnchorIncomeReq) ProtoMessage()    {}
func (*FamilyAnchorIncomeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{5}
}

func (m *FamilyAnchorIncomeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyAnchorIncomeReq.Unmarshal(m, b)
}
func (m *FamilyAnchorIncomeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyAnchorIncomeReq.Marshal(b, m, deterministic)
}
func (m *FamilyAnchorIncomeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyAnchorIncomeReq.Merge(m, src)
}
func (m *FamilyAnchorIncomeReq) XXX_Size() int {
	return xxx_messageInfo_FamilyAnchorIncomeReq.Size(m)
}
func (m *FamilyAnchorIncomeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyAnchorIncomeReq.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyAnchorIncomeReq proto.InternalMessageInfo

func (m *FamilyAnchorIncomeReq) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

// 家族主播收益响应
type FamilyAnchorIncomeResp struct {
	Income               string   `protobuf:"bytes,1,opt,name=income,proto3" json:"income"`
	CumulativeIncome     string   `protobuf:"bytes,2,opt,name=cumulativeIncome,proto3" json:"cumulativeIncome"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyAnchorIncomeResp) Reset()         { *m = FamilyAnchorIncomeResp{} }
func (m *FamilyAnchorIncomeResp) String() string { return proto.CompactTextString(m) }
func (*FamilyAnchorIncomeResp) ProtoMessage()    {}
func (*FamilyAnchorIncomeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7408cf969d3c0b, []int{6}
}

func (m *FamilyAnchorIncomeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyAnchorIncomeResp.Unmarshal(m, b)
}
func (m *FamilyAnchorIncomeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyAnchorIncomeResp.Marshal(b, m, deterministic)
}
func (m *FamilyAnchorIncomeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyAnchorIncomeResp.Merge(m, src)
}
func (m *FamilyAnchorIncomeResp) XXX_Size() int {
	return xxx_messageInfo_FamilyAnchorIncomeResp.Size(m)
}
func (m *FamilyAnchorIncomeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyAnchorIncomeResp.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyAnchorIncomeResp proto.InternalMessageInfo

func (m *FamilyAnchorIncomeResp) GetIncome() string {
	if m != nil {
		return m.Income
	}
	return ""
}

func (m *FamilyAnchorIncomeResp) GetCumulativeIncome() string {
	if m != nil {
		return m.CumulativeIncome
	}
	return ""
}

func init() {
	proto.RegisterType((*FamilyListAnchorResp)(nil), "proto.FamilyListAnchorResp")
	proto.RegisterType((*FamilyListAnchorResp_Item)(nil), "proto.FamilyListAnchorResp.Item")
	proto.RegisterType((*FamilyAddAnchorReq)(nil), "proto.FamilyAddAnchorReq")
	proto.RegisterType((*FamilyCancelAnchorReq)(nil), "proto.FamilyCancelAnchorReq")
	proto.RegisterType((*FamilyModifyAnchorScaleReq)(nil), "proto.FamilyModifyAnchorScaleReq")
	proto.RegisterType((*FamilyDetailResp)(nil), "proto.FamilyDetailResp")
	proto.RegisterType((*FamilyAnchorIncomeReq)(nil), "proto.FamilyAnchorIncomeReq")
	proto.RegisterType((*FamilyAnchorIncomeResp)(nil), "proto.FamilyAnchorIncomeResp")
}

func init() {
	proto.RegisterFile("live/family.proto", fileDescriptor_df7408cf969d3c0b)
}

var fileDescriptor_df7408cf969d3c0b = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0xda, 0xd4, 0xf6, 0x2c, 0x4a, 0x77, 0xd0, 0x65, 0x08, 0x22, 0xa1, 0x78, 0x51,
	0x44, 0x5a, 0x70, 0x7d, 0x81, 0x75, 0x45, 0xa8, 0xa8, 0x48, 0x16, 0x6f, 0xc4, 0x9b, 0x69, 0x66,
	0xaa, 0xc3, 0x4e, 0x32, 0xd9, 0x64, 0x52, 0xdd, 0xb7, 0xf0, 0x49, 0x7c, 0x16, 0xdf, 0xc0, 0x57,
	0x91, 0x9c, 0xd3, 0x3f, 0xe9, 0x26, 0x52, 0xaf, 0xda, 0xef, 0x3b, 0xdf, 0xe9, 0x9c, 0xfc, 0xce,
	0x34, 0x70, 0x6a, 0xf4, 0x5a, 0xcd, 0x57, 0x22, 0xd5, 0xe6, 0x76, 0x96, 0x17, 0xd6, 0x59, 0x16,
	0xe0, 0xc7, 0xe4, 0x8f, 0x0f, 0x0f, 0xdf, 0xa0, 0xff, 0x4e, 0x97, 0xee, 0x22, 0x4b, 0xbe, 0xd9,
	0x22, 0x56, 0x65, 0xce, 0x5e, 0x42, 0xdf, 0xe8, 0xd2, 0x71, 0x2f, 0xea, 0x4d, 0x4f, 0x5e, 0x44,
	0xd4, 0x35, 0xeb, 0x8a, 0xce, 0x16, 0x4e, 0xa5, 0x31, 0xa6, 0xc3, 0x9f, 0x3e, 0xf4, 0x6b, 0xc9,
	0x1e, 0x80, 0xaf, 0x25, 0xf7, 0x22, 0x6f, 0x1a, 0xc4, 0xbe, 0x96, 0x2c, 0x84, 0xa1, 0xc0, 0x8e,
	0x85, 0xe4, 0x3e, 0xba, 0x3b, 0x5d, 0xd7, 0x32, 0x9d, 0x5c, 0x67, 0x22, 0x55, 0xbc, 0x17, 0x79,
	0xd3, 0x51, 0xbc, 0xd3, 0xec, 0x0c, 0x06, 0x62, 0x2d, 0x9c, 0x28, 0x78, 0x1f, 0x2b, 0x1b, 0xc5,
	0xc6, 0xd0, 0x2b, 0xd5, 0x0f, 0x1e, 0xe0, 0x4f, 0xd5, 0x5f, 0xd9, 0x53, 0xb8, 0x9f, 0x1b, 0xe1,
	0x56, 0xb6, 0x48, 0x63, 0xe1, 0xb4, 0xe5, 0x03, 0xac, 0x1d, 0x9a, 0x2c, 0x82, 0x13, 0xc2, 0x40,
	0x99, 0x7b, 0x98, 0x69, 0x5a, 0x75, 0x82, 0x26, 0xa3, 0xc4, 0x90, 0x12, 0x0d, 0x8b, 0x3d, 0x87,
	0xd3, 0x5c, 0x68, 0xf9, 0xb1, 0x2a, 0xd6, 0x5a, 0x7d, 0xbf, 0x72, 0xc2, 0x55, 0x25, 0x1f, 0x61,
	0xae, 0x5d, 0x98, 0x48, 0x60, 0x44, 0xed, 0x42, 0xca, 0x2d, 0xb4, 0x9b, 0x03, 0x1e, 0x5e, 0x9b,
	0x87, 0x28, 0x94, 0xb8, 0xb4, 0x52, 0x21, 0xab, 0x51, 0xbc, 0xd3, 0x35, 0x8f, 0xd4, 0x2e, 0xb5,
	0xd9, 0x92, 0xda, 0xa8, 0xc9, 0x39, 0x3c, 0xa2, 0x53, 0x2e, 0x45, 0x96, 0x28, 0xf3, 0x5f, 0x07,
	0x4d, 0x7e, 0x7b, 0x10, 0x52, 0xd7, 0x7b, 0x2b, 0xf5, 0xea, 0x96, 0xba, 0xae, 0x12, 0x61, 0xd4,
	0xb1, 0x19, 0xef, 0x50, 0xf2, 0xdb, 0x94, 0xee, 0x90, 0xee, 0xb5, 0x49, 0xb7, 0x36, 0xd6, 0xef,
	0xda, 0x58, 0x27, 0xed, 0xe0, 0x5f, 0xb4, 0x7f, 0x79, 0x30, 0xa6, 0x47, 0x7a, 0xad, 0x9c, 0xd0,
	0x06, 0xef, 0x72, 0x08, 0x43, 0x3a, 0x77, 0xff, 0x20, 0x5b, 0xdd, 0x1e, 0xc2, 0xef, 0x1a, 0xe2,
	0x09, 0x00, 0x75, 0x7c, 0xd8, 0x5f, 0xd2, 0x86, 0x53, 0xaf, 0x45, 0x67, 0x89, 0x4d, 0xd5, 0xf6,
	0x9a, 0x92, 0x42, 0x4c, 0x52, 0x7e, 0xca, 0x17, 0x54, 0x0c, 0xb0, 0xd8, 0xb4, 0xf6, 0x8b, 0x23,
	0xf8, 0xe4, 0x1e, 0x5b, 0xdc, 0x17, 0x38, 0xeb, 0x6a, 0x2a, 0xf3, 0xc6, 0x20, 0xde, 0xc1, 0x20,
	0xcf, 0x60, 0x9c, 0x54, 0x69, 0x65, 0x84, 0xd3, 0x6b, 0xb5, 0x99, 0x86, 0xee, 0x56, 0xcb, 0x7f,
	0xf5, 0xf8, 0x73, 0x78, 0x53, 0xa9, 0x4a, 0xbd, 0xb5, 0xcb, 0x79, 0x7e, 0xfd, 0x75, 0x8e, 0x7f,
	0xfd, 0x65, 0xb5, 0x9a, 0xd7, 0x6f, 0x91, 0xe5, 0x00, 0xe5, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe2, 0x61, 0xfb, 0x3e, 0x54, 0x04, 0x00, 0x00,
}
