// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live/gift.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GiftsResp struct {
	List                 []*GiftItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GiftsResp) Reset()         { *m = GiftsResp{} }
func (m *GiftsResp) String() string { return proto.CompactTextString(m) }
func (*GiftsResp) ProtoMessage()    {}
func (*GiftsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{0}
}

func (m *GiftsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiftsResp.Unmarshal(m, b)
}
func (m *GiftsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiftsResp.Marshal(b, m, deterministic)
}
func (m *GiftsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiftsResp.Merge(m, src)
}
func (m *GiftsResp) XXX_Size() int {
	return xxx_messageInfo_GiftsResp.Size(m)
}
func (m *GiftsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GiftsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GiftsResp proto.InternalMessageInfo

func (m *GiftsResp) GetList() []*GiftItem {
	if m != nil {
		return m.List
	}
	return nil
}

type GiftItem struct {
	GiftId               int32    `protobuf:"varint,1,opt,name=giftId,proto3" json:"giftId"`
	GiftName             string   `protobuf:"bytes,2,opt,name=giftName,proto3" json:"giftName"`
	Category             int32    `protobuf:"varint,3,opt,name=category,proto3" json:"category"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price"`
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon"`
	Animation            string   `protobuf:"bytes,6,opt,name=animation,proto3" json:"animation"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GiftItem) Reset()         { *m = GiftItem{} }
func (m *GiftItem) String() string { return proto.CompactTextString(m) }
func (*GiftItem) ProtoMessage()    {}
func (*GiftItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{1}
}

func (m *GiftItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GiftItem.Unmarshal(m, b)
}
func (m *GiftItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GiftItem.Marshal(b, m, deterministic)
}
func (m *GiftItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GiftItem.Merge(m, src)
}
func (m *GiftItem) XXX_Size() int {
	return xxx_messageInfo_GiftItem.Size(m)
}
func (m *GiftItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GiftItem.DiscardUnknown(m)
}

var xxx_messageInfo_GiftItem proto.InternalMessageInfo

func (m *GiftItem) GetGiftId() int32 {
	if m != nil {
		return m.GiftId
	}
	return 0
}

func (m *GiftItem) GetGiftName() string {
	if m != nil {
		return m.GiftName
	}
	return ""
}

func (m *GiftItem) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *GiftItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GiftItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GiftItem) GetAnimation() string {
	if m != nil {
		return m.Animation
	}
	return ""
}

// 用户坐骑列表响应
type MountResp struct {
	List                 []*MountResp_MountItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MountResp) Reset()         { *m = MountResp{} }
func (m *MountResp) String() string { return proto.CompactTextString(m) }
func (*MountResp) ProtoMessage()    {}
func (*MountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{2}
}

func (m *MountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountResp.Unmarshal(m, b)
}
func (m *MountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountResp.Marshal(b, m, deterministic)
}
func (m *MountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountResp.Merge(m, src)
}
func (m *MountResp) XXX_Size() int {
	return xxx_messageInfo_MountResp.Size(m)
}
func (m *MountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MountResp.DiscardUnknown(m)
}

var xxx_messageInfo_MountResp proto.InternalMessageInfo

func (m *MountResp) GetList() []*MountResp_MountItem {
	if m != nil {
		return m.List
	}
	return nil
}

type MountResp_MountItem struct {
	MountId              int32    `protobuf:"varint,1,opt,name=mountId,proto3" json:"mountId"`
	MountName            string   `protobuf:"bytes,2,opt,name=mountName,proto3" json:"mountName"`
	BuyPrice             int32    `protobuf:"varint,3,opt,name=buyPrice,proto3" json:"buyPrice"`
	RenewalPrice         int32    `protobuf:"varint,4,opt,name=renewalPrice,proto3" json:"renewalPrice"`
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon"`
	Animation            string   `protobuf:"bytes,6,opt,name=animation,proto3" json:"animation"`
	IsHave               int32    `protobuf:"varint,7,opt,name=isHave,proto3" json:"isHave"`
	ExpiredTime          int32    `protobuf:"varint,8,opt,name=expiredTime,proto3" json:"expiredTime"`
	IsUse                int32    `protobuf:"varint,9,opt,name=isUse,proto3" json:"isUse"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountResp_MountItem) Reset()         { *m = MountResp_MountItem{} }
func (m *MountResp_MountItem) String() string { return proto.CompactTextString(m) }
func (*MountResp_MountItem) ProtoMessage()    {}
func (*MountResp_MountItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{2, 0}
}

func (m *MountResp_MountItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountResp_MountItem.Unmarshal(m, b)
}
func (m *MountResp_MountItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountResp_MountItem.Marshal(b, m, deterministic)
}
func (m *MountResp_MountItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountResp_MountItem.Merge(m, src)
}
func (m *MountResp_MountItem) XXX_Size() int {
	return xxx_messageInfo_MountResp_MountItem.Size(m)
}
func (m *MountResp_MountItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MountResp_MountItem.DiscardUnknown(m)
}

var xxx_messageInfo_MountResp_MountItem proto.InternalMessageInfo

func (m *MountResp_MountItem) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

func (m *MountResp_MountItem) GetMountName() string {
	if m != nil {
		return m.MountName
	}
	return ""
}

func (m *MountResp_MountItem) GetBuyPrice() int32 {
	if m != nil {
		return m.BuyPrice
	}
	return 0
}

func (m *MountResp_MountItem) GetRenewalPrice() int32 {
	if m != nil {
		return m.RenewalPrice
	}
	return 0
}

func (m *MountResp_MountItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MountResp_MountItem) GetAnimation() string {
	if m != nil {
		return m.Animation
	}
	return ""
}

func (m *MountResp_MountItem) GetIsHave() int32 {
	if m != nil {
		return m.IsHave
	}
	return 0
}

func (m *MountResp_MountItem) GetExpiredTime() int32 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MountResp_MountItem) GetIsUse() int32 {
	if m != nil {
		return m.IsUse
	}
	return 0
}

// 购买续费坐骑
type BuyRenewalMountReq struct {
	MountId              int32    `protobuf:"varint,1,opt,name=mountId,proto3" json:"mountId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyRenewalMountReq) Reset()         { *m = BuyRenewalMountReq{} }
func (m *BuyRenewalMountReq) String() string { return proto.CompactTextString(m) }
func (*BuyRenewalMountReq) ProtoMessage()    {}
func (*BuyRenewalMountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{3}
}

func (m *BuyRenewalMountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyRenewalMountReq.Unmarshal(m, b)
}
func (m *BuyRenewalMountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyRenewalMountReq.Marshal(b, m, deterministic)
}
func (m *BuyRenewalMountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyRenewalMountReq.Merge(m, src)
}
func (m *BuyRenewalMountReq) XXX_Size() int {
	return xxx_messageInfo_BuyRenewalMountReq.Size(m)
}
func (m *BuyRenewalMountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyRenewalMountReq.DiscardUnknown(m)
}

var xxx_messageInfo_BuyRenewalMountReq proto.InternalMessageInfo

func (m *BuyRenewalMountReq) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

// 使用坐骑
type UesMountReq struct {
	MountId              int32    `protobuf:"varint,1,opt,name=mountId,proto3" json:"mountId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UesMountReq) Reset()         { *m = UesMountReq{} }
func (m *UesMountReq) String() string { return proto.CompactTextString(m) }
func (*UesMountReq) ProtoMessage()    {}
func (*UesMountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{4}
}

func (m *UesMountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UesMountReq.Unmarshal(m, b)
}
func (m *UesMountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UesMountReq.Marshal(b, m, deterministic)
}
func (m *UesMountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UesMountReq.Merge(m, src)
}
func (m *UesMountReq) XXX_Size() int {
	return xxx_messageInfo_UesMountReq.Size(m)
}
func (m *UesMountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UesMountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UesMountReq proto.InternalMessageInfo

func (m *UesMountReq) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

// 跳蛋列表响应
type ListVibratorResp struct {
	List                 []*ListVibratorItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListVibratorResp) Reset()         { *m = ListVibratorResp{} }
func (m *ListVibratorResp) String() string { return proto.CompactTextString(m) }
func (*ListVibratorResp) ProtoMessage()    {}
func (*ListVibratorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{5}
}

func (m *ListVibratorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVibratorResp.Unmarshal(m, b)
}
func (m *ListVibratorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVibratorResp.Marshal(b, m, deterministic)
}
func (m *ListVibratorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVibratorResp.Merge(m, src)
}
func (m *ListVibratorResp) XXX_Size() int {
	return xxx_messageInfo_ListVibratorResp.Size(m)
}
func (m *ListVibratorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVibratorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListVibratorResp proto.InternalMessageInfo

func (m *ListVibratorResp) GetList() []*ListVibratorItem {
	if m != nil {
		return m.List
	}
	return nil
}

type ListVibratorItem struct {
	VibratorId           int32    `protobuf:"varint,1,opt,name=vibratorId,proto3" json:"vibratorId"`
	VibratorName         string   `protobuf:"bytes,2,opt,name=vibratorName,proto3" json:"vibratorName"`
	Category             int32    `protobuf:"varint,3,opt,name=category,proto3" json:"category"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price"`
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon"`
	Animation            string   `protobuf:"bytes,6,opt,name=animation,proto3" json:"animation"`
	Duration             int32    `protobuf:"varint,7,opt,name=duration,proto3" json:"duration"`
	Strength             int32    `protobuf:"varint,8,opt,name=strength,proto3" json:"strength"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVibratorItem) Reset()         { *m = ListVibratorItem{} }
func (m *ListVibratorItem) String() string { return proto.CompactTextString(m) }
func (*ListVibratorItem) ProtoMessage()    {}
func (*ListVibratorItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{6}
}

func (m *ListVibratorItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVibratorItem.Unmarshal(m, b)
}
func (m *ListVibratorItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVibratorItem.Marshal(b, m, deterministic)
}
func (m *ListVibratorItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVibratorItem.Merge(m, src)
}
func (m *ListVibratorItem) XXX_Size() int {
	return xxx_messageInfo_ListVibratorItem.Size(m)
}
func (m *ListVibratorItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVibratorItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListVibratorItem proto.InternalMessageInfo

func (m *ListVibratorItem) GetVibratorId() int32 {
	if m != nil {
		return m.VibratorId
	}
	return 0
}

func (m *ListVibratorItem) GetVibratorName() string {
	if m != nil {
		return m.VibratorName
	}
	return ""
}

func (m *ListVibratorItem) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *ListVibratorItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListVibratorItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *ListVibratorItem) GetAnimation() string {
	if m != nil {
		return m.Animation
	}
	return ""
}

func (m *ListVibratorItem) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ListVibratorItem) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

// 坐骑列表响应
type MountListResp struct {
	List                 []*MountListResp_MountItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MountListResp) Reset()         { *m = MountListResp{} }
func (m *MountListResp) String() string { return proto.CompactTextString(m) }
func (*MountListResp) ProtoMessage()    {}
func (*MountListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{7}
}

func (m *MountListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountListResp.Unmarshal(m, b)
}
func (m *MountListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountListResp.Marshal(b, m, deterministic)
}
func (m *MountListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountListResp.Merge(m, src)
}
func (m *MountListResp) XXX_Size() int {
	return xxx_messageInfo_MountListResp.Size(m)
}
func (m *MountListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MountListResp.DiscardUnknown(m)
}

var xxx_messageInfo_MountListResp proto.InternalMessageInfo

func (m *MountListResp) GetList() []*MountListResp_MountItem {
	if m != nil {
		return m.List
	}
	return nil
}

type MountListResp_MountItem struct {
	MountId              int32    `protobuf:"varint,1,opt,name=mountId,proto3" json:"mountId"`
	MountName            string   `protobuf:"bytes,2,opt,name=mountName,proto3" json:"mountName"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon"`
	Animation            string   `protobuf:"bytes,4,opt,name=animation,proto3" json:"animation"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountListResp_MountItem) Reset()         { *m = MountListResp_MountItem{} }
func (m *MountListResp_MountItem) String() string { return proto.CompactTextString(m) }
func (*MountListResp_MountItem) ProtoMessage()    {}
func (*MountListResp_MountItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{7, 0}
}

func (m *MountListResp_MountItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountListResp_MountItem.Unmarshal(m, b)
}
func (m *MountListResp_MountItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountListResp_MountItem.Marshal(b, m, deterministic)
}
func (m *MountListResp_MountItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountListResp_MountItem.Merge(m, src)
}
func (m *MountListResp_MountItem) XXX_Size() int {
	return xxx_messageInfo_MountListResp_MountItem.Size(m)
}
func (m *MountListResp_MountItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MountListResp_MountItem.DiscardUnknown(m)
}

var xxx_messageInfo_MountListResp_MountItem proto.InternalMessageInfo

func (m *MountListResp_MountItem) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

func (m *MountListResp_MountItem) GetMountName() string {
	if m != nil {
		return m.MountName
	}
	return ""
}

func (m *MountListResp_MountItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MountListResp_MountItem) GetAnimation() string {
	if m != nil {
		return m.Animation
	}
	return ""
}

// 使用坐骑
type UnUesMountReq struct {
	MountId              int32    `protobuf:"varint,1,opt,name=mountId,proto3" json:"mountId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnUesMountReq) Reset()         { *m = UnUesMountReq{} }
func (m *UnUesMountReq) String() string { return proto.CompactTextString(m) }
func (*UnUesMountReq) ProtoMessage()    {}
func (*UnUesMountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba1053056acb885a, []int{8}
}

func (m *UnUesMountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnUesMountReq.Unmarshal(m, b)
}
func (m *UnUesMountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnUesMountReq.Marshal(b, m, deterministic)
}
func (m *UnUesMountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnUesMountReq.Merge(m, src)
}
func (m *UnUesMountReq) XXX_Size() int {
	return xxx_messageInfo_UnUesMountReq.Size(m)
}
func (m *UnUesMountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnUesMountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnUesMountReq proto.InternalMessageInfo

func (m *UnUesMountReq) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

func init() {
	proto.RegisterType((*GiftsResp)(nil), "proto.GiftsResp")
	proto.RegisterType((*GiftItem)(nil), "proto.GiftItem")
	proto.RegisterType((*MountResp)(nil), "proto.MountResp")
	proto.RegisterType((*MountResp_MountItem)(nil), "proto.MountResp.MountItem")
	proto.RegisterType((*BuyRenewalMountReq)(nil), "proto.BuyRenewalMountReq")
	proto.RegisterType((*UesMountReq)(nil), "proto.UesMountReq")
	proto.RegisterType((*ListVibratorResp)(nil), "proto.ListVibratorResp")
	proto.RegisterType((*ListVibratorItem)(nil), "proto.ListVibratorItem")
	proto.RegisterType((*MountListResp)(nil), "proto.MountListResp")
	proto.RegisterType((*MountListResp_MountItem)(nil), "proto.MountListResp.MountItem")
	proto.RegisterType((*UnUesMountReq)(nil), "proto.UnUesMountReq")
}

func init() {
	proto.RegisterFile("live/gift.proto", fileDescriptor_ba1053056acb885a)
}

var fileDescriptor_ba1053056acb885a = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0xc9, 0xf6, 0xcf, 0x36, 0xa7, 0x2e, 0x2b, 0x83, 0xe8, 0x50, 0x96, 0xa5, 0xc4, 0x0b,
	0x2b, 0x42, 0x2b, 0xeb, 0x03, 0x08, 0x7b, 0xa3, 0x2b, 0x2a, 0x4b, 0xb0, 0x5e, 0x78, 0x97, 0xb4,
	0xa7, 0x75, 0xb0, 0xf9, 0xb3, 0x33, 0x93, 0x6a, 0x1f, 0xc0, 0x17, 0xf1, 0x31, 0xbc, 0xf5, 0x8d,
	0x7c, 0x02, 0x99, 0x33, 0x99, 0x74, 0xa2, 0x2c, 0x54, 0x10, 0xaf, 0x3a, 0xdf, 0xf9, 0x26, 0x93,
	0xf9, 0x9d, 0xef, 0x34, 0x70, 0xba, 0x11, 0x5b, 0x9c, 0xad, 0xc5, 0x4a, 0x4f, 0x4b, 0x59, 0xe8,
	0x82, 0xf5, 0xe8, 0x27, 0x7a, 0x0a, 0xe1, 0x0b, 0xb1, 0xd2, 0x2a, 0x46, 0x55, 0xb2, 0x87, 0xd0,
	0xdd, 0x08, 0xa5, 0x79, 0x30, 0xee, 0x4c, 0x86, 0x17, 0xa7, 0x76, 0xe7, 0xd4, 0xf8, 0x57, 0x1a,
	0xb3, 0x98, 0xcc, 0xe8, 0x5b, 0x00, 0x03, 0x57, 0x62, 0xf7, 0xa1, 0x6f, 0xce, 0xbc, 0x5a, 0xf2,
	0x60, 0x1c, 0x4c, 0x7a, 0x71, 0xad, 0xd8, 0x08, 0x06, 0x66, 0xf5, 0x36, 0xc9, 0x90, 0x1f, 0x8d,
	0x83, 0x49, 0x18, 0x37, 0xda, 0x78, 0x8b, 0x44, 0xe3, 0xba, 0x90, 0x3b, 0xde, 0xa1, 0xa7, 0x1a,
	0xcd, 0xee, 0x41, 0xaf, 0x94, 0x62, 0x81, 0xbc, 0x4b, 0x86, 0x15, 0x8c, 0x41, 0x57, 0x2c, 0x8a,
	0x9c, 0xf7, 0xe8, 0x24, 0x5a, 0xb3, 0x33, 0x08, 0x93, 0x5c, 0x64, 0x89, 0x16, 0x45, 0xce, 0xfb,
	0x64, 0xec, 0x0b, 0xd1, 0x8f, 0x23, 0x08, 0xdf, 0x14, 0x55, 0xae, 0x89, 0x6b, 0xda, 0xe2, 0x1a,
	0xd5, 0x5c, 0x8d, 0x6f, 0x57, 0x7b, 0xc4, 0xd1, 0x57, 0xf7, 0x34, 0x31, 0x72, 0x38, 0xce, 0x48,
	0x38, 0x48, 0x27, 0xcd, 0x1d, 0x68, 0xe9, 0x61, 0xee, 0x0b, 0x86, 0x33, 0xad, 0x76, 0xd7, 0x84,
	0x53, 0x73, 0x3a, 0xcd, 0x22, 0xb8, 0x23, 0x31, 0xc7, 0xcf, 0xc9, 0xe6, 0xda, 0xc3, 0x6d, 0xd5,
	0xfe, 0x9e, 0xda, 0xa4, 0x21, 0xd4, 0xcb, 0x64, 0x8b, 0xfc, 0xd8, 0xa6, 0x61, 0x15, 0x1b, 0xc3,
	0x10, 0xbf, 0x94, 0x42, 0xe2, 0xf2, 0x9d, 0xc8, 0x90, 0x0f, 0xc8, 0xf4, 0x4b, 0xa6, 0xef, 0x42,
	0xcd, 0x15, 0xf2, 0xd0, 0xf6, 0x9d, 0x44, 0x34, 0x05, 0x76, 0x59, 0xed, 0x62, 0x7b, 0xa9, 0xba,
	0x5d, 0x37, 0xb7, 0xf7, 0x23, 0x7a, 0x04, 0xc3, 0x39, 0xaa, 0x03, 0x36, 0x3e, 0x87, 0xbb, 0xaf,
	0x85, 0xd2, 0xef, 0x45, 0x2a, 0x13, 0x5d, 0x48, 0x0a, 0xe9, 0x49, 0x2b, 0xa4, 0x07, 0x75, 0x48,
	0xfe, 0x36, 0x6f, 0x08, 0x7f, 0x06, 0xed, 0x13, 0x28, 0xa8, 0x73, 0x80, 0xad, 0xd3, 0xee, 0x95,
	0x5e, 0xc5, 0x34, 0xdd, 0x29, 0x2f, 0xb1, 0x56, 0xed, 0x7f, 0x0c, 0xa7, 0x79, 0xc7, 0xb2, 0x92,
	0xd6, 0xb4, 0x41, 0x35, 0xda, 0x78, 0x4a, 0x4b, 0xcc, 0xd7, 0xfa, 0x63, 0x9d, 0x53, 0xa3, 0xa3,
	0xef, 0x01, 0x9c, 0x50, 0x73, 0x0d, 0x39, 0xf5, 0xec, 0xa2, 0xd5, 0xb3, 0x73, 0x7f, 0xb0, 0xdd,
	0x9e, 0x3f, 0x86, 0xbb, 0xfa, 0x17, 0xb3, 0xed, 0xa0, 0x3b, 0xb7, 0x41, 0x77, 0x7f, 0xff, 0x47,
	0x3e, 0x86, 0x93, 0x79, 0x7e, 0xd0, 0x74, 0x5c, 0x9e, 0x7d, 0x18, 0xdd, 0x54, 0x58, 0xe1, 0xab,
	0x22, 0x9d, 0x95, 0x9f, 0xd6, 0x33, 0xa2, 0x4a, 0xab, 0xd5, 0xcc, 0x7c, 0xc3, 0xd2, 0x3e, 0xc9,
	0x67, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0x3e, 0x72, 0x3d, 0xd2, 0x04, 0x00, 0x00,
}
