// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live/rank.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 主播排行榜请求
type AnchorRankReq struct {
	Cycle                int32    `protobuf:"varint,1,opt,name=cycle,proto3" json:"cycle"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnchorRankReq) Reset()         { *m = AnchorRankReq{} }
func (m *AnchorRankReq) String() string { return proto.CompactTextString(m) }
func (*AnchorRankReq) ProtoMessage()    {}
func (*AnchorRankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{0}
}

func (m *AnchorRankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorRankReq.Unmarshal(m, b)
}
func (m *AnchorRankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorRankReq.Marshal(b, m, deterministic)
}
func (m *AnchorRankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorRankReq.Merge(m, src)
}
func (m *AnchorRankReq) XXX_Size() int {
	return xxx_messageInfo_AnchorRankReq.Size(m)
}
func (m *AnchorRankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorRankReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorRankReq proto.InternalMessageInfo

func (m *AnchorRankReq) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

// 主播排行榜响应
type AnchorRankResp struct {
	List                 []*AnchorRankResp_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AnchorRankResp) Reset()         { *m = AnchorRankResp{} }
func (m *AnchorRankResp) String() string { return proto.CompactTextString(m) }
func (*AnchorRankResp) ProtoMessage()    {}
func (*AnchorRankResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{1}
}

func (m *AnchorRankResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorRankResp.Unmarshal(m, b)
}
func (m *AnchorRankResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorRankResp.Marshal(b, m, deterministic)
}
func (m *AnchorRankResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorRankResp.Merge(m, src)
}
func (m *AnchorRankResp) XXX_Size() int {
	return xxx_messageInfo_AnchorRankResp.Size(m)
}
func (m *AnchorRankResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorRankResp.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorRankResp proto.InternalMessageInfo

func (m *AnchorRankResp) GetList() []*AnchorRankResp_Item {
	if m != nil {
		return m.List
	}
	return nil
}

type AnchorRankResp_Item struct {
	AnchorId             int32    `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	RoomId               int32    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	Fans                 int32    `protobuf:"varint,5,opt,name=fans,proto3" json:"fans"`
	Income               string   `protobuf:"bytes,6,opt,name=income,proto3" json:"income"`
	IsFollow             int32    `protobuf:"varint,7,opt,name=isFollow,proto3" json:"isFollow"`
	AnchorLevelId        int32    `protobuf:"varint,8,opt,name=anchorLevelId,proto3" json:"anchorLevelId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnchorRankResp_Item) Reset()         { *m = AnchorRankResp_Item{} }
func (m *AnchorRankResp_Item) String() string { return proto.CompactTextString(m) }
func (*AnchorRankResp_Item) ProtoMessage()    {}
func (*AnchorRankResp_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{1, 0}
}

func (m *AnchorRankResp_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorRankResp_Item.Unmarshal(m, b)
}
func (m *AnchorRankResp_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorRankResp_Item.Marshal(b, m, deterministic)
}
func (m *AnchorRankResp_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorRankResp_Item.Merge(m, src)
}
func (m *AnchorRankResp_Item) XXX_Size() int {
	return xxx_messageInfo_AnchorRankResp_Item.Size(m)
}
func (m *AnchorRankResp_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorRankResp_Item.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorRankResp_Item proto.InternalMessageInfo

func (m *AnchorRankResp_Item) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *AnchorRankResp_Item) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AnchorRankResp_Item) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *AnchorRankResp_Item) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AnchorRankResp_Item) GetFans() int32 {
	if m != nil {
		return m.Fans
	}
	return 0
}

func (m *AnchorRankResp_Item) GetIncome() string {
	if m != nil {
		return m.Income
	}
	return ""
}

func (m *AnchorRankResp_Item) GetIsFollow() int32 {
	if m != nil {
		return m.IsFollow
	}
	return 0
}

func (m *AnchorRankResp_Item) GetAnchorLevelId() int32 {
	if m != nil {
		return m.AnchorLevelId
	}
	return 0
}

// 用户排行榜请求
type UserRankReq struct {
	Cycle                int32    `protobuf:"varint,1,opt,name=cycle,proto3" json:"cycle"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRankReq) Reset()         { *m = UserRankReq{} }
func (m *UserRankReq) String() string { return proto.CompactTextString(m) }
func (*UserRankReq) ProtoMessage()    {}
func (*UserRankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{2}
}

func (m *UserRankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRankReq.Unmarshal(m, b)
}
func (m *UserRankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRankReq.Marshal(b, m, deterministic)
}
func (m *UserRankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRankReq.Merge(m, src)
}
func (m *UserRankReq) XXX_Size() int {
	return xxx_messageInfo_UserRankReq.Size(m)
}
func (m *UserRankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRankReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRankReq proto.InternalMessageInfo

func (m *UserRankReq) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

func (m *UserRankReq) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 用户排行榜响应
type UserRankResp struct {
	List                 []*UserRankResp_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserRankResp) Reset()         { *m = UserRankResp{} }
func (m *UserRankResp) String() string { return proto.CompactTextString(m) }
func (*UserRankResp) ProtoMessage()    {}
func (*UserRankResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{3}
}

func (m *UserRankResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRankResp.Unmarshal(m, b)
}
func (m *UserRankResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRankResp.Marshal(b, m, deterministic)
}
func (m *UserRankResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRankResp.Merge(m, src)
}
func (m *UserRankResp) XXX_Size() int {
	return xxx_messageInfo_UserRankResp.Size(m)
}
func (m *UserRankResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRankResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserRankResp proto.InternalMessageInfo

func (m *UserRankResp) GetList() []*UserRankResp_Item {
	if m != nil {
		return m.List
	}
	return nil
}

type UserRankResp_Item struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	LevelId              int32    `protobuf:"varint,3,opt,name=levelId,proto3" json:"levelId"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	Contribute           string   `protobuf:"bytes,5,opt,name=contribute,proto3" json:"contribute"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRankResp_Item) Reset()         { *m = UserRankResp_Item{} }
func (m *UserRankResp_Item) String() string { return proto.CompactTextString(m) }
func (*UserRankResp_Item) ProtoMessage()    {}
func (*UserRankResp_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a14768c7e3e6d65, []int{3, 0}
}

func (m *UserRankResp_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRankResp_Item.Unmarshal(m, b)
}
func (m *UserRankResp_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRankResp_Item.Marshal(b, m, deterministic)
}
func (m *UserRankResp_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRankResp_Item.Merge(m, src)
}
func (m *UserRankResp_Item) XXX_Size() int {
	return xxx_messageInfo_UserRankResp_Item.Size(m)
}
func (m *UserRankResp_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRankResp_Item.DiscardUnknown(m)
}

var xxx_messageInfo_UserRankResp_Item proto.InternalMessageInfo

func (m *UserRankResp_Item) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRankResp_Item) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserRankResp_Item) GetLevelId() int32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *UserRankResp_Item) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserRankResp_Item) GetContribute() string {
	if m != nil {
		return m.Contribute
	}
	return ""
}

func init() {
	proto.RegisterType((*AnchorRankReq)(nil), "proto.AnchorRankReq")
	proto.RegisterType((*AnchorRankResp)(nil), "proto.AnchorRankResp")
	proto.RegisterType((*AnchorRankResp_Item)(nil), "proto.AnchorRankResp.Item")
	proto.RegisterType((*UserRankReq)(nil), "proto.UserRankReq")
	proto.RegisterType((*UserRankResp)(nil), "proto.UserRankResp")
	proto.RegisterType((*UserRankResp_Item)(nil), "proto.UserRankResp.Item")
}

func init() {
	proto.RegisterFile("live/rank.proto", fileDescriptor_6a14768c7e3e6d65)
}

var fileDescriptor_6a14768c7e3e6d65 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6a, 0xab, 0x40,
	0x14, 0x86, 0x31, 0x51, 0x93, 0x9c, 0xdc, 0xdc, 0x0b, 0xc3, 0x25, 0x0c, 0x72, 0xb9, 0x04, 0x69,
	0x21, 0x8b, 0xa2, 0xd0, 0x2e, 0xbb, 0x6a, 0x17, 0x05, 0x4b, 0x57, 0x42, 0x37, 0xdd, 0x8d, 0xe6,
	0xa4, 0x15, 0xc7, 0x19, 0xe3, 0x68, 0x4a, 0xdf, 0xa1, 0xef, 0xd0, 0x07, 0xea, 0x2b, 0xf4, 0x61,
	0x8a, 0x33, 0x26, 0x31, 0x8b, 0x66, 0xa5, 0xdf, 0xf1, 0x3f, 0xce, 0x39, 0x1f, 0x03, 0x7f, 0x78,
	0xb6, 0xc5, 0xb0, 0x62, 0x22, 0x0f, 0xca, 0x4a, 0xd6, 0x92, 0x38, 0xfa, 0xe1, 0x9f, 0xc3, 0xec,
	0x46, 0xa4, 0x2f, 0xb2, 0x8a, 0x99, 0xc8, 0x63, 0xdc, 0x90, 0xbf, 0xe0, 0xa4, 0x6f, 0x29, 0x47,
	0x6a, 0x2d, 0xac, 0xa5, 0x13, 0x1b, 0xf0, 0x3f, 0x06, 0xf0, 0xbb, 0x9f, 0x53, 0x25, 0x09, 0xc0,
	0xe6, 0x99, 0xaa, 0xa9, 0xb5, 0x18, 0x2e, 0xa7, 0x97, 0x9e, 0xf9, 0x6d, 0x70, 0x1c, 0x0a, 0xa2,
	0x1a, 0x8b, 0x58, 0xe7, 0xbc, 0x2f, 0x0b, 0xec, 0x16, 0x89, 0x07, 0x63, 0xa6, 0x53, 0xd1, 0xaa,
	0x3b, 0x64, 0xcf, 0xed, 0x37, 0x91, 0xa5, 0xb9, 0x60, 0x05, 0xd2, 0xc1, 0xc2, 0x5a, 0x4e, 0xe2,
	0x3d, 0x93, 0x39, 0xb8, 0x95, 0x94, 0x45, 0xb4, 0xa2, 0x43, 0xdd, 0xd5, 0x51, 0x5b, 0x67, 0x5b,
	0x56, 0xb3, 0x8a, 0xda, 0xba, 0xa3, 0x23, 0x42, 0xc0, 0x5e, 0x33, 0xa1, 0xa8, 0xa3, 0xd3, 0xfa,
	0xbd, 0xcd, 0x66, 0x22, 0x95, 0x05, 0x52, 0xd7, 0x64, 0x0d, 0xb5, 0xe7, 0x66, 0xea, 0x4e, 0x72,
	0x2e, 0x5f, 0xe9, 0xc8, 0xcc, 0xb4, 0x63, 0x72, 0x06, 0x33, 0x33, 0xdf, 0x03, 0x6e, 0x91, 0x47,
	0x2b, 0x3a, 0xd6, 0x81, 0xe3, 0xa2, 0x7f, 0x0d, 0xd3, 0x47, 0x85, 0xa7, 0x35, 0xf6, 0x56, 0x18,
	0xf4, 0x57, 0xf0, 0x3f, 0x2d, 0xf8, 0x75, 0xe8, 0x56, 0x25, 0xb9, 0x38, 0x92, 0x4b, 0x3b, 0xb9,
	0xfd, 0x48, 0x5f, 0xed, 0xfb, 0x4e, 0xed, 0x1c, 0xdc, 0x46, 0xe1, 0x41, 0x6c, 0x47, 0x27, 0xb5,
	0x52, 0x18, 0xf1, 0x6e, 0x31, 0xe3, 0x75, 0x87, 0x3f, 0x8a, 0xfd, 0x0f, 0x90, 0x4a, 0x51, 0x57,
	0x59, 0xd2, 0xd4, 0xa8, 0xf5, 0x4e, 0xe2, 0x5e, 0xe5, 0xf6, 0xdf, 0x93, 0xb7, 0x69, 0xb0, 0xc1,
	0x7b, 0x99, 0x84, 0x65, 0xfe, 0x1c, 0xea, 0xe1, 0x93, 0x66, 0x1d, 0xb6, 0x77, 0x30, 0x71, 0x35,
	0x5e, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x30, 0x2e, 0x56, 0xb0, 0x92, 0x02, 0x00, 0x00,
}
