// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: live/rank.proto

package live

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 主播排行榜请求
type AnchorRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cycle int32 `protobuf:"varint,1,opt,name=cycle,proto3" json:"cycle,omitempty"` // 周期 1-日 2-周 3-月 4-昨天 5-上周 6-上月
}

func (x *AnchorRankReq) Reset() {
	*x = AnchorRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRankReq) ProtoMessage() {}

func (x *AnchorRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRankReq.ProtoReflect.Descriptor instead.
func (*AnchorRankReq) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorRankReq) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

// 主播排行榜响应
type AnchorRankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AnchorRankResp_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AnchorRankResp) Reset() {
	*x = AnchorRankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRankResp) ProtoMessage() {}

func (x *AnchorRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRankResp.ProtoReflect.Descriptor instead.
func (*AnchorRankResp) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{1}
}

func (x *AnchorRankResp) GetList() []*AnchorRankResp_Item {
	if x != nil {
		return x.List
	}
	return nil
}

// 用户排行榜请求
type UserRankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cycle  int32 `protobuf:"varint,1,opt,name=cycle,proto3" json:"cycle,omitempty"`   // 周期 1-日 2-周 3-月 4-总榜
	RoomId int32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"` // 直播间id
}

func (x *UserRankReq) Reset() {
	*x = UserRankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRankReq) ProtoMessage() {}

func (x *UserRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRankReq.ProtoReflect.Descriptor instead.
func (*UserRankReq) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{2}
}

func (x *UserRankReq) GetCycle() int32 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *UserRankReq) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 用户排行榜响应
type UserRankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*UserRankResp_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserRankResp) Reset() {
	*x = UserRankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRankResp) ProtoMessage() {}

func (x *UserRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRankResp.ProtoReflect.Descriptor instead.
func (*UserRankResp) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{3}
}

func (x *UserRankResp) GetList() []*UserRankResp_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type AnchorRankResp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnchorId      int32  `protobuf:"varint,1,opt,name=anchorId,proto3" json:"anchorId,omitempty"`           // 主播id
	Nickname      string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`            // 昵称
	RoomId        int32  `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`               // 直播间id
	Avatar        string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                // 头像
	Fans          int32  `protobuf:"varint,5,opt,name=fans,proto3" json:"fans,omitempty"`                   // 粉丝数量
	Income        string `protobuf:"bytes,6,opt,name=income,proto3" json:"income,omitempty"`                // 累计收益
	IsFollow      int32  `protobuf:"varint,7,opt,name=isFollow,proto3" json:"isFollow,omitempty"`           // 是否关注
	AnchorLevelId int32  `protobuf:"varint,8,opt,name=anchorLevelId,proto3" json:"anchorLevelId,omitempty"` // 主播直播间等级
}

func (x *AnchorRankResp_Item) Reset() {
	*x = AnchorRankResp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorRankResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRankResp_Item) ProtoMessage() {}

func (x *AnchorRankResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRankResp_Item.ProtoReflect.Descriptor instead.
func (*AnchorRankResp_Item) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AnchorRankResp_Item) GetAnchorId() int32 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *AnchorRankResp_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AnchorRankResp_Item) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AnchorRankResp_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AnchorRankResp_Item) GetFans() int32 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *AnchorRankResp_Item) GetIncome() string {
	if x != nil {
		return x.Income
	}
	return ""
}

func (x *AnchorRankResp_Item) GetIsFollow() int32 {
	if x != nil {
		return x.IsFollow
	}
	return 0
}

func (x *AnchorRankResp_Item) GetAnchorLevelId() int32 {
	if x != nil {
		return x.AnchorLevelId
	}
	return 0
}

type UserRankResp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`        // 用户id
	Nickname   string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`     // 昵称
	LevelId    int32  `protobuf:"varint,3,opt,name=levelId,proto3" json:"levelId,omitempty"`      // 等级id
	Avatar     string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`         // 头像
	Contribute string `protobuf:"bytes,5,opt,name=contribute,proto3" json:"contribute,omitempty"` // 贡献值
}

func (x *UserRankResp_Item) Reset() {
	*x = UserRankResp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_rank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRankResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRankResp_Item) ProtoMessage() {}

func (x *UserRankResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_live_rank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRankResp_Item.ProtoReflect.Descriptor instead.
func (*UserRankResp_Item) Descriptor() ([]byte, []int) {
	return file_live_rank_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UserRankResp_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRankResp_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserRankResp_Item) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *UserRankResp_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserRankResp_Item) GetContribute() string {
	if x != nil {
		return x.Contribute
	}
	return ""
}

var File_live_rank_proto protoreflect.FileDescriptor

var file_live_rank_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x41, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x22,
	0x9f, 0x02, 0x0a, 0x0e, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52,
	0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x1a, 0xdc, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x0d, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0x3b, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0xcb,
	0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x8c, 0x01,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x42, 0x1b, 0x5a, 0x19,
	0x6c, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_live_rank_proto_rawDescOnce sync.Once
	file_live_rank_proto_rawDescData = file_live_rank_proto_rawDesc
)

func file_live_rank_proto_rawDescGZIP() []byte {
	file_live_rank_proto_rawDescOnce.Do(func() {
		file_live_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_rank_proto_rawDescData)
	})
	return file_live_rank_proto_rawDescData
}

var file_live_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_live_rank_proto_goTypes = []any{
	(*AnchorRankReq)(nil),       // 0: proto.AnchorRankReq
	(*AnchorRankResp)(nil),      // 1: proto.AnchorRankResp
	(*UserRankReq)(nil),         // 2: proto.UserRankReq
	(*UserRankResp)(nil),        // 3: proto.UserRankResp
	(*AnchorRankResp_Item)(nil), // 4: proto.AnchorRankResp.Item
	(*UserRankResp_Item)(nil),   // 5: proto.UserRankResp.Item
}
var file_live_rank_proto_depIdxs = []int32{
	4, // 0: proto.AnchorRankResp.list:type_name -> proto.AnchorRankResp.Item
	5, // 1: proto.UserRankResp.list:type_name -> proto.UserRankResp.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_live_rank_proto_init() }
func file_live_rank_proto_init() {
	if File_live_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_rank_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AnchorRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_rank_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AnchorRankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_rank_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserRankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_rank_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UserRankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_rank_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AnchorRankResp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_rank_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UserRankResp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_rank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_rank_proto_goTypes,
		DependencyIndexes: file_live_rank_proto_depIdxs,
		MessageInfos:      file_live_rank_proto_msgTypes,
	}.Build()
	File_live_rank_proto = out.File
	file_live_rank_proto_rawDesc = nil
	file_live_rank_proto_goTypes = nil
	file_live_rank_proto_depIdxs = nil
}
