[success]
other = "完成"
[user_or_pass_err]
other = "用户或密码错误"
[register_err]
other = "注册失败，请重试"
[gen_token_err]
other = "用户信息生成错误"
[para_err]
other = "无效请求"
[invalid_request]
other = "参数不合法"
[user_not_exist]
other = "用户不存在"
[user_add_detail_err]
other = "添加用户详情失败"
[unique_idcard]
other = "身份证已注册"
[re_login]
other = "网络波动，请重新登录"
[one_time_pass_code_err]
other = "一次性验证码错误"
[create_user_err]
other = "创建用户失败"
[unique_user]
other = "用户已存在"
[unique_email]
other = "邮箱已注册账号"
[same_password]
other = "新密码不能与旧密码相同"
[update_err]
other = "更新失败"
[not_allow_update]
other = "数据不允许修改"
[db_err]
other = "数据异常"
[no_opuser_id]
other = "no opUserID"
[opuser_id_empty]
other = "opUserID empty"
[missing_user_type]
other = "missing user type"
[user_type_empty]
other = "user type empty"
[user_type_invalid]
other = "user type invalid"
[empty_phone_number]
other = "请输入手机号码"
[empty_password]
other = "请输入密码"
[empty_validation]
other = "请输入验证码"
[invalid_password_length]
other = "限制字数为6个数字或字母或数字与字母"
[invalid_validation_length]
other = "验证码限制字数为6位数字"
[login_type_error]
other = "登陆方式错误"
[two_password_no_match]
other = "两次密码输入不一致"
[password_error]
other = "密码不能为空"
[username_or_password_error]
other = "用户名或密码错误"
[internal_error]
other = "服务器错误"
[msg_type_error]
other = "短消息类型错误"
[empty_country_code_error]
other = "国家代码不能为空"
[modify_password_fail]
other = "修改密码失败"
[not_found_msg_template]
other = "无法找到对应的短信模板"
[msg_send_fail]
other = "短信发送失败"
[max_send_times_of_24_hours]
other = "验证码请求次数超限"
[cool_down_error]
other = "冷静期间内不允许再次请求验证码"
[global_areas_fail]
other = "无法获取地区列表"
[modify_profile_fail]
other = "修改用户信息失败"
[query_profile_fail]
other = "无法获取用户信息"
[token_create_fail]
other = "用户标识创建失败"
[token_match_fail]
other = "Token错误"
[empty_country_code]
other = "手机国家代码不能为空"
[user_disabled]
other = "你已被禁止登陆，请联系客服"


[no_token]
other = "您还未登录，请登录后重试"
[token_not_exists]
other = "用户令牌已过期或不存在"
[token_generate_failed]
other = "token生成失败"
[404]
other = "页面未找到"
[proto_error]
other = "参数错误"

[copy_error]
other = "内部复制错误"

[query_failed]
other = "查询失败"

[reward_user_apply_reject]
other = "用户申请活动失败"
[reward_create_user_status_failed]
other = "创建失败"
[reward_update_quantity_failed]
other = "更新活动剩余数量失败"
[reward_not_in_progress]
other = "活动当前没有开放"

[reset_email_title]
other = "重置密码邮件"
[reset_email_check_error]
other = "邮件与账号不匹配"
[reset_email_body]
other = "您的验证码是：{{.v1}}"
[reset_email_send_success]
other = "发送重置邮件成功"
[reset_email_send_error]
other = "发送邮件失败"
[reset_pass_err]
other = "重置密码错误"

[charge_error]
other = "充值失败"
[charge_log_error]
other = "充值发生异常"
[insufficient_balance]
other = "余额不足"
[transfer_error]
other = "转账失败"

[upload_error]
other = "上传失败"

[wallet_init_err]
other = "钱包未初始化"
[kyc_init_err]
other = "KYC信息初始化失败"

[game_login_error]
other = "获取游戏登录链接失败"
[game_charge_error]
other = "用户钱包充入游戏失败"
[game_balance_error]
other = "查询用户游戏余额失败"
[game_balance_less_than_zero]
other = "用户游戏余额小于1"
[game_balance_out_error]
other = "将用户游戏余额提回至平台主钱包失败"
[game_transfer_log_error]
other = "游戏场馆转帐记录失败"
[unknown_responsibility]
other = "未知的责任限制ID"
[not_vip]
other = "不是会员"
[copy_err]
other = "转换信息错误"
[default_vip_unallocated]
other = "默认VIP未配置"


[interim_prohibit]
other = "临时门禁已开启"
[permanent_prohibit]
other = "永久门禁"
[dispassionate]
other = "冷静功能"
[deposit_limit]
other = "总存款限制"
[error_amount]
other = "错误的金额"

[clear_token_error]
other = "退出登录失败"

[set_captcha_error]
other = "生成验证码错误"
[set_captcha_cache_error]
other = "缓冲验证码错误"
[get_captcha_code_error]
other = "获取缓冲码失败"
[invalid_captcha_data]
other = "验证码错误"
[invalid_captcha_int_data]
other = "验证码生成错误"
[invalid_code]
other = "验证码错误"
[bind_mobile_send_error]
other = "绑定验证码发送错误"
[bind_email_title]
other = "您正在绑定邮件"
[bind_email_body]
other = "您的验证码是：{{.v1}}"
[bind_mobile_risk]
other = "号码存在风险"

[bind_email_send_error]
other = "发送验证码失败"
[bind_email_send_success]
other = "发送验证码成功"

[one_time_pass_expire]
other = "验证码已过期"


[error_game_group]
other = "错误的游戏分组"


[not_match_game]
other = "未配置游戏"
[not_match_game_venue]
other = "未配置游戏场馆"
[extra_info_error]
other = "未配置扩展配置"
[game_login_fail]
other = "游戏登录错误"
[game_login_url_parse_fail]
other = "游戏登录链接错误"
[old_password_error]
other = "旧密码错误"
[withdrawal_password_is_set_up]
other = "已设置提现密码"
[game_reg_fail]
other = "注册游戏账号失败"

[user_is_ban]
other = "该用户已禁用,请联系客服!"
[same_withdrawal_password]
other = "不能与支付密码一致"
[same_login_password]
other = "不能与登录密码一致"
[wrong_captcha]
other = "错误的验证码"

[login_highly_operator]
other = "登录频繁，请于3秒后重试"
[limit_cache_error]
other = "登录频繁，请稍后再试"
[limit_login]
other = "密码错误次数过多，请30分钟后重试"
[register_err2]
other = "三方游戏注册失败"
[balance_transfer_ok]
other = "余额转回成功"

[empty_games]
other = "暂无游戏资料"
[empty_games_account]
other = "暂未建立任意的场馆账号"
[user_ban]
other = "用户被冻结"
[tx_notice]
other = "已在其他地方登陆"
[email_exits]
other = "邮箱已被使用"
[phone_exits]
other = "号码已被使用"

[route_timeout]
other = "请求超时"
[login_failed]
other = "登陆失败"

