// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance/change.proto

package finance

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentType int32

const (
	PaymentType_PT_Error           PaymentType = 0
	PaymentType_PT_Gift            PaymentType = 1
	PaymentType_PT_Barrage         PaymentType = 2
	PaymentType_PT_Game            PaymentType = 3
	PaymentType_PT_LiveCharge      PaymentType = 4
	PaymentType_PT_Item            PaymentType = 5
	PaymentType_PT_Mounts          PaymentType = 6
	PaymentType_PT_SubscribeMounts PaymentType = 7
	PaymentType_PT_Noble           PaymentType = 8
	PaymentType_PT_SubscribeNoble  PaymentType = 9
	PaymentType_PT_Guard           PaymentType = 10
	PaymentType_PT_SubscribeGuard  PaymentType = 11
	PaymentType_PT_Exchange        PaymentType = 100
	PaymentType_PT_UpDiamond       PaymentType = 111
	PaymentType_PT_DownDiamond     PaymentType = 112
)

var PaymentType_name = map[int32]string{
	0:   "PT_Error",
	1:   "PT_Gift",
	2:   "PT_Barrage",
	3:   "PT_Game",
	4:   "PT_LiveCharge",
	5:   "PT_Item",
	6:   "PT_Mounts",
	7:   "PT_SubscribeMounts",
	8:   "PT_Noble",
	9:   "PT_SubscribeNoble",
	10:  "PT_Guard",
	11:  "PT_SubscribeGuard",
	100: "PT_Exchange",
	111: "PT_UpDiamond",
	112: "PT_DownDiamond",
}

var PaymentType_value = map[string]int32{
	"PT_Error":           0,
	"PT_Gift":            1,
	"PT_Barrage":         2,
	"PT_Game":            3,
	"PT_LiveCharge":      4,
	"PT_Item":            5,
	"PT_Mounts":          6,
	"PT_SubscribeMounts": 7,
	"PT_Noble":           8,
	"PT_SubscribeNoble":  9,
	"PT_Guard":           10,
	"PT_SubscribeGuard":  11,
	"PT_Exchange":        100,
	"PT_UpDiamond":       111,
	"PT_DownDiamond":     112,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{0}
}

// 扣费扩展信息
type ExtInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	I18NJson             string   `protobuf:"bytes,5,opt,name=i18nJson,proto3" json:"i18nJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtInfo) Reset()         { *m = ExtInfo{} }
func (m *ExtInfo) String() string { return proto.CompactTextString(m) }
func (*ExtInfo) ProtoMessage()    {}
func (*ExtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{0}
}

func (m *ExtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtInfo.Unmarshal(m, b)
}
func (m *ExtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtInfo.Marshal(b, m, deterministic)
}
func (m *ExtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtInfo.Merge(m, src)
}
func (m *ExtInfo) XXX_Size() int {
	return xxx_messageInfo_ExtInfo.Size(m)
}
func (m *ExtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExtInfo proto.InternalMessageInfo

func (m *ExtInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExtInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtInfo) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ExtInfo) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ExtInfo) GetI18NJson() string {
	if m != nil {
		return m.I18NJson
	}
	return ""
}

// 扣费
type PayDiamondReq struct {
	UserId               int32       `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Diamond              int32       `protobuf:"varint,2,opt,name=diamond,proto3" json:"diamond,omitempty"`
	ChangeType           PaymentType `protobuf:"varint,3,opt,name=changeType,proto3,enum=proto.PaymentType" json:"changeType,omitempty"`
	RoomId               int32       `protobuf:"varint,4,opt,name=roomId,proto3" json:"roomId,omitempty"`
	StreamerId           int32       `protobuf:"varint,5,opt,name=streamerId,proto3" json:"streamerId,omitempty"`
	ExtInfo              *ExtInfo    `protobuf:"bytes,6,opt,name=extInfo,proto3" json:"extInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PayDiamondReq) Reset()         { *m = PayDiamondReq{} }
func (m *PayDiamondReq) String() string { return proto.CompactTextString(m) }
func (*PayDiamondReq) ProtoMessage()    {}
func (*PayDiamondReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{1}
}

func (m *PayDiamondReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayDiamondReq.Unmarshal(m, b)
}
func (m *PayDiamondReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayDiamondReq.Marshal(b, m, deterministic)
}
func (m *PayDiamondReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayDiamondReq.Merge(m, src)
}
func (m *PayDiamondReq) XXX_Size() int {
	return xxx_messageInfo_PayDiamondReq.Size(m)
}
func (m *PayDiamondReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayDiamondReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayDiamondReq proto.InternalMessageInfo

func (m *PayDiamondReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PayDiamondReq) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *PayDiamondReq) GetChangeType() PaymentType {
	if m != nil {
		return m.ChangeType
	}
	return PaymentType_PT_Error
}

func (m *PayDiamondReq) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *PayDiamondReq) GetStreamerId() int32 {
	if m != nil {
		return m.StreamerId
	}
	return 0
}

func (m *PayDiamondReq) GetExtInfo() *ExtInfo {
	if m != nil {
		return m.ExtInfo
	}
	return nil
}

// 扣费返回
type PayDiamondResp struct {
	Balance              int32    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayDiamondResp) Reset()         { *m = PayDiamondResp{} }
func (m *PayDiamondResp) String() string { return proto.CompactTextString(m) }
func (*PayDiamondResp) ProtoMessage()    {}
func (*PayDiamondResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{2}
}

func (m *PayDiamondResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayDiamondResp.Unmarshal(m, b)
}
func (m *PayDiamondResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayDiamondResp.Marshal(b, m, deterministic)
}
func (m *PayDiamondResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayDiamondResp.Merge(m, src)
}
func (m *PayDiamondResp) XXX_Size() int {
	return xxx_messageInfo_PayDiamondResp.Size(m)
}
func (m *PayDiamondResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayDiamondResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayDiamondResp proto.InternalMessageInfo

func (m *PayDiamondResp) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// 钻石操作
type DiamondReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Diamond              int32    `protobuf:"varint,2,opt,name=diamond,proto3" json:"diamond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondReq) Reset()         { *m = DiamondReq{} }
func (m *DiamondReq) String() string { return proto.CompactTextString(m) }
func (*DiamondReq) ProtoMessage()    {}
func (*DiamondReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{3}
}

func (m *DiamondReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondReq.Unmarshal(m, b)
}
func (m *DiamondReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondReq.Marshal(b, m, deterministic)
}
func (m *DiamondReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondReq.Merge(m, src)
}
func (m *DiamondReq) XXX_Size() int {
	return xxx_messageInfo_DiamondReq.Size(m)
}
func (m *DiamondReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondReq.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondReq proto.InternalMessageInfo

func (m *DiamondReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DiamondReq) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

// 钻石操作返回
type DiamondResp struct {
	Balance              int32    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondResp) Reset()         { *m = DiamondResp{} }
func (m *DiamondResp) String() string { return proto.CompactTextString(m) }
func (*DiamondResp) ProtoMessage()    {}
func (*DiamondResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ee4dee1fcd4a81, []int{4}
}

func (m *DiamondResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondResp.Unmarshal(m, b)
}
func (m *DiamondResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondResp.Marshal(b, m, deterministic)
}
func (m *DiamondResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondResp.Merge(m, src)
}
func (m *DiamondResp) XXX_Size() int {
	return xxx_messageInfo_DiamondResp.Size(m)
}
func (m *DiamondResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondResp.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondResp proto.InternalMessageInfo

func (m *DiamondResp) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterType((*ExtInfo)(nil), "proto.ExtInfo")
	proto.RegisterType((*PayDiamondReq)(nil), "proto.PayDiamondReq")
	proto.RegisterType((*PayDiamondResp)(nil), "proto.PayDiamondResp")
	proto.RegisterType((*DiamondReq)(nil), "proto.DiamondReq")
	proto.RegisterType((*DiamondResp)(nil), "proto.DiamondResp")
}

func init() {
	proto.RegisterFile("finance/change.proto", fileDescriptor_d6ee4dee1fcd4a81)
}

var fileDescriptor_d6ee4dee1fcd4a81 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x69, 0x9d, 0x8f, 0x71, 0x63, 0xb6, 0xa3, 0x52, 0x59, 0x48, 0x40, 0x94, 0x0b, 0x51,
	0x0f, 0x8d, 0x08, 0x17, 0x4e, 0x1c, 0x4a, 0xab, 0x2a, 0x15, 0xa0, 0x95, 0x31, 0x17, 0x2e, 0xd6,
	0x3a, 0x9e, 0xa4, 0x16, 0xf5, 0xae, 0xbb, 0xb6, 0x69, 0xf3, 0x23, 0xf8, 0x7d, 0xfc, 0x1d, 0xe4,
	0xf5, 0x1a, 0x59, 0x9c, 0x90, 0x38, 0x25, 0xef, 0xcd, 0xd3, 0xce, 0x7b, 0x6f, 0x64, 0x38, 0xd9,
	0x66, 0x52, 0xc8, 0x0d, 0x2d, 0x37, 0xb7, 0x42, 0xee, 0xe8, 0xbc, 0xd0, 0xaa, 0x52, 0xe8, 0x9a,
	0x9f, 0xf9, 0x03, 0x8c, 0xae, 0x1e, 0xab, 0xb5, 0xdc, 0x2a, 0xf4, 0x61, 0x90, 0xa5, 0x81, 0x33,
	0x73, 0x16, 0x6e, 0x38, 0xc8, 0x52, 0x44, 0x38, 0x94, 0x22, 0xa7, 0x60, 0x30, 0x73, 0x16, 0x93,
	0xd0, 0xfc, 0xc7, 0x53, 0x18, 0xca, 0x3a, 0x4f, 0x48, 0x07, 0x07, 0x46, 0x67, 0x11, 0x9e, 0x80,
	0x5b, 0xe8, 0x6c, 0x43, 0xc1, 0xa1, 0xa1, 0x5b, 0x80, 0xcf, 0x61, 0x9c, 0xbd, 0x79, 0x27, 0x6f,
	0x4a, 0x25, 0x03, 0xd7, 0xbc, 0xf2, 0x07, 0xcf, 0x7f, 0x39, 0x30, 0xe5, 0x62, 0x7f, 0x99, 0x89,
	0x5c, 0xc9, 0x34, 0xa4, 0xfb, 0xe6, 0xed, 0xba, 0x24, 0xbd, 0xee, 0x3c, 0x58, 0x84, 0x01, 0x8c,
	0xd2, 0x56, 0x65, 0xac, 0xb8, 0x61, 0x07, 0x71, 0x05, 0xd0, 0x66, 0x8a, 0xf6, 0x05, 0x19, 0x47,
	0xfe, 0x0a, 0xdb, 0x7c, 0xe7, 0x5c, 0xec, 0x73, 0x92, 0x55, 0x33, 0x09, 0x7b, 0xaa, 0x66, 0x8b,
	0x56, 0x2a, 0x5f, 0xa7, 0xd6, 0xaa, 0x45, 0xf8, 0x12, 0xa0, 0xac, 0x34, 0x89, 0xdc, 0x38, 0x70,
	0xcd, 0xac, 0xc7, 0xe0, 0x02, 0x46, 0xd4, 0x16, 0x15, 0x0c, 0x67, 0xce, 0xc2, 0x5b, 0xf9, 0x76,
	0x91, 0xad, 0x2f, 0xec, 0xc6, 0xf3, 0x33, 0xf0, 0xfb, 0xc1, 0xca, 0xa2, 0x49, 0x90, 0x88, 0xbb,
	0xe6, 0x06, 0x36, 0x5a, 0x07, 0xe7, 0xef, 0x01, 0xfe, 0xa7, 0x81, 0xf9, 0x6b, 0xf0, 0xfe, 0x69,
	0xd1, 0xd9, 0xcf, 0x01, 0x78, 0xbd, 0x4a, 0xf0, 0x08, 0xc6, 0x3c, 0x8a, 0xaf, 0xb4, 0x56, 0x9a,
	0x3d, 0x41, 0x0f, 0x46, 0x3c, 0x8a, 0xaf, 0xb3, 0x6d, 0xc5, 0x1c, 0xf4, 0x01, 0x78, 0x14, 0x5f,
	0x08, 0xad, 0xc5, 0x8e, 0xd8, 0xa0, 0x1b, 0x8a, 0x9c, 0xd8, 0x01, 0x1e, 0xc3, 0x94, 0x47, 0xf1,
	0xc7, 0xec, 0x07, 0x7d, 0xb8, 0x15, 0x7a, 0x47, 0xec, 0xd0, 0xce, 0xd7, 0x15, 0xe5, 0xcc, 0xc5,
	0x29, 0x4c, 0x78, 0x14, 0x7f, 0x52, 0xb5, 0xac, 0x4a, 0x36, 0xc4, 0x53, 0x40, 0x1e, 0xc5, 0x5f,
	0xea, 0xa4, 0xdc, 0xe8, 0x2c, 0x21, 0xcb, 0x8f, 0xec, 0xfa, 0xcf, 0x2a, 0xb9, 0x23, 0x36, 0xc6,
	0x67, 0x70, 0xdc, 0x57, 0xb5, 0xf4, 0xc4, 0x8a, 0xae, 0x6b, 0xa1, 0x53, 0x06, 0x7f, 0x8b, 0x5a,
	0xda, 0xc3, 0xa7, 0xe0, 0x35, 0x41, 0x1e, 0xdb, 0x13, 0xb3, 0x14, 0x19, 0x1c, 0xf1, 0x28, 0xfe,
	0x5a, 0xd8, 0x5e, 0x98, 0x42, 0x04, 0x9f, 0x47, 0xf1, 0xa5, 0x7a, 0x90, 0x1d, 0x57, 0x5c, 0xbc,
	0xfa, 0xf6, 0xe2, 0xbe, 0xa6, 0x9a, 0x6e, 0x54, 0xb2, 0x2c, 0xbe, 0xef, 0x96, 0xe6, 0x96, 0x49,
	0xbd, 0x5d, 0xda, 0x8f, 0x25, 0x19, 0x1a, 0xe6, 0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10,
	0x63, 0x3e, 0x32, 0x3e, 0x03, 0x00, 0x00,
}
