// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: finance/change.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentType int32

const (
	PaymentType_PT_Error           PaymentType = 0   // 错误类型
	PaymentType_PT_Gift            PaymentType = 1   // 礼物
	PaymentType_PT_Barrage         PaymentType = 2   // 弹幕
	PaymentType_PT_Game            PaymentType = 3   // 游戏
	PaymentType_PT_LiveCharge      PaymentType = 4   // 直播收费
	PaymentType_PT_Item            PaymentType = 5   // 道具
	PaymentType_PT_Mounts          PaymentType = 6   // 坐骑
	PaymentType_PT_SubscribeMounts PaymentType = 7   // 续订坐骑
	PaymentType_PT_Noble           PaymentType = 8   // 购买贵族
	PaymentType_PT_SubscribeNoble  PaymentType = 9   // 续订贵族
	PaymentType_PT_Guard           PaymentType = 10  // 购买守护
	PaymentType_PT_SubscribeGuard  PaymentType = 11  // 守护
	PaymentType_PT_Exchange        PaymentType = 100 // 美金兑换钻石
	PaymentType_PT_UpDiamond       PaymentType = 111 // 系统上分
	PaymentType_PT_DownDiamond     PaymentType = 112 // 系统下分
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0:   "PT_Error",
		1:   "PT_Gift",
		2:   "PT_Barrage",
		3:   "PT_Game",
		4:   "PT_LiveCharge",
		5:   "PT_Item",
		6:   "PT_Mounts",
		7:   "PT_SubscribeMounts",
		8:   "PT_Noble",
		9:   "PT_SubscribeNoble",
		10:  "PT_Guard",
		11:  "PT_SubscribeGuard",
		100: "PT_Exchange",
		111: "PT_UpDiamond",
		112: "PT_DownDiamond",
	}
	PaymentType_value = map[string]int32{
		"PT_Error":           0,
		"PT_Gift":            1,
		"PT_Barrage":         2,
		"PT_Game":            3,
		"PT_LiveCharge":      4,
		"PT_Item":            5,
		"PT_Mounts":          6,
		"PT_SubscribeMounts": 7,
		"PT_Noble":           8,
		"PT_SubscribeNoble":  9,
		"PT_Guard":           10,
		"PT_SubscribeGuard":  11,
		"PT_Exchange":        100,
		"PT_UpDiamond":       111,
		"PT_DownDiamond":     112,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_finance_change_proto_enumTypes[0].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_finance_change_proto_enumTypes[0]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{0}
}

// 扣费扩展信息
type ExtInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // id
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         // 名称
	Number   int32  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`    // 数量
	Price    int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`      // 单价
	I18NJson string `protobuf:"bytes,5,opt,name=i18nJson,proto3" json:"i18nJson,omitempty"` // 国际化配置 如：{"en":"kiss","zh":"飞吻"}
}

func (x *ExtInfo) Reset() {
	*x = ExtInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_change_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtInfo) ProtoMessage() {}

func (x *ExtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_change_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtInfo.ProtoReflect.Descriptor instead.
func (*ExtInfo) Descriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{0}
}

func (x *ExtInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExtInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtInfo) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ExtInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ExtInfo) GetI18NJson() string {
	if x != nil {
		return x.I18NJson
	}
	return ""
}

// 扣费
type PayDiamondReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32       `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                                // 用户id
	Diamond    int32       `protobuf:"varint,2,opt,name=diamond,proto3" json:"diamond,omitempty"`                              // 钻石数量
	ChangeType PaymentType `protobuf:"varint,3,opt,name=changeType,proto3,enum=proto.PaymentType" json:"changeType,omitempty"` // 扣费类型
	RoomId     int32       `protobuf:"varint,4,opt,name=roomId,proto3" json:"roomId,omitempty"`                                // 费用发生的直播间id
	StreamerId int32       `protobuf:"varint,5,opt,name=streamerId,proto3" json:"streamerId,omitempty"`                        // 主播id
	ExtInfo    *ExtInfo    `protobuf:"bytes,6,opt,name=extInfo,proto3" json:"extInfo,omitempty"`                               // 扩展信息
}

func (x *PayDiamondReq) Reset() {
	*x = PayDiamondReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_change_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayDiamondReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDiamondReq) ProtoMessage() {}

func (x *PayDiamondReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_change_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDiamondReq.ProtoReflect.Descriptor instead.
func (*PayDiamondReq) Descriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{1}
}

func (x *PayDiamondReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayDiamondReq) GetDiamond() int32 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *PayDiamondReq) GetChangeType() PaymentType {
	if x != nil {
		return x.ChangeType
	}
	return PaymentType_PT_Error
}

func (x *PayDiamondReq) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PayDiamondReq) GetStreamerId() int32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

func (x *PayDiamondReq) GetExtInfo() *ExtInfo {
	if x != nil {
		return x.ExtInfo
	}
	return nil
}

// 扣费返回
type PayDiamondResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance int32 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"` // 剩余钻石
}

func (x *PayDiamondResp) Reset() {
	*x = PayDiamondResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_change_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayDiamondResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayDiamondResp) ProtoMessage() {}

func (x *PayDiamondResp) ProtoReflect() protoreflect.Message {
	mi := &file_finance_change_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayDiamondResp.ProtoReflect.Descriptor instead.
func (*PayDiamondResp) Descriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{2}
}

func (x *PayDiamondResp) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 钻石操作
type DiamondReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`   // 用户id
	Diamond int32 `protobuf:"varint,2,opt,name=diamond,proto3" json:"diamond,omitempty"` // 钻石数量 (正数表示增加钻石, 负数表示减少钻石)
}

func (x *DiamondReq) Reset() {
	*x = DiamondReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_change_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiamondReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiamondReq) ProtoMessage() {}

func (x *DiamondReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_change_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiamondReq.ProtoReflect.Descriptor instead.
func (*DiamondReq) Descriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{3}
}

func (x *DiamondReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DiamondReq) GetDiamond() int32 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

// 钻石操作返回
type DiamondResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance int32 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"` // 剩余钻石
}

func (x *DiamondResp) Reset() {
	*x = DiamondResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_change_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiamondResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiamondResp) ProtoMessage() {}

func (x *DiamondResp) ProtoReflect() protoreflect.Message {
	mi := &file_finance_change_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiamondResp.ProtoReflect.Descriptor instead.
func (*DiamondResp) Descriptor() ([]byte, []int) {
	return file_finance_change_proto_rawDescGZIP(), []int{4}
}

func (x *DiamondResp) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_finance_change_proto protoreflect.FileDescriptor

var file_finance_change_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a,
	0x07, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x31,
	0x38, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x31,
	0x38, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x44, 0x69,
	0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x2a, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x3e, 0x0a, 0x0a,
	0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x22, 0x27, 0x0a, 0x0b,
	0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2a, 0x8d, 0x02, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x54, 0x5f, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x54, 0x5f, 0x47, 0x69, 0x66, 0x74, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x54, 0x5f, 0x42, 0x61, 0x72, 0x72, 0x61, 0x67, 0x65, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x54, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x03, 0x12, 0x11, 0x0a,
	0x0d, 0x50, 0x54, 0x5f, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x54, 0x5f, 0x49, 0x74, 0x65, 0x6d, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x50, 0x54, 0x5f, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12,
	0x50, 0x54, 0x5f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x54, 0x5f, 0x4e, 0x6f, 0x62, 0x6c, 0x65,
	0x10, 0x08, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x54, 0x5f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x4e, 0x6f, 0x62, 0x6c, 0x65, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x54, 0x5f,
	0x47, 0x75, 0x61, 0x72, 0x64, 0x10, 0x0a, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x54, 0x5f, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x10, 0x0b, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x54, 0x5f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x64, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x54, 0x5f, 0x55, 0x70, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x10,
	0x6f, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x54, 0x5f, 0x44, 0x6f, 0x77, 0x6e, 0x44, 0x69, 0x61, 0x6d,
	0x6f, 0x6e, 0x64, 0x10, 0x70, 0x42, 0x1e, 0x5a, 0x1c, 0x6c, 0x69, 0x76, 0x65, 0x4a, 0x6f, 0x62,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finance_change_proto_rawDescOnce sync.Once
	file_finance_change_proto_rawDescData = file_finance_change_proto_rawDesc
)

func file_finance_change_proto_rawDescGZIP() []byte {
	file_finance_change_proto_rawDescOnce.Do(func() {
		file_finance_change_proto_rawDescData = protoimpl.X.CompressGZIP(file_finance_change_proto_rawDescData)
	})
	return file_finance_change_proto_rawDescData
}

var file_finance_change_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_finance_change_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_finance_change_proto_goTypes = []any{
	(PaymentType)(0),       // 0: proto.PaymentType
	(*ExtInfo)(nil),        // 1: proto.ExtInfo
	(*PayDiamondReq)(nil),  // 2: proto.PayDiamondReq
	(*PayDiamondResp)(nil), // 3: proto.PayDiamondResp
	(*DiamondReq)(nil),     // 4: proto.DiamondReq
	(*DiamondResp)(nil),    // 5: proto.DiamondResp
}
var file_finance_change_proto_depIdxs = []int32{
	0, // 0: proto.PayDiamondReq.changeType:type_name -> proto.PaymentType
	1, // 1: proto.PayDiamondReq.extInfo:type_name -> proto.ExtInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finance_change_proto_init() }
func file_finance_change_proto_init() {
	if File_finance_change_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finance_change_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExtInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_change_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PayDiamondReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_change_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PayDiamondResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_change_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DiamondReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_change_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DiamondResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finance_change_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_finance_change_proto_goTypes,
		DependencyIndexes: file_finance_change_proto_depIdxs,
		EnumInfos:         file_finance_change_proto_enumTypes,
		MessageInfos:      file_finance_change_proto_msgTypes,
	}.Build()
	File_finance_change_proto = out.File
	file_finance_change_proto_rawDesc = nil
	file_finance_change_proto_goTypes = nil
	file_finance_change_proto_depIdxs = nil
}
