// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance/finance.proto

package finance

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 代收
type PayInReq struct {
	Company              string   `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Money                string   `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
	RandomCode           string   `protobuf:"bytes,3,opt,name=randomCode,proto3" json:"randomCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInReq) Reset()         { *m = PayInReq{} }
func (m *PayInReq) String() string { return proto.CompactTextString(m) }
func (*PayInReq) ProtoMessage()    {}
func (*PayInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{0}
}

func (m *PayInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInReq.Unmarshal(m, b)
}
func (m *PayInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInReq.Marshal(b, m, deterministic)
}
func (m *PayInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInReq.Merge(m, src)
}
func (m *PayInReq) XXX_Size() int {
	return xxx_messageInfo_PayInReq.Size(m)
}
func (m *PayInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayInReq proto.InternalMessageInfo

func (m *PayInReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *PayInReq) GetMoney() string {
	if m != nil {
		return m.Money
	}
	return ""
}

func (m *PayInReq) GetRandomCode() string {
	if m != nil {
		return m.RandomCode
	}
	return ""
}

type PayInResp struct {
	PayCode              string   `protobuf:"bytes,1,opt,name=payCode,proto3" json:"payCode,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	QrCode               string   `protobuf:"bytes,3,opt,name=qrCode,proto3" json:"qrCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInResp) Reset()         { *m = PayInResp{} }
func (m *PayInResp) String() string { return proto.CompactTextString(m) }
func (*PayInResp) ProtoMessage()    {}
func (*PayInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{1}
}

func (m *PayInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInResp.Unmarshal(m, b)
}
func (m *PayInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInResp.Marshal(b, m, deterministic)
}
func (m *PayInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInResp.Merge(m, src)
}
func (m *PayInResp) XXX_Size() int {
	return xxx_messageInfo_PayInResp.Size(m)
}
func (m *PayInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayInResp proto.InternalMessageInfo

func (m *PayInResp) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

func (m *PayInResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PayInResp) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

// 代收订单查询
type PayInQueryReq struct {
	Company              string   `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Order                string   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInQueryReq) Reset()         { *m = PayInQueryReq{} }
func (m *PayInQueryReq) String() string { return proto.CompactTextString(m) }
func (*PayInQueryReq) ProtoMessage()    {}
func (*PayInQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{2}
}

func (m *PayInQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInQueryReq.Unmarshal(m, b)
}
func (m *PayInQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInQueryReq.Marshal(b, m, deterministic)
}
func (m *PayInQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInQueryReq.Merge(m, src)
}
func (m *PayInQueryReq) XXX_Size() int {
	return xxx_messageInfo_PayInQueryReq.Size(m)
}
func (m *PayInQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayInQueryReq proto.InternalMessageInfo

func (m *PayInQueryReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *PayInQueryReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type PayInQueryResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	JsonString           string   `protobuf:"bytes,2,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInQueryResp) Reset()         { *m = PayInQueryResp{} }
func (m *PayInQueryResp) String() string { return proto.CompactTextString(m) }
func (*PayInQueryResp) ProtoMessage()    {}
func (*PayInQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{3}
}

func (m *PayInQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInQueryResp.Unmarshal(m, b)
}
func (m *PayInQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInQueryResp.Marshal(b, m, deterministic)
}
func (m *PayInQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInQueryResp.Merge(m, src)
}
func (m *PayInQueryResp) XXX_Size() int {
	return xxx_messageInfo_PayInQueryResp.Size(m)
}
func (m *PayInQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayInQueryResp proto.InternalMessageInfo

func (m *PayInQueryResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PayInQueryResp) GetJsonString() string {
	if m != nil {
		return m.JsonString
	}
	return ""
}

// 代付订单查询
type PayOutQueryReq struct {
	Company              string   `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Order                string   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutQueryReq) Reset()         { *m = PayOutQueryReq{} }
func (m *PayOutQueryReq) String() string { return proto.CompactTextString(m) }
func (*PayOutQueryReq) ProtoMessage()    {}
func (*PayOutQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{4}
}

func (m *PayOutQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutQueryReq.Unmarshal(m, b)
}
func (m *PayOutQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutQueryReq.Marshal(b, m, deterministic)
}
func (m *PayOutQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutQueryReq.Merge(m, src)
}
func (m *PayOutQueryReq) XXX_Size() int {
	return xxx_messageInfo_PayOutQueryReq.Size(m)
}
func (m *PayOutQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutQueryReq proto.InternalMessageInfo

func (m *PayOutQueryReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *PayOutQueryReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type PayOutQueryResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	JsonString           string   `protobuf:"bytes,2,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutQueryResp) Reset()         { *m = PayOutQueryResp{} }
func (m *PayOutQueryResp) String() string { return proto.CompactTextString(m) }
func (*PayOutQueryResp) ProtoMessage()    {}
func (*PayOutQueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{5}
}

func (m *PayOutQueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutQueryResp.Unmarshal(m, b)
}
func (m *PayOutQueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutQueryResp.Marshal(b, m, deterministic)
}
func (m *PayOutQueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutQueryResp.Merge(m, src)
}
func (m *PayOutQueryResp) XXX_Size() int {
	return xxx_messageInfo_PayOutQueryResp.Size(m)
}
func (m *PayOutQueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutQueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutQueryResp proto.InternalMessageInfo

func (m *PayOutQueryResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PayOutQueryResp) GetJsonString() string {
	if m != nil {
		return m.JsonString
	}
	return ""
}

type PayOutAccount struct {
	BankCode             string   `protobuf:"bytes,1,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	AccountNo            string   `protobuf:"bytes,2,opt,name=accountNo,proto3" json:"accountNo,omitempty"`
	AccountName          string   `protobuf:"bytes,3,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Document             string   `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutAccount) Reset()         { *m = PayOutAccount{} }
func (m *PayOutAccount) String() string { return proto.CompactTextString(m) }
func (*PayOutAccount) ProtoMessage()    {}
func (*PayOutAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{6}
}

func (m *PayOutAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutAccount.Unmarshal(m, b)
}
func (m *PayOutAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutAccount.Marshal(b, m, deterministic)
}
func (m *PayOutAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutAccount.Merge(m, src)
}
func (m *PayOutAccount) XXX_Size() int {
	return xxx_messageInfo_PayOutAccount.Size(m)
}
func (m *PayOutAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutAccount.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutAccount proto.InternalMessageInfo

func (m *PayOutAccount) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *PayOutAccount) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *PayOutAccount) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *PayOutAccount) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

// 代付
type PayOutReq struct {
	Company              string         `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Area                 string         `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	Currency             string         `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Money                string         `protobuf:"bytes,4,opt,name=money,proto3" json:"money,omitempty"`
	Account              *PayOutAccount `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayOutReq) Reset()         { *m = PayOutReq{} }
func (m *PayOutReq) String() string { return proto.CompactTextString(m) }
func (*PayOutReq) ProtoMessage()    {}
func (*PayOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{7}
}

func (m *PayOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutReq.Unmarshal(m, b)
}
func (m *PayOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutReq.Marshal(b, m, deterministic)
}
func (m *PayOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutReq.Merge(m, src)
}
func (m *PayOutReq) XXX_Size() int {
	return xxx_messageInfo_PayOutReq.Size(m)
}
func (m *PayOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutReq proto.InternalMessageInfo

func (m *PayOutReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *PayOutReq) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *PayOutReq) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PayOutReq) GetMoney() string {
	if m != nil {
		return m.Money
	}
	return ""
}

func (m *PayOutReq) GetAccount() *PayOutAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

type PayOutResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	PayCode              string   `protobuf:"bytes,2,opt,name=payCode,proto3" json:"payCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutResp) Reset()         { *m = PayOutResp{} }
func (m *PayOutResp) String() string { return proto.CompactTextString(m) }
func (*PayOutResp) ProtoMessage()    {}
func (*PayOutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{8}
}

func (m *PayOutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutResp.Unmarshal(m, b)
}
func (m *PayOutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutResp.Marshal(b, m, deterministic)
}
func (m *PayOutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutResp.Merge(m, src)
}
func (m *PayOutResp) XXX_Size() int {
	return xxx_messageInfo_PayOutResp.Size(m)
}
func (m *PayOutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutResp proto.InternalMessageInfo

func (m *PayOutResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PayOutResp) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

// 第三方回调数据
type PayNotificationReq struct {
	JsonResult           []byte   `protobuf:"bytes,1,opt,name=jsonResult,proto3" json:"jsonResult,omitempty"`
	TimestampResult      string   `protobuf:"bytes,2,opt,name=timestampResult,proto3" json:"timestampResult,omitempty"`
	SignatureResult      string   `protobuf:"bytes,3,opt,name=signatureResult,proto3" json:"signatureResult,omitempty"`
	Company              string   `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayNotificationReq) Reset()         { *m = PayNotificationReq{} }
func (m *PayNotificationReq) String() string { return proto.CompactTextString(m) }
func (*PayNotificationReq) ProtoMessage()    {}
func (*PayNotificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{9}
}

func (m *PayNotificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayNotificationReq.Unmarshal(m, b)
}
func (m *PayNotificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayNotificationReq.Marshal(b, m, deterministic)
}
func (m *PayNotificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayNotificationReq.Merge(m, src)
}
func (m *PayNotificationReq) XXX_Size() int {
	return xxx_messageInfo_PayNotificationReq.Size(m)
}
func (m *PayNotificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayNotificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayNotificationReq proto.InternalMessageInfo

func (m *PayNotificationReq) GetJsonResult() []byte {
	if m != nil {
		return m.JsonResult
	}
	return nil
}

func (m *PayNotificationReq) GetTimestampResult() string {
	if m != nil {
		return m.TimestampResult
	}
	return ""
}

func (m *PayNotificationReq) GetSignatureResult() string {
	if m != nil {
		return m.SignatureResult
	}
	return ""
}

func (m *PayNotificationReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type PayNotificationResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayNotificationResp) Reset()         { *m = PayNotificationResp{} }
func (m *PayNotificationResp) String() string { return proto.CompactTextString(m) }
func (*PayNotificationResp) ProtoMessage()    {}
func (*PayNotificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{10}
}

func (m *PayNotificationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayNotificationResp.Unmarshal(m, b)
}
func (m *PayNotificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayNotificationResp.Marshal(b, m, deterministic)
}
func (m *PayNotificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayNotificationResp.Merge(m, src)
}
func (m *PayNotificationResp) XXX_Size() int {
	return xxx_messageInfo_PayNotificationResp.Size(m)
}
func (m *PayNotificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayNotificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayNotificationResp proto.InternalMessageInfo

func (m *PayNotificationResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 第三方回调数据
type PayOutNotifyReq struct {
	JsonResult           []byte   `protobuf:"bytes,1,opt,name=jsonResult,proto3" json:"jsonResult,omitempty"`
	TimestampResult      string   `protobuf:"bytes,2,opt,name=timestampResult,proto3" json:"timestampResult,omitempty"`
	SignatureResult      string   `protobuf:"bytes,3,opt,name=signatureResult,proto3" json:"signatureResult,omitempty"`
	Company              string   `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutNotifyReq) Reset()         { *m = PayOutNotifyReq{} }
func (m *PayOutNotifyReq) String() string { return proto.CompactTextString(m) }
func (*PayOutNotifyReq) ProtoMessage()    {}
func (*PayOutNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{11}
}

func (m *PayOutNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutNotifyReq.Unmarshal(m, b)
}
func (m *PayOutNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutNotifyReq.Marshal(b, m, deterministic)
}
func (m *PayOutNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutNotifyReq.Merge(m, src)
}
func (m *PayOutNotifyReq) XXX_Size() int {
	return xxx_messageInfo_PayOutNotifyReq.Size(m)
}
func (m *PayOutNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutNotifyReq proto.InternalMessageInfo

func (m *PayOutNotifyReq) GetJsonResult() []byte {
	if m != nil {
		return m.JsonResult
	}
	return nil
}

func (m *PayOutNotifyReq) GetTimestampResult() string {
	if m != nil {
		return m.TimestampResult
	}
	return ""
}

func (m *PayOutNotifyReq) GetSignatureResult() string {
	if m != nil {
		return m.SignatureResult
	}
	return ""
}

func (m *PayOutNotifyReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type PayOutNotifyResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOutNotifyResp) Reset()         { *m = PayOutNotifyResp{} }
func (m *PayOutNotifyResp) String() string { return proto.CompactTextString(m) }
func (*PayOutNotifyResp) ProtoMessage()    {}
func (*PayOutNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{12}
}

func (m *PayOutNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOutNotifyResp.Unmarshal(m, b)
}
func (m *PayOutNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOutNotifyResp.Marshal(b, m, deterministic)
}
func (m *PayOutNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOutNotifyResp.Merge(m, src)
}
func (m *PayOutNotifyResp) XXX_Size() int {
	return xxx_messageInfo_PayOutNotifyResp.Size(m)
}
func (m *PayOutNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOutNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayOutNotifyResp proto.InternalMessageInfo

func (m *PayOutNotifyResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 余额查询
type BalanceReq struct {
	Company              string   `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceReq) Reset()         { *m = BalanceReq{} }
func (m *BalanceReq) String() string { return proto.CompactTextString(m) }
func (*BalanceReq) ProtoMessage()    {}
func (*BalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{13}
}

func (m *BalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceReq.Unmarshal(m, b)
}
func (m *BalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceReq.Marshal(b, m, deterministic)
}
func (m *BalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceReq.Merge(m, src)
}
func (m *BalanceReq) XXX_Size() int {
	return xxx_messageInfo_BalanceReq.Size(m)
}
func (m *BalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceReq proto.InternalMessageInfo

func (m *BalanceReq) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type BalanceResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	JsonString           string   `protobuf:"bytes,2,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResp) Reset()         { *m = BalanceResp{} }
func (m *BalanceResp) String() string { return proto.CompactTextString(m) }
func (*BalanceResp) ProtoMessage()    {}
func (*BalanceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{14}
}

func (m *BalanceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResp.Unmarshal(m, b)
}
func (m *BalanceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResp.Marshal(b, m, deterministic)
}
func (m *BalanceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResp.Merge(m, src)
}
func (m *BalanceResp) XXX_Size() int {
	return xxx_messageInfo_BalanceResp.Size(m)
}
func (m *BalanceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResp.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResp proto.InternalMessageInfo

func (m *BalanceResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *BalanceResp) GetJsonString() string {
	if m != nil {
		return m.JsonString
	}
	return ""
}

// 提现
type WithdrawReq struct {
	PayType              string   `protobuf:"bytes,1,opt,name=payType,proto3" json:"payType,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BindId               int32    `protobuf:"varint,3,opt,name=bindId,proto3" json:"bindId,omitempty"`
	UAddress             string   `protobuf:"bytes,4,opt,name=uAddress,proto3" json:"uAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawReq) Reset()         { *m = WithdrawReq{} }
func (m *WithdrawReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawReq) ProtoMessage()    {}
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{15}
}

func (m *WithdrawReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawReq.Unmarshal(m, b)
}
func (m *WithdrawReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawReq.Marshal(b, m, deterministic)
}
func (m *WithdrawReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawReq.Merge(m, src)
}
func (m *WithdrawReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawReq.Size(m)
}
func (m *WithdrawReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawReq proto.InternalMessageInfo

func (m *WithdrawReq) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *WithdrawReq) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *WithdrawReq) GetBindId() int32 {
	if m != nil {
		return m.BindId
	}
	return 0
}

func (m *WithdrawReq) GetUAddress() string {
	if m != nil {
		return m.UAddress
	}
	return ""
}

// 提现返回
type WithdrawResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResp) Reset()         { *m = WithdrawResp{} }
func (m *WithdrawResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawResp) ProtoMessage()    {}
func (*WithdrawResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{16}
}

func (m *WithdrawResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResp.Unmarshal(m, b)
}
func (m *WithdrawResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResp.Marshal(b, m, deterministic)
}
func (m *WithdrawResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResp.Merge(m, src)
}
func (m *WithdrawResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawResp.Size(m)
}
func (m *WithdrawResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResp proto.InternalMessageInfo

func (m *WithdrawResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 平台打款
type PlatPayReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatPayReq) Reset()         { *m = PlatPayReq{} }
func (m *PlatPayReq) String() string { return proto.CompactTextString(m) }
func (*PlatPayReq) ProtoMessage()    {}
func (*PlatPayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{17}
}

func (m *PlatPayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatPayReq.Unmarshal(m, b)
}
func (m *PlatPayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatPayReq.Marshal(b, m, deterministic)
}
func (m *PlatPayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatPayReq.Merge(m, src)
}
func (m *PlatPayReq) XXX_Size() int {
	return xxx_messageInfo_PlatPayReq.Size(m)
}
func (m *PlatPayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatPayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatPayReq proto.InternalMessageInfo

func (m *PlatPayReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PlatPayReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 提现返回
type PlatPayResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	PayCode              string   `protobuf:"bytes,2,opt,name=payCode,proto3" json:"payCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatPayResp) Reset()         { *m = PlatPayResp{} }
func (m *PlatPayResp) String() string { return proto.CompactTextString(m) }
func (*PlatPayResp) ProtoMessage()    {}
func (*PlatPayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{18}
}

func (m *PlatPayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatPayResp.Unmarshal(m, b)
}
func (m *PlatPayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatPayResp.Marshal(b, m, deterministic)
}
func (m *PlatPayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatPayResp.Merge(m, src)
}
func (m *PlatPayResp) XXX_Size() int {
	return xxx_messageInfo_PlatPayResp.Size(m)
}
func (m *PlatPayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatPayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatPayResp proto.InternalMessageInfo

func (m *PlatPayResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PlatPayResp) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

// 平台驳回
type PlatRejectPayReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatRejectPayReq) Reset()         { *m = PlatRejectPayReq{} }
func (m *PlatRejectPayReq) String() string { return proto.CompactTextString(m) }
func (*PlatRejectPayReq) ProtoMessage()    {}
func (*PlatRejectPayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{19}
}

func (m *PlatRejectPayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatRejectPayReq.Unmarshal(m, b)
}
func (m *PlatRejectPayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatRejectPayReq.Marshal(b, m, deterministic)
}
func (m *PlatRejectPayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatRejectPayReq.Merge(m, src)
}
func (m *PlatRejectPayReq) XXX_Size() int {
	return xxx_messageInfo_PlatRejectPayReq.Size(m)
}
func (m *PlatRejectPayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatRejectPayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatRejectPayReq proto.InternalMessageInfo

func (m *PlatRejectPayReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PlatRejectPayReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PlatRejectPayReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 返回
type PlatRejectPayResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatRejectPayResp) Reset()         { *m = PlatRejectPayResp{} }
func (m *PlatRejectPayResp) String() string { return proto.CompactTextString(m) }
func (*PlatRejectPayResp) ProtoMessage()    {}
func (*PlatRejectPayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{20}
}

func (m *PlatRejectPayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatRejectPayResp.Unmarshal(m, b)
}
func (m *PlatRejectPayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatRejectPayResp.Marshal(b, m, deterministic)
}
func (m *PlatRejectPayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatRejectPayResp.Merge(m, src)
}
func (m *PlatRejectPayResp) XXX_Size() int {
	return xxx_messageInfo_PlatRejectPayResp.Size(m)
}
func (m *PlatRejectPayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatRejectPayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatRejectPayResp proto.InternalMessageInfo

func (m *PlatRejectPayResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 平台冻结直播间钻石消费记录打款
type PlatFreezeLiveRoomDetailReq struct {
	DetailId             int32    `protobuf:"varint,1,opt,name=detailId,proto3" json:"detailId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatFreezeLiveRoomDetailReq) Reset()         { *m = PlatFreezeLiveRoomDetailReq{} }
func (m *PlatFreezeLiveRoomDetailReq) String() string { return proto.CompactTextString(m) }
func (*PlatFreezeLiveRoomDetailReq) ProtoMessage()    {}
func (*PlatFreezeLiveRoomDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{21}
}

func (m *PlatFreezeLiveRoomDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailReq.Unmarshal(m, b)
}
func (m *PlatFreezeLiveRoomDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailReq.Marshal(b, m, deterministic)
}
func (m *PlatFreezeLiveRoomDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatFreezeLiveRoomDetailReq.Merge(m, src)
}
func (m *PlatFreezeLiveRoomDetailReq) XXX_Size() int {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailReq.Size(m)
}
func (m *PlatFreezeLiveRoomDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatFreezeLiveRoomDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlatFreezeLiveRoomDetailReq proto.InternalMessageInfo

func (m *PlatFreezeLiveRoomDetailReq) GetDetailId() int32 {
	if m != nil {
		return m.DetailId
	}
	return 0
}

func (m *PlatFreezeLiveRoomDetailReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 平台冻结直播间钻石消费记录打款返回
type PlatFreezeLiveRoomDetailResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatFreezeLiveRoomDetailResp) Reset()         { *m = PlatFreezeLiveRoomDetailResp{} }
func (m *PlatFreezeLiveRoomDetailResp) String() string { return proto.CompactTextString(m) }
func (*PlatFreezeLiveRoomDetailResp) ProtoMessage()    {}
func (*PlatFreezeLiveRoomDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{22}
}

func (m *PlatFreezeLiveRoomDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailResp.Unmarshal(m, b)
}
func (m *PlatFreezeLiveRoomDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailResp.Marshal(b, m, deterministic)
}
func (m *PlatFreezeLiveRoomDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatFreezeLiveRoomDetailResp.Merge(m, src)
}
func (m *PlatFreezeLiveRoomDetailResp) XXX_Size() int {
	return xxx_messageInfo_PlatFreezeLiveRoomDetailResp.Size(m)
}
func (m *PlatFreezeLiveRoomDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatFreezeLiveRoomDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_PlatFreezeLiveRoomDetailResp proto.InternalMessageInfo

func (m *PlatFreezeLiveRoomDetailResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 代付设置
type WithdrawBindReq struct {
	BankCode             string   `protobuf:"bytes,1,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	AccountNo            string   `protobuf:"bytes,2,opt,name=accountNo,proto3" json:"accountNo,omitempty"`
	AccountName          string   `protobuf:"bytes,3,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Document             string   `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawBindReq) Reset()         { *m = WithdrawBindReq{} }
func (m *WithdrawBindReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawBindReq) ProtoMessage()    {}
func (*WithdrawBindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{23}
}

func (m *WithdrawBindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawBindReq.Unmarshal(m, b)
}
func (m *WithdrawBindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawBindReq.Marshal(b, m, deterministic)
}
func (m *WithdrawBindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawBindReq.Merge(m, src)
}
func (m *WithdrawBindReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawBindReq.Size(m)
}
func (m *WithdrawBindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawBindReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawBindReq proto.InternalMessageInfo

func (m *WithdrawBindReq) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *WithdrawBindReq) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *WithdrawBindReq) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *WithdrawBindReq) GetDocument() string {
	if m != nil {
		return m.Document
	}
	return ""
}

// 代付设置返回
type WithdrawBindResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawBindResp) Reset()         { *m = WithdrawBindResp{} }
func (m *WithdrawBindResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawBindResp) ProtoMessage()    {}
func (*WithdrawBindResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{24}
}

func (m *WithdrawBindResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawBindResp.Unmarshal(m, b)
}
func (m *WithdrawBindResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawBindResp.Marshal(b, m, deterministic)
}
func (m *WithdrawBindResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawBindResp.Merge(m, src)
}
func (m *WithdrawBindResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawBindResp.Size(m)
}
func (m *WithdrawBindResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawBindResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawBindResp proto.InternalMessageInfo

func (m *WithdrawBindResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 获取提现配置列表
type WithdrawListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawListReq) Reset()         { *m = WithdrawListReq{} }
func (m *WithdrawListReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawListReq) ProtoMessage()    {}
func (*WithdrawListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{25}
}

func (m *WithdrawListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawListReq.Unmarshal(m, b)
}
func (m *WithdrawListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawListReq.Marshal(b, m, deterministic)
}
func (m *WithdrawListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawListReq.Merge(m, src)
}
func (m *WithdrawListReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawListReq.Size(m)
}
func (m *WithdrawListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawListReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawListReq proto.InternalMessageInfo

type WithdrawInfo struct {
	PayTypeCode          string   `protobuf:"bytes,1,opt,name=payTypeCode,proto3" json:"payTypeCode,omitempty"`
	PayTypeIcon          string   `protobuf:"bytes,2,opt,name=payTypeIcon,proto3" json:"payTypeIcon,omitempty"`
	ServerFee            string   `protobuf:"bytes,3,opt,name=serverFee,proto3" json:"serverFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawInfo) Reset()         { *m = WithdrawInfo{} }
func (m *WithdrawInfo) String() string { return proto.CompactTextString(m) }
func (*WithdrawInfo) ProtoMessage()    {}
func (*WithdrawInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{26}
}

func (m *WithdrawInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawInfo.Unmarshal(m, b)
}
func (m *WithdrawInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawInfo.Marshal(b, m, deterministic)
}
func (m *WithdrawInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawInfo.Merge(m, src)
}
func (m *WithdrawInfo) XXX_Size() int {
	return xxx_messageInfo_WithdrawInfo.Size(m)
}
func (m *WithdrawInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawInfo proto.InternalMessageInfo

func (m *WithdrawInfo) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *WithdrawInfo) GetPayTypeIcon() string {
	if m != nil {
		return m.PayTypeIcon
	}
	return ""
}

func (m *WithdrawInfo) GetServerFee() string {
	if m != nil {
		return m.ServerFee
	}
	return ""
}

// 提现配置列表
type WithdrawListResp struct {
	List                 []*WithdrawInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WithdrawListResp) Reset()         { *m = WithdrawListResp{} }
func (m *WithdrawListResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawListResp) ProtoMessage()    {}
func (*WithdrawListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{27}
}

func (m *WithdrawListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawListResp.Unmarshal(m, b)
}
func (m *WithdrawListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawListResp.Marshal(b, m, deterministic)
}
func (m *WithdrawListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawListResp.Merge(m, src)
}
func (m *WithdrawListResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawListResp.Size(m)
}
func (m *WithdrawListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawListResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawListResp proto.InternalMessageInfo

func (m *WithdrawListResp) GetList() []*WithdrawInfo {
	if m != nil {
		return m.List
	}
	return nil
}

// 获取提现类型列表
type WithdrawTypeListReq struct {
	PayTypeCode          string   `protobuf:"bytes,1,opt,name=payTypeCode,proto3" json:"payTypeCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawTypeListReq) Reset()         { *m = WithdrawTypeListReq{} }
func (m *WithdrawTypeListReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawTypeListReq) ProtoMessage()    {}
func (*WithdrawTypeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{28}
}

func (m *WithdrawTypeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawTypeListReq.Unmarshal(m, b)
}
func (m *WithdrawTypeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawTypeListReq.Marshal(b, m, deterministic)
}
func (m *WithdrawTypeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawTypeListReq.Merge(m, src)
}
func (m *WithdrawTypeListReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawTypeListReq.Size(m)
}
func (m *WithdrawTypeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawTypeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawTypeListReq proto.InternalMessageInfo

func (m *WithdrawTypeListReq) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

type WithdrawTypeInfo struct {
	BindId               int32          `protobuf:"varint,1,opt,name=bindId,proto3" json:"bindId,omitempty"`
	Account              *PayOutAccount `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WithdrawTypeInfo) Reset()         { *m = WithdrawTypeInfo{} }
func (m *WithdrawTypeInfo) String() string { return proto.CompactTextString(m) }
func (*WithdrawTypeInfo) ProtoMessage()    {}
func (*WithdrawTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{29}
}

func (m *WithdrawTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawTypeInfo.Unmarshal(m, b)
}
func (m *WithdrawTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawTypeInfo.Marshal(b, m, deterministic)
}
func (m *WithdrawTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawTypeInfo.Merge(m, src)
}
func (m *WithdrawTypeInfo) XXX_Size() int {
	return xxx_messageInfo_WithdrawTypeInfo.Size(m)
}
func (m *WithdrawTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawTypeInfo proto.InternalMessageInfo

func (m *WithdrawTypeInfo) GetBindId() int32 {
	if m != nil {
		return m.BindId
	}
	return 0
}

func (m *WithdrawTypeInfo) GetAccount() *PayOutAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

// 提现类型列表
type WithdrawTypeListResp struct {
	List                 []*WithdrawTypeInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WithdrawTypeListResp) Reset()         { *m = WithdrawTypeListResp{} }
func (m *WithdrawTypeListResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawTypeListResp) ProtoMessage()    {}
func (*WithdrawTypeListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ba5db168f3852fa, []int{30}
}

func (m *WithdrawTypeListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawTypeListResp.Unmarshal(m, b)
}
func (m *WithdrawTypeListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawTypeListResp.Marshal(b, m, deterministic)
}
func (m *WithdrawTypeListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawTypeListResp.Merge(m, src)
}
func (m *WithdrawTypeListResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawTypeListResp.Size(m)
}
func (m *WithdrawTypeListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawTypeListResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawTypeListResp proto.InternalMessageInfo

func (m *WithdrawTypeListResp) GetList() []*WithdrawTypeInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PayInReq)(nil), "proto.PayInReq")
	proto.RegisterType((*PayInResp)(nil), "proto.PayInResp")
	proto.RegisterType((*PayInQueryReq)(nil), "proto.PayInQueryReq")
	proto.RegisterType((*PayInQueryResp)(nil), "proto.PayInQueryResp")
	proto.RegisterType((*PayOutQueryReq)(nil), "proto.PayOutQueryReq")
	proto.RegisterType((*PayOutQueryResp)(nil), "proto.PayOutQueryResp")
	proto.RegisterType((*PayOutAccount)(nil), "proto.PayOutAccount")
	proto.RegisterType((*PayOutReq)(nil), "proto.PayOutReq")
	proto.RegisterType((*PayOutResp)(nil), "proto.PayOutResp")
	proto.RegisterType((*PayNotificationReq)(nil), "proto.PayNotificationReq")
	proto.RegisterType((*PayNotificationResp)(nil), "proto.PayNotificationResp")
	proto.RegisterType((*PayOutNotifyReq)(nil), "proto.PayOutNotifyReq")
	proto.RegisterType((*PayOutNotifyResp)(nil), "proto.PayOutNotifyResp")
	proto.RegisterType((*BalanceReq)(nil), "proto.BalanceReq")
	proto.RegisterType((*BalanceResp)(nil), "proto.BalanceResp")
	proto.RegisterType((*WithdrawReq)(nil), "proto.WithdrawReq")
	proto.RegisterType((*WithdrawResp)(nil), "proto.WithdrawResp")
	proto.RegisterType((*PlatPayReq)(nil), "proto.PlatPayReq")
	proto.RegisterType((*PlatPayResp)(nil), "proto.PlatPayResp")
	proto.RegisterType((*PlatRejectPayReq)(nil), "proto.PlatRejectPayReq")
	proto.RegisterType((*PlatRejectPayResp)(nil), "proto.PlatRejectPayResp")
	proto.RegisterType((*PlatFreezeLiveRoomDetailReq)(nil), "proto.PlatFreezeLiveRoomDetailReq")
	proto.RegisterType((*PlatFreezeLiveRoomDetailResp)(nil), "proto.PlatFreezeLiveRoomDetailResp")
	proto.RegisterType((*WithdrawBindReq)(nil), "proto.WithdrawBindReq")
	proto.RegisterType((*WithdrawBindResp)(nil), "proto.WithdrawBindResp")
	proto.RegisterType((*WithdrawListReq)(nil), "proto.WithdrawListReq")
	proto.RegisterType((*WithdrawInfo)(nil), "proto.WithdrawInfo")
	proto.RegisterType((*WithdrawListResp)(nil), "proto.WithdrawListResp")
	proto.RegisterType((*WithdrawTypeListReq)(nil), "proto.WithdrawTypeListReq")
	proto.RegisterType((*WithdrawTypeInfo)(nil), "proto.WithdrawTypeInfo")
	proto.RegisterType((*WithdrawTypeListResp)(nil), "proto.WithdrawTypeListResp")
}

func init() {
	proto.RegisterFile("finance/finance.proto", fileDescriptor_0ba5db168f3852fa)
}

var fileDescriptor_0ba5db168f3852fa = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5d, 0x4f, 0xd4, 0x40,
	0x14, 0x4d, 0x61, 0x97, 0x8f, 0xbb, 0x28, 0x4b, 0x41, 0xdd, 0x28, 0x2a, 0x99, 0x07, 0xdc, 0x40,
	0x84, 0x04, 0x13, 0x7d, 0x30, 0x11, 0x01, 0x25, 0xae, 0x21, 0x2c, 0x54, 0x13, 0x13, 0xe2, 0xcb,
	0x6c, 0x3b, 0x8b, 0x85, 0xed, 0x4c, 0x99, 0x4e, 0x31, 0xf5, 0x0f, 0x18, 0x7f, 0x83, 0x0f, 0x26,
	0xfe, 0x52, 0x33, 0xd3, 0x99, 0xed, 0x74, 0x09, 0xc5, 0xc0, 0x83, 0x3e, 0x6d, 0xcf, 0xe9, 0xed,
	0xb9, 0xe7, 0xde, 0xb9, 0x33, 0xb3, 0x70, 0xa7, 0x1f, 0x52, 0x4c, 0x7d, 0xb2, 0xae, 0x7f, 0xd7,
	0x62, 0xce, 0x04, 0x73, 0xeb, 0xea, 0x07, 0x1d, 0xc1, 0xd4, 0x01, 0xce, 0x3a, 0xd4, 0x23, 0x67,
	0x6e, 0x0b, 0x26, 0x7d, 0x16, 0xc5, 0x98, 0x66, 0x2d, 0x67, 0xc9, 0x69, 0x4f, 0x7b, 0x06, 0xba,
	0x0b, 0x50, 0x8f, 0x18, 0x25, 0x59, 0x6b, 0x4c, 0xf1, 0x39, 0x70, 0x1f, 0x01, 0x70, 0x4c, 0x03,
	0x16, 0xed, 0xb0, 0x80, 0xb4, 0xc6, 0xd5, 0x2b, 0x8b, 0x41, 0x5d, 0x98, 0xd6, 0xda, 0x49, 0x2c,
	0xc5, 0x63, 0x9c, 0xa9, 0x48, 0x2d, 0xae, 0xa1, 0xdb, 0x84, 0xf1, 0x94, 0x0f, 0xb4, 0xb4, 0x7c,
	0x74, 0xef, 0xc2, 0xc4, 0x19, 0xb7, 0x44, 0x35, 0x42, 0x9b, 0x70, 0x4b, 0x09, 0x1e, 0xa6, 0x84,
	0x67, 0x57, 0x3a, 0x66, 0x3c, 0x20, 0xdc, 0x38, 0x56, 0x00, 0xbd, 0x83, 0xdb, 0xb6, 0x40, 0x12,
	0xcb, 0x54, 0x9c, 0x24, 0xe9, 0x40, 0x28, 0x81, 0xba, 0xa7, 0x91, 0xac, 0xed, 0x24, 0x61, 0xf4,
	0x83, 0xe0, 0x21, 0x3d, 0xd6, 0x22, 0x16, 0x83, 0x5e, 0x2b, 0xa5, 0x6e, 0x2a, 0xae, 0xed, 0xa5,
	0x03, 0xb3, 0x25, 0x85, 0x1b, 0x98, 0xf9, 0xee, 0xa8, 0xc6, 0x74, 0x53, 0xb1, 0xe5, 0xfb, 0x2c,
	0xa5, 0xc2, 0xbd, 0x0f, 0x53, 0x3d, 0x4c, 0x4f, 0xad, 0x76, 0x0f, 0xb1, 0xbb, 0x08, 0xd3, 0x38,
	0x0f, 0xdb, 0x67, 0x5a, 0xac, 0x20, 0xdc, 0x25, 0x68, 0x18, 0x80, 0x23, 0xb3, 0x00, 0x36, 0x25,
	0xb5, 0x03, 0xe6, 0xa7, 0x11, 0xa1, 0xa2, 0x55, 0xcb, 0xb5, 0x0d, 0x46, 0x3f, 0x1d, 0xb5, 0xe6,
	0xdd, 0x54, 0x54, 0xb7, 0xc4, 0x85, 0x1a, 0xe6, 0x04, 0xeb, 0xf4, 0xea, 0x59, 0xea, 0xfa, 0x29,
	0xe7, 0x84, 0xfa, 0x99, 0x4e, 0x3b, 0xc4, 0xc5, 0x00, 0xd6, 0xec, 0x01, 0x5c, 0x83, 0x49, 0x6d,
	0xac, 0x55, 0x5f, 0x72, 0xda, 0x8d, 0x8d, 0x85, 0x7c, 0xb8, 0xd7, 0x4a, 0xcd, 0xf0, 0x4c, 0x10,
	0x7a, 0x05, 0x60, 0xcc, 0x55, 0x74, 0xdb, 0x9a, 0xd4, 0xb1, 0xd2, 0xa4, 0xa2, 0xdf, 0x0e, 0xb8,
	0x07, 0x38, 0xdb, 0x67, 0x22, 0xec, 0x87, 0x3e, 0x16, 0x21, 0x53, 0xfb, 0x46, 0x2f, 0x8f, 0x57,
	0x88, 0xcd, 0x78, 0x16, 0xe3, 0xb6, 0x61, 0x56, 0x84, 0x11, 0x49, 0x04, 0x8e, 0x62, 0x1d, 0x94,
	0x0b, 0x8f, 0xd2, 0x32, 0x32, 0x09, 0x8f, 0x29, 0x16, 0x29, 0x27, 0x3a, 0x32, 0xef, 0xc4, 0x28,
	0x6d, 0xb7, 0xb6, 0x56, 0x6a, 0x2d, 0x7a, 0x0a, 0xf3, 0x17, 0x3c, 0x5e, 0x5e, 0x2d, 0xfa, 0xe5,
	0x98, 0x39, 0x54, 0x9f, 0x64, 0xff, 0x5f, 0x41, 0x2b, 0xd0, 0x2c, 0x1b, 0xac, 0xa8, 0x66, 0x19,
	0x60, 0x1b, 0x0f, 0xe4, 0x31, 0x57, 0x39, 0x7f, 0xe8, 0x2d, 0x34, 0x86, 0x71, 0x37, 0xd8, 0x78,
	0x09, 0x34, 0x3e, 0x85, 0xe2, 0x4b, 0xc0, 0xf1, 0x57, 0x9d, 0x2f, 0xc6, 0xd9, 0xc7, 0x2c, 0xb6,
	0xcf, 0x38, 0x09, 0x65, 0x02, 0x1c, 0xa9, 0x41, 0xcd, 0x45, 0x34, 0x92, 0x7c, 0x2f, 0xa4, 0x41,
	0x27, 0x50, 0x6d, 0xa9, 0x7b, 0x1a, 0xc9, 0xbd, 0x90, 0x6e, 0x05, 0x01, 0x27, 0x49, 0x62, 0xf6,
	0x98, 0xc1, 0x68, 0x19, 0x66, 0x8a, 0xa4, 0x15, 0xbd, 0x90, 0xd3, 0x3e, 0xc0, 0xe2, 0x00, 0x9b,
	0xe3, 0x49, 0x9d, 0x3b, 0x9d, 0xc0, 0x78, 0xd3, 0x50, 0x7e, 0x9f, 0x26, 0xea, 0x85, 0xf6, 0x96,
	0x23, 0xb4, 0x09, 0x8d, 0xe1, 0xf7, 0xd7, 0xda, 0x2e, 0x9f, 0xa1, 0x29, 0x05, 0x3c, 0x72, 0x42,
	0xfc, 0x6b, 0xdb, 0xc8, 0xf3, 0x46, 0x98, 0x9f, 0x9a, 0xcb, 0x20, 0x47, 0x68, 0x15, 0xe6, 0x46,
	0xd4, 0x2b, 0x7a, 0x71, 0x08, 0x0f, 0x64, 0xf0, 0x2e, 0x27, 0xe4, 0x1b, 0xd9, 0x0b, 0xcf, 0x89,
	0xc7, 0x58, 0xf4, 0x86, 0x08, 0x1c, 0x0e, 0xa4, 0x2b, 0x79, 0xa4, 0x29, 0xa0, 0x6d, 0xd5, 0xbd,
	0x21, 0xbe, 0xb4, 0x3d, 0xcf, 0x61, 0xf1, 0x72, 0xc9, 0x0a, 0x2b, 0x3f, 0x1c, 0x98, 0x35, 0xeb,
	0xb7, 0x1d, 0xd2, 0x40, 0xe7, 0xff, 0x27, 0xc7, 0xf5, 0x0a, 0x34, 0xcb, 0x56, 0x2a, 0x7c, 0xcf,
	0x15, 0xb6, 0xf7, 0xc2, 0x44, 0x9e, 0xef, 0x28, 0x2e, 0x26, 0xb1, 0x43, 0xfb, 0xca, 0x8c, 0x1e,
	0x78, 0xab, 0x12, 0x9b, 0xb2, 0x22, 0x3a, 0x3e, 0xa3, 0xba, 0x1c, 0x9b, 0x92, 0xe5, 0x26, 0x84,
	0x9f, 0x13, 0xbe, 0x4b, 0x4c, 0x39, 0x05, 0x81, 0x5e, 0x16, 0x86, 0x73, 0x13, 0x49, 0xec, 0x3e,
	0x81, 0xda, 0x20, 0x4c, 0xa4, 0xdd, 0xf1, 0x76, 0x63, 0x63, 0x5e, 0x5f, 0x01, 0xb6, 0x31, 0x4f,
	0x05, 0xa0, 0x17, 0x30, 0x6f, 0x58, 0x99, 0x4e, 0x57, 0x71, 0xb5, 0x6b, 0x74, 0x54, 0x64, 0x55,
	0x3e, 0x65, 0xad, 0xc5, 0xce, 0x75, 0x4a, 0x3b, 0xd7, 0xba, 0x93, 0xc6, 0xfe, 0xe6, 0x4e, 0xda,
	0x81, 0x85, 0x8b, 0xa6, 0x92, 0xd8, 0x5d, 0x2d, 0x55, 0x75, 0x6f, 0xa4, 0x2a, 0x63, 0x23, 0xaf,
	0x6c, 0xfb, 0xf1, 0xd1, 0xc3, 0xb3, 0x94, 0xa4, 0xe4, 0x3d, 0xeb, 0xad, 0xc7, 0xa7, 0xc7, 0xeb,
	0x2a, 0xb8, 0x97, 0xf6, 0xcd, 0x7f, 0xbe, 0xde, 0x84, 0x62, 0x9e, 0xfd, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x16, 0xfe, 0xa2, 0x0d, 0x0a, 0x00, 0x00,
}
