// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance/pay.proto

package finance

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 充值中心支付类型列表
type PayTypeItem struct {
	// 支付类型编码
	PayTypeCode string `protobuf:"bytes,1,opt,name=payTypeCode,proto3" json:"payTypeCode,omitempty"`
	// 支付类型名称
	PayTypeName string `protobuf:"bytes,2,opt,name=payTypeName,proto3" json:"payTypeName,omitempty"`
	// 支付类型图标
	PayTypeIcon string `protobuf:"bytes,3,opt,name=payTypeIcon,proto3" json:"payTypeIcon,omitempty"`
	// 支付类描述Title
	DescribeTitle string `protobuf:"bytes,4,opt,name=describeTitle,proto3" json:"describeTitle,omitempty"`
	// 支付类描述内容
	DescribeContent      string   `protobuf:"bytes,5,opt,name=describeContent,proto3" json:"describeContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayTypeItem) Reset()         { *m = PayTypeItem{} }
func (m *PayTypeItem) String() string { return proto.CompactTextString(m) }
func (*PayTypeItem) ProtoMessage()    {}
func (*PayTypeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{0}
}

func (m *PayTypeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayTypeItem.Unmarshal(m, b)
}
func (m *PayTypeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayTypeItem.Marshal(b, m, deterministic)
}
func (m *PayTypeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayTypeItem.Merge(m, src)
}
func (m *PayTypeItem) XXX_Size() int {
	return xxx_messageInfo_PayTypeItem.Size(m)
}
func (m *PayTypeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PayTypeItem.DiscardUnknown(m)
}

var xxx_messageInfo_PayTypeItem proto.InternalMessageInfo

func (m *PayTypeItem) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

func (m *PayTypeItem) GetPayTypeName() string {
	if m != nil {
		return m.PayTypeName
	}
	return ""
}

func (m *PayTypeItem) GetPayTypeIcon() string {
	if m != nil {
		return m.PayTypeIcon
	}
	return ""
}

func (m *PayTypeItem) GetDescribeTitle() string {
	if m != nil {
		return m.DescribeTitle
	}
	return ""
}

func (m *PayTypeItem) GetDescribeContent() string {
	if m != nil {
		return m.DescribeContent
	}
	return ""
}

// 充值中心支付区间
type PayChannel struct {
	// 支付商编码
	ChannelCode string `protobuf:"bytes,1,opt,name=channelCode,proto3" json:"channelCode,omitempty"`
	// 支付区间
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayChannel) Reset()         { *m = PayChannel{} }
func (m *PayChannel) String() string { return proto.CompactTextString(m) }
func (*PayChannel) ProtoMessage()    {}
func (*PayChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{1}
}

func (m *PayChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayChannel.Unmarshal(m, b)
}
func (m *PayChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayChannel.Marshal(b, m, deterministic)
}
func (m *PayChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayChannel.Merge(m, src)
}
func (m *PayChannel) XXX_Size() int {
	return xxx_messageInfo_PayChannel.Size(m)
}
func (m *PayChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_PayChannel.DiscardUnknown(m)
}

var xxx_messageInfo_PayChannel proto.InternalMessageInfo

func (m *PayChannel) GetChannelCode() string {
	if m != nil {
		return m.ChannelCode
	}
	return ""
}

func (m *PayChannel) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

// 获取充值中心响应
type GetRechargeCenterResp struct {
	// 币种编码
	CoinCode string `protobuf:"bytes,1,opt,name=coinCode,proto3" json:"coinCode,omitempty"`
	// 国家编码
	CountryCode string `protobuf:"bytes,2,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	// 余额
	Balance string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	// 钻石
	Diamond string `protobuf:"bytes,4,opt,name=diamond,proto3" json:"diamond,omitempty"`
	// 兑换金额(约等于)
	ExchangeAmount string `protobuf:"bytes,6,opt,name=exchangeAmount,proto3" json:"exchangeAmount,omitempty"`
	// 支付类型列表
	PayTypeList []*PayTypeItem `protobuf:"bytes,7,rep,name=payTypeList,proto3" json:"payTypeList,omitempty"`
	// 支付区间
	ChannelList          []*PayChannel `protobuf:"bytes,8,rep,name=channelList,proto3" json:"channelList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRechargeCenterResp) Reset()         { *m = GetRechargeCenterResp{} }
func (m *GetRechargeCenterResp) String() string { return proto.CompactTextString(m) }
func (*GetRechargeCenterResp) ProtoMessage()    {}
func (*GetRechargeCenterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{2}
}

func (m *GetRechargeCenterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRechargeCenterResp.Unmarshal(m, b)
}
func (m *GetRechargeCenterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRechargeCenterResp.Marshal(b, m, deterministic)
}
func (m *GetRechargeCenterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRechargeCenterResp.Merge(m, src)
}
func (m *GetRechargeCenterResp) XXX_Size() int {
	return xxx_messageInfo_GetRechargeCenterResp.Size(m)
}
func (m *GetRechargeCenterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRechargeCenterResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRechargeCenterResp proto.InternalMessageInfo

func (m *GetRechargeCenterResp) GetCoinCode() string {
	if m != nil {
		return m.CoinCode
	}
	return ""
}

func (m *GetRechargeCenterResp) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *GetRechargeCenterResp) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetRechargeCenterResp) GetDiamond() string {
	if m != nil {
		return m.Diamond
	}
	return ""
}

func (m *GetRechargeCenterResp) GetExchangeAmount() string {
	if m != nil {
		return m.ExchangeAmount
	}
	return ""
}

func (m *GetRechargeCenterResp) GetPayTypeList() []*PayTypeItem {
	if m != nil {
		return m.PayTypeList
	}
	return nil
}

func (m *GetRechargeCenterResp) GetChannelList() []*PayChannel {
	if m != nil {
		return m.ChannelList
	}
	return nil
}

// 通过支付类型编码国家编码获取渠道商请求
type GetZoneByPayTypeCodeReq struct {
	// 支付类型编码
	PayTypeCode          string   `protobuf:"bytes,1,opt,name=payTypeCode,proto3" json:"payTypeCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetZoneByPayTypeCodeReq) Reset()         { *m = GetZoneByPayTypeCodeReq{} }
func (m *GetZoneByPayTypeCodeReq) String() string { return proto.CompactTextString(m) }
func (*GetZoneByPayTypeCodeReq) ProtoMessage()    {}
func (*GetZoneByPayTypeCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{3}
}

func (m *GetZoneByPayTypeCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetZoneByPayTypeCodeReq.Unmarshal(m, b)
}
func (m *GetZoneByPayTypeCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetZoneByPayTypeCodeReq.Marshal(b, m, deterministic)
}
func (m *GetZoneByPayTypeCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetZoneByPayTypeCodeReq.Merge(m, src)
}
func (m *GetZoneByPayTypeCodeReq) XXX_Size() int {
	return xxx_messageInfo_GetZoneByPayTypeCodeReq.Size(m)
}
func (m *GetZoneByPayTypeCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetZoneByPayTypeCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetZoneByPayTypeCodeReq proto.InternalMessageInfo

func (m *GetZoneByPayTypeCodeReq) GetPayTypeCode() string {
	if m != nil {
		return m.PayTypeCode
	}
	return ""
}

// 通过支付类型编码国家编码获取渠道商响应
type GetZoneByPayTypeCodeResp struct {
	// 支付区间
	ChannelList          []*PayChannel `protobuf:"bytes,8,rep,name=channelList,proto3" json:"channelList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetZoneByPayTypeCodeResp) Reset()         { *m = GetZoneByPayTypeCodeResp{} }
func (m *GetZoneByPayTypeCodeResp) String() string { return proto.CompactTextString(m) }
func (*GetZoneByPayTypeCodeResp) ProtoMessage()    {}
func (*GetZoneByPayTypeCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{4}
}

func (m *GetZoneByPayTypeCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetZoneByPayTypeCodeResp.Unmarshal(m, b)
}
func (m *GetZoneByPayTypeCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetZoneByPayTypeCodeResp.Marshal(b, m, deterministic)
}
func (m *GetZoneByPayTypeCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetZoneByPayTypeCodeResp.Merge(m, src)
}
func (m *GetZoneByPayTypeCodeResp) XXX_Size() int {
	return xxx_messageInfo_GetZoneByPayTypeCodeResp.Size(m)
}
func (m *GetZoneByPayTypeCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetZoneByPayTypeCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetZoneByPayTypeCodeResp proto.InternalMessageInfo

func (m *GetZoneByPayTypeCodeResp) GetChannelList() []*PayChannel {
	if m != nil {
		return m.ChannelList
	}
	return nil
}

// 充值中心随机码响应
type GetPayRandomCodeResp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPayRandomCodeResp) Reset()         { *m = GetPayRandomCodeResp{} }
func (m *GetPayRandomCodeResp) String() string { return proto.CompactTextString(m) }
func (*GetPayRandomCodeResp) ProtoMessage()    {}
func (*GetPayRandomCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{5}
}

func (m *GetPayRandomCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayRandomCodeResp.Unmarshal(m, b)
}
func (m *GetPayRandomCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayRandomCodeResp.Marshal(b, m, deterministic)
}
func (m *GetPayRandomCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayRandomCodeResp.Merge(m, src)
}
func (m *GetPayRandomCodeResp) XXX_Size() int {
	return xxx_messageInfo_GetPayRandomCodeResp.Size(m)
}
func (m *GetPayRandomCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayRandomCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayRandomCodeResp proto.InternalMessageInfo

func (m *GetPayRandomCodeResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// 钻石兑换项
type DiamondExchangeItem struct {
	USD                  int32    `protobuf:"varint,1,opt,name=USD,proto3" json:"USD,omitempty"`
	Diamond              int32    `protobuf:"varint,2,opt,name=Diamond,proto3" json:"Diamond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondExchangeItem) Reset()         { *m = DiamondExchangeItem{} }
func (m *DiamondExchangeItem) String() string { return proto.CompactTextString(m) }
func (*DiamondExchangeItem) ProtoMessage()    {}
func (*DiamondExchangeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{6}
}

func (m *DiamondExchangeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondExchangeItem.Unmarshal(m, b)
}
func (m *DiamondExchangeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondExchangeItem.Marshal(b, m, deterministic)
}
func (m *DiamondExchangeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondExchangeItem.Merge(m, src)
}
func (m *DiamondExchangeItem) XXX_Size() int {
	return xxx_messageInfo_DiamondExchangeItem.Size(m)
}
func (m *DiamondExchangeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondExchangeItem.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondExchangeItem proto.InternalMessageInfo

func (m *DiamondExchangeItem) GetUSD() int32 {
	if m != nil {
		return m.USD
	}
	return 0
}

func (m *DiamondExchangeItem) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

// 获取钻石响应
type GetDiamondResp struct {
	// 余额
	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// 钻石
	Diamond string `protobuf:"bytes,2,opt,name=diamond,proto3" json:"diamond,omitempty"`
	// 兑换金额(约等于)
	ExchangeAmount string `protobuf:"bytes,3,opt,name=exchangeAmount,proto3" json:"exchangeAmount,omitempty"`
	// VIP等级
	LevelId int32 `protobuf:"varint,4,opt,name=levelId,proto3" json:"levelId,omitempty"`
	// 钻石兑换项列表
	List                 []*DiamondExchangeItem `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDiamondResp) Reset()         { *m = GetDiamondResp{} }
func (m *GetDiamondResp) String() string { return proto.CompactTextString(m) }
func (*GetDiamondResp) ProtoMessage()    {}
func (*GetDiamondResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{7}
}

func (m *GetDiamondResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiamondResp.Unmarshal(m, b)
}
func (m *GetDiamondResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiamondResp.Marshal(b, m, deterministic)
}
func (m *GetDiamondResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiamondResp.Merge(m, src)
}
func (m *GetDiamondResp) XXX_Size() int {
	return xxx_messageInfo_GetDiamondResp.Size(m)
}
func (m *GetDiamondResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiamondResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiamondResp proto.InternalMessageInfo

func (m *GetDiamondResp) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetDiamondResp) GetDiamond() string {
	if m != nil {
		return m.Diamond
	}
	return ""
}

func (m *GetDiamondResp) GetExchangeAmount() string {
	if m != nil {
		return m.ExchangeAmount
	}
	return ""
}

func (m *GetDiamondResp) GetLevelId() int32 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

func (m *GetDiamondResp) GetList() []*DiamondExchangeItem {
	if m != nil {
		return m.List
	}
	return nil
}

// 钻石兑换请求
type DiamondExchangeReq struct {
	// 兑换美元
	USD int32 `protobuf:"varint,1,opt,name=USD,proto3" json:"USD,omitempty"`
	// 兑换钻石
	Diamond              int32    `protobuf:"varint,2,opt,name=diamond,proto3" json:"diamond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondExchangeReq) Reset()         { *m = DiamondExchangeReq{} }
func (m *DiamondExchangeReq) String() string { return proto.CompactTextString(m) }
func (*DiamondExchangeReq) ProtoMessage()    {}
func (*DiamondExchangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{8}
}

func (m *DiamondExchangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondExchangeReq.Unmarshal(m, b)
}
func (m *DiamondExchangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondExchangeReq.Marshal(b, m, deterministic)
}
func (m *DiamondExchangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondExchangeReq.Merge(m, src)
}
func (m *DiamondExchangeReq) XXX_Size() int {
	return xxx_messageInfo_DiamondExchangeReq.Size(m)
}
func (m *DiamondExchangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondExchangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondExchangeReq proto.InternalMessageInfo

func (m *DiamondExchangeReq) GetUSD() int32 {
	if m != nil {
		return m.USD
	}
	return 0
}

func (m *DiamondExchangeReq) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

// 充值记录列表请求
type RechargeRecordListReq struct {
	// 页码
	PageNumber int32 `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	// 页大小
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeRecordListReq) Reset()         { *m = RechargeRecordListReq{} }
func (m *RechargeRecordListReq) String() string { return proto.CompactTextString(m) }
func (*RechargeRecordListReq) ProtoMessage()    {}
func (*RechargeRecordListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{9}
}

func (m *RechargeRecordListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeRecordListReq.Unmarshal(m, b)
}
func (m *RechargeRecordListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeRecordListReq.Marshal(b, m, deterministic)
}
func (m *RechargeRecordListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeRecordListReq.Merge(m, src)
}
func (m *RechargeRecordListReq) XXX_Size() int {
	return xxx_messageInfo_RechargeRecordListReq.Size(m)
}
func (m *RechargeRecordListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeRecordListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeRecordListReq proto.InternalMessageInfo

func (m *RechargeRecordListReq) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *RechargeRecordListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 充值记录列表项
type RechargeRecordItem struct {
	// 订单Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 账单号
	BillNo string `protobuf:"bytes,2,opt,name=billNo,proto3" json:"billNo,omitempty"`
	// 充值金额
	OrderAmount string `protobuf:"bytes,3,opt,name=orderAmount,proto3" json:"orderAmount,omitempty"`
	// 充值时间
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 状态
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RechargeRecordItem) Reset()         { *m = RechargeRecordItem{} }
func (m *RechargeRecordItem) String() string { return proto.CompactTextString(m) }
func (*RechargeRecordItem) ProtoMessage()    {}
func (*RechargeRecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{10}
}

func (m *RechargeRecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeRecordItem.Unmarshal(m, b)
}
func (m *RechargeRecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeRecordItem.Marshal(b, m, deterministic)
}
func (m *RechargeRecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeRecordItem.Merge(m, src)
}
func (m *RechargeRecordItem) XXX_Size() int {
	return xxx_messageInfo_RechargeRecordItem.Size(m)
}
func (m *RechargeRecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeRecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeRecordItem proto.InternalMessageInfo

func (m *RechargeRecordItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RechargeRecordItem) GetBillNo() string {
	if m != nil {
		return m.BillNo
	}
	return ""
}

func (m *RechargeRecordItem) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *RechargeRecordItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RechargeRecordItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// 充值记录列表响应
type RechargeRecordListResp struct {
	// 总记录数
	TotalRecord int32 `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	// 总页数
	TotalPage int32 `protobuf:"varint,2,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	// 页面大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 页码
	PageNum int32 `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 充值记录列表项
	List                 []*RechargeRecordItem `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RechargeRecordListResp) Reset()         { *m = RechargeRecordListResp{} }
func (m *RechargeRecordListResp) String() string { return proto.CompactTextString(m) }
func (*RechargeRecordListResp) ProtoMessage()    {}
func (*RechargeRecordListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{11}
}

func (m *RechargeRecordListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RechargeRecordListResp.Unmarshal(m, b)
}
func (m *RechargeRecordListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RechargeRecordListResp.Marshal(b, m, deterministic)
}
func (m *RechargeRecordListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RechargeRecordListResp.Merge(m, src)
}
func (m *RechargeRecordListResp) XXX_Size() int {
	return xxx_messageInfo_RechargeRecordListResp.Size(m)
}
func (m *RechargeRecordListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RechargeRecordListResp.DiscardUnknown(m)
}

var xxx_messageInfo_RechargeRecordListResp proto.InternalMessageInfo

func (m *RechargeRecordListResp) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *RechargeRecordListResp) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *RechargeRecordListResp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *RechargeRecordListResp) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *RechargeRecordListResp) GetList() []*RechargeRecordItem {
	if m != nil {
		return m.List
	}
	return nil
}

// 提现列表请求
type WithdrawRecordListReq struct {
	// 页码
	PageNumber int32 `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	// 页大小
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRecordListReq) Reset()         { *m = WithdrawRecordListReq{} }
func (m *WithdrawRecordListReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawRecordListReq) ProtoMessage()    {}
func (*WithdrawRecordListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{12}
}

func (m *WithdrawRecordListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRecordListReq.Unmarshal(m, b)
}
func (m *WithdrawRecordListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRecordListReq.Marshal(b, m, deterministic)
}
func (m *WithdrawRecordListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRecordListReq.Merge(m, src)
}
func (m *WithdrawRecordListReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawRecordListReq.Size(m)
}
func (m *WithdrawRecordListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRecordListReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRecordListReq proto.InternalMessageInfo

func (m *WithdrawRecordListReq) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *WithdrawRecordListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 提现列表项
type WithdrawRecordItem struct {
	// 订单Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 账单号
	BillNo string `protobuf:"bytes,2,opt,name=billNo,proto3" json:"billNo,omitempty"`
	// 充值金额
	OrderAmount string `protobuf:"bytes,3,opt,name=orderAmount,proto3" json:"orderAmount,omitempty"`
	// 充值时间
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 状态
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRecordItem) Reset()         { *m = WithdrawRecordItem{} }
func (m *WithdrawRecordItem) String() string { return proto.CompactTextString(m) }
func (*WithdrawRecordItem) ProtoMessage()    {}
func (*WithdrawRecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{13}
}

func (m *WithdrawRecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRecordItem.Unmarshal(m, b)
}
func (m *WithdrawRecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRecordItem.Marshal(b, m, deterministic)
}
func (m *WithdrawRecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRecordItem.Merge(m, src)
}
func (m *WithdrawRecordItem) XXX_Size() int {
	return xxx_messageInfo_WithdrawRecordItem.Size(m)
}
func (m *WithdrawRecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRecordItem proto.InternalMessageInfo

func (m *WithdrawRecordItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WithdrawRecordItem) GetBillNo() string {
	if m != nil {
		return m.BillNo
	}
	return ""
}

func (m *WithdrawRecordItem) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *WithdrawRecordItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *WithdrawRecordItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// 提现列表响应
type WithdrawRecordListResp struct {
	// 总记录数
	TotalRecord int32 `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	// 总页数
	TotalPage int32 `protobuf:"varint,2,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	// 页面大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 页码
	PageNum int32 `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 充值记录列表项
	List                 []*WithdrawRecordItem `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WithdrawRecordListResp) Reset()         { *m = WithdrawRecordListResp{} }
func (m *WithdrawRecordListResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawRecordListResp) ProtoMessage()    {}
func (*WithdrawRecordListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{14}
}

func (m *WithdrawRecordListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRecordListResp.Unmarshal(m, b)
}
func (m *WithdrawRecordListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRecordListResp.Marshal(b, m, deterministic)
}
func (m *WithdrawRecordListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRecordListResp.Merge(m, src)
}
func (m *WithdrawRecordListResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawRecordListResp.Size(m)
}
func (m *WithdrawRecordListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRecordListResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRecordListResp proto.InternalMessageInfo

func (m *WithdrawRecordListResp) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *WithdrawRecordListResp) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *WithdrawRecordListResp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *WithdrawRecordListResp) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *WithdrawRecordListResp) GetList() []*WithdrawRecordItem {
	if m != nil {
		return m.List
	}
	return nil
}

// 查看提现失败详情请求
type CheckWithdrawDetailReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWithdrawDetailReq) Reset()         { *m = CheckWithdrawDetailReq{} }
func (m *CheckWithdrawDetailReq) String() string { return proto.CompactTextString(m) }
func (*CheckWithdrawDetailReq) ProtoMessage()    {}
func (*CheckWithdrawDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{15}
}

func (m *CheckWithdrawDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWithdrawDetailReq.Unmarshal(m, b)
}
func (m *CheckWithdrawDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWithdrawDetailReq.Marshal(b, m, deterministic)
}
func (m *CheckWithdrawDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWithdrawDetailReq.Merge(m, src)
}
func (m *CheckWithdrawDetailReq) XXX_Size() int {
	return xxx_messageInfo_CheckWithdrawDetailReq.Size(m)
}
func (m *CheckWithdrawDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWithdrawDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWithdrawDetailReq proto.InternalMessageInfo

func (m *CheckWithdrawDetailReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 查看提现失败详情响应
type CheckWithdrawDetailResp struct {
	Remark               string   `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWithdrawDetailResp) Reset()         { *m = CheckWithdrawDetailResp{} }
func (m *CheckWithdrawDetailResp) String() string { return proto.CompactTextString(m) }
func (*CheckWithdrawDetailResp) ProtoMessage()    {}
func (*CheckWithdrawDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{16}
}

func (m *CheckWithdrawDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWithdrawDetailResp.Unmarshal(m, b)
}
func (m *CheckWithdrawDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWithdrawDetailResp.Marshal(b, m, deterministic)
}
func (m *CheckWithdrawDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWithdrawDetailResp.Merge(m, src)
}
func (m *CheckWithdrawDetailResp) XXX_Size() int {
	return xxx_messageInfo_CheckWithdrawDetailResp.Size(m)
}
func (m *CheckWithdrawDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWithdrawDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWithdrawDetailResp proto.InternalMessageInfo

func (m *CheckWithdrawDetailResp) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 我的资产响应(用户端)
type MyAssetResp struct {
	// 余额
	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// 钻石
	Diamond string `protobuf:"bytes,2,opt,name=diamond,proto3" json:"diamond,omitempty"`
	// 已赠送钻石
	SendDiamond          string   `protobuf:"bytes,3,opt,name=sendDiamond,proto3" json:"sendDiamond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyAssetResp) Reset()         { *m = MyAssetResp{} }
func (m *MyAssetResp) String() string { return proto.CompactTextString(m) }
func (*MyAssetResp) ProtoMessage()    {}
func (*MyAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{17}
}

func (m *MyAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyAssetResp.Unmarshal(m, b)
}
func (m *MyAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyAssetResp.Marshal(b, m, deterministic)
}
func (m *MyAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyAssetResp.Merge(m, src)
}
func (m *MyAssetResp) XXX_Size() int {
	return xxx_messageInfo_MyAssetResp.Size(m)
}
func (m *MyAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MyAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_MyAssetResp proto.InternalMessageInfo

func (m *MyAssetResp) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *MyAssetResp) GetDiamond() string {
	if m != nil {
		return m.Diamond
	}
	return ""
}

func (m *MyAssetResp) GetSendDiamond() string {
	if m != nil {
		return m.SendDiamond
	}
	return ""
}

// 收入明细列表请求
type GetIncomeDetailListReq struct {
	// 查询类型1消费明细列表 2收入明细列表
	QueryType int32 `protobuf:"varint,1,opt,name=queryType,proto3" json:"queryType,omitempty"`
	// 日期
	Date string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	// 页码
	PageNumber int32 `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	// 页大小
	PageSize int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 用户手机的时区
	TimeZone             string   `protobuf:"bytes,5,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIncomeDetailListReq) Reset()         { *m = GetIncomeDetailListReq{} }
func (m *GetIncomeDetailListReq) String() string { return proto.CompactTextString(m) }
func (*GetIncomeDetailListReq) ProtoMessage()    {}
func (*GetIncomeDetailListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{18}
}

func (m *GetIncomeDetailListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIncomeDetailListReq.Unmarshal(m, b)
}
func (m *GetIncomeDetailListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIncomeDetailListReq.Marshal(b, m, deterministic)
}
func (m *GetIncomeDetailListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIncomeDetailListReq.Merge(m, src)
}
func (m *GetIncomeDetailListReq) XXX_Size() int {
	return xxx_messageInfo_GetIncomeDetailListReq.Size(m)
}
func (m *GetIncomeDetailListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIncomeDetailListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetIncomeDetailListReq proto.InternalMessageInfo

func (m *GetIncomeDetailListReq) GetQueryType() int32 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

func (m *GetIncomeDetailListReq) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *GetIncomeDetailListReq) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *GetIncomeDetailListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetIncomeDetailListReq) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

// 收入明细列表项
type IncomeDetailItem struct {
	// 主键Id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 消费项目名(弹幕、道具等)
	ConsumeName string `protobuf:"bytes,2,opt,name=consumeName,proto3" json:"consumeName,omitempty"`
	// 钻石
	Diamond int32 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	// 时间
	CreatedAt            string   `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncomeDetailItem) Reset()         { *m = IncomeDetailItem{} }
func (m *IncomeDetailItem) String() string { return proto.CompactTextString(m) }
func (*IncomeDetailItem) ProtoMessage()    {}
func (*IncomeDetailItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{19}
}

func (m *IncomeDetailItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomeDetailItem.Unmarshal(m, b)
}
func (m *IncomeDetailItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomeDetailItem.Marshal(b, m, deterministic)
}
func (m *IncomeDetailItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomeDetailItem.Merge(m, src)
}
func (m *IncomeDetailItem) XXX_Size() int {
	return xxx_messageInfo_IncomeDetailItem.Size(m)
}
func (m *IncomeDetailItem) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomeDetailItem.DiscardUnknown(m)
}

var xxx_messageInfo_IncomeDetailItem proto.InternalMessageInfo

func (m *IncomeDetailItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IncomeDetailItem) GetConsumeName() string {
	if m != nil {
		return m.ConsumeName
	}
	return ""
}

func (m *IncomeDetailItem) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *IncomeDetailItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// 收入明细列表响应
type GetIncomeDetailListResp struct {
	// 总记录数
	TotalRecord int32 `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	// 总页数
	TotalPage int32 `protobuf:"varint,2,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	// 页面大小
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 页码
	PageNum int32 `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 总钻石
	TotalDiamond int32 `protobuf:"varint,5,opt,name=totalDiamond,proto3" json:"totalDiamond,omitempty"`
	// 收入明细列表请求
	List                 []*IncomeDetailItem `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetIncomeDetailListResp) Reset()         { *m = GetIncomeDetailListResp{} }
func (m *GetIncomeDetailListResp) String() string { return proto.CompactTextString(m) }
func (*GetIncomeDetailListResp) ProtoMessage()    {}
func (*GetIncomeDetailListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{20}
}

func (m *GetIncomeDetailListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIncomeDetailListResp.Unmarshal(m, b)
}
func (m *GetIncomeDetailListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIncomeDetailListResp.Marshal(b, m, deterministic)
}
func (m *GetIncomeDetailListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIncomeDetailListResp.Merge(m, src)
}
func (m *GetIncomeDetailListResp) XXX_Size() int {
	return xxx_messageInfo_GetIncomeDetailListResp.Size(m)
}
func (m *GetIncomeDetailListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIncomeDetailListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetIncomeDetailListResp proto.InternalMessageInfo

func (m *GetIncomeDetailListResp) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *GetIncomeDetailListResp) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *GetIncomeDetailListResp) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetIncomeDetailListResp) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetIncomeDetailListResp) GetTotalDiamond() int32 {
	if m != nil {
		return m.TotalDiamond
	}
	return 0
}

func (m *GetIncomeDetailListResp) GetList() []*IncomeDetailItem {
	if m != nil {
		return m.List
	}
	return nil
}

// 查看收支明细详情请求
type CheckIncomeDetailReq struct {
	// 查询类型1消费明细列表 2收入明细列表
	QueryType            int32    `protobuf:"varint,1,opt,name=queryType,proto3" json:"queryType,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckIncomeDetailReq) Reset()         { *m = CheckIncomeDetailReq{} }
func (m *CheckIncomeDetailReq) String() string { return proto.CompactTextString(m) }
func (*CheckIncomeDetailReq) ProtoMessage()    {}
func (*CheckIncomeDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{21}
}

func (m *CheckIncomeDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckIncomeDetailReq.Unmarshal(m, b)
}
func (m *CheckIncomeDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckIncomeDetailReq.Marshal(b, m, deterministic)
}
func (m *CheckIncomeDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckIncomeDetailReq.Merge(m, src)
}
func (m *CheckIncomeDetailReq) XXX_Size() int {
	return xxx_messageInfo_CheckIncomeDetailReq.Size(m)
}
func (m *CheckIncomeDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckIncomeDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckIncomeDetailReq proto.InternalMessageInfo

func (m *CheckIncomeDetailReq) GetQueryType() int32 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

func (m *CheckIncomeDetailReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 查看收支明细详情响应
type CheckIncomeDetailResp struct {
	// 钻石
	Diamond int32 `protobuf:"varint,1,opt,name=diamond,proto3" json:"diamond,omitempty"`
	// 主播id
	AnchorId int32 `protobuf:"varint,2,opt,name=anchorId,proto3" json:"anchorId,omitempty"`
	// 主播昵称
	AnchorNickName string `protobuf:"bytes,3,opt,name=anchorNickName,proto3" json:"anchorNickName,omitempty"`
	// 消费类型名称
	ConsumeTypeName string `protobuf:"bytes,4,opt,name=consumeTypeName,proto3" json:"consumeTypeName,omitempty"`
	// 创建时间
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckIncomeDetailResp) Reset()         { *m = CheckIncomeDetailResp{} }
func (m *CheckIncomeDetailResp) String() string { return proto.CompactTextString(m) }
func (*CheckIncomeDetailResp) ProtoMessage()    {}
func (*CheckIncomeDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{22}
}

func (m *CheckIncomeDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckIncomeDetailResp.Unmarshal(m, b)
}
func (m *CheckIncomeDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckIncomeDetailResp.Marshal(b, m, deterministic)
}
func (m *CheckIncomeDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckIncomeDetailResp.Merge(m, src)
}
func (m *CheckIncomeDetailResp) XXX_Size() int {
	return xxx_messageInfo_CheckIncomeDetailResp.Size(m)
}
func (m *CheckIncomeDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckIncomeDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckIncomeDetailResp proto.InternalMessageInfo

func (m *CheckIncomeDetailResp) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *CheckIncomeDetailResp) GetAnchorId() int32 {
	if m != nil {
		return m.AnchorId
	}
	return 0
}

func (m *CheckIncomeDetailResp) GetAnchorNickName() string {
	if m != nil {
		return m.AnchorNickName
	}
	return ""
}

func (m *CheckIncomeDetailResp) GetConsumeTypeName() string {
	if m != nil {
		return m.ConsumeTypeName
	}
	return ""
}

func (m *CheckIncomeDetailResp) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// 我的钱包(主播端)
type MyWalletReq struct {
	// 用户手机今天的日期
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// 用户手机的时区
	TimeZone             string   `protobuf:"bytes,2,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyWalletReq) Reset()         { *m = MyWalletReq{} }
func (m *MyWalletReq) String() string { return proto.CompactTextString(m) }
func (*MyWalletReq) ProtoMessage()    {}
func (*MyWalletReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{23}
}

func (m *MyWalletReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyWalletReq.Unmarshal(m, b)
}
func (m *MyWalletReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyWalletReq.Marshal(b, m, deterministic)
}
func (m *MyWalletReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyWalletReq.Merge(m, src)
}
func (m *MyWalletReq) XXX_Size() int {
	return xxx_messageInfo_MyWalletReq.Size(m)
}
func (m *MyWalletReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MyWalletReq.DiscardUnknown(m)
}

var xxx_messageInfo_MyWalletReq proto.InternalMessageInfo

func (m *MyWalletReq) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MyWalletReq) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

// 我的钱包(主播端)
type MyWalletResp struct {
	// 总资产(主播收到的所有钻石等值的可提USD)
	TotalUSD string `protobuf:"bytes,1,opt,name=totalUSD,proto3" json:"totalUSD,omitempty"`
	// 约等于当地币种
	Approximately string `protobuf:"bytes,2,opt,name=approximately,proto3" json:"approximately,omitempty"`
	// 今日收入钻石
	TodayIncomeDiamond string `protobuf:"bytes,3,opt,name=todayIncomeDiamond,proto3" json:"todayIncomeDiamond,omitempty"`
	// 今日收入钻石换算成美元
	TodayIncomeUSD string `protobuf:"bytes,4,opt,name=todayIncomeUSD,proto3" json:"todayIncomeUSD,omitempty"`
	// 直播间资产
	RoomAsset string `protobuf:"bytes,5,opt,name=roomAsset,proto3" json:"roomAsset,omitempty"`
	// 家族资产
	FamilyAsset          string   `protobuf:"bytes,6,opt,name=familyAsset,proto3" json:"familyAsset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyWalletResp) Reset()         { *m = MyWalletResp{} }
func (m *MyWalletResp) String() string { return proto.CompactTextString(m) }
func (*MyWalletResp) ProtoMessage()    {}
func (*MyWalletResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a5cfb949fd1ce9, []int{24}
}

func (m *MyWalletResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyWalletResp.Unmarshal(m, b)
}
func (m *MyWalletResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyWalletResp.Marshal(b, m, deterministic)
}
func (m *MyWalletResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyWalletResp.Merge(m, src)
}
func (m *MyWalletResp) XXX_Size() int {
	return xxx_messageInfo_MyWalletResp.Size(m)
}
func (m *MyWalletResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MyWalletResp.DiscardUnknown(m)
}

var xxx_messageInfo_MyWalletResp proto.InternalMessageInfo

func (m *MyWalletResp) GetTotalUSD() string {
	if m != nil {
		return m.TotalUSD
	}
	return ""
}

func (m *MyWalletResp) GetApproximately() string {
	if m != nil {
		return m.Approximately
	}
	return ""
}

func (m *MyWalletResp) GetTodayIncomeDiamond() string {
	if m != nil {
		return m.TodayIncomeDiamond
	}
	return ""
}

func (m *MyWalletResp) GetTodayIncomeUSD() string {
	if m != nil {
		return m.TodayIncomeUSD
	}
	return ""
}

func (m *MyWalletResp) GetRoomAsset() string {
	if m != nil {
		return m.RoomAsset
	}
	return ""
}

func (m *MyWalletResp) GetFamilyAsset() string {
	if m != nil {
		return m.FamilyAsset
	}
	return ""
}

func init() {
	proto.RegisterType((*PayTypeItem)(nil), "proto.PayTypeItem")
	proto.RegisterType((*PayChannel)(nil), "proto.PayChannel")
	proto.RegisterType((*GetRechargeCenterResp)(nil), "proto.GetRechargeCenterResp")
	proto.RegisterType((*GetZoneByPayTypeCodeReq)(nil), "proto.GetZoneByPayTypeCodeReq")
	proto.RegisterType((*GetZoneByPayTypeCodeResp)(nil), "proto.GetZoneByPayTypeCodeResp")
	proto.RegisterType((*GetPayRandomCodeResp)(nil), "proto.GetPayRandomCodeResp")
	proto.RegisterType((*DiamondExchangeItem)(nil), "proto.DiamondExchangeItem")
	proto.RegisterType((*GetDiamondResp)(nil), "proto.GetDiamondResp")
	proto.RegisterType((*DiamondExchangeReq)(nil), "proto.DiamondExchangeReq")
	proto.RegisterType((*RechargeRecordListReq)(nil), "proto.RechargeRecordListReq")
	proto.RegisterType((*RechargeRecordItem)(nil), "proto.RechargeRecordItem")
	proto.RegisterType((*RechargeRecordListResp)(nil), "proto.RechargeRecordListResp")
	proto.RegisterType((*WithdrawRecordListReq)(nil), "proto.WithdrawRecordListReq")
	proto.RegisterType((*WithdrawRecordItem)(nil), "proto.WithdrawRecordItem")
	proto.RegisterType((*WithdrawRecordListResp)(nil), "proto.WithdrawRecordListResp")
	proto.RegisterType((*CheckWithdrawDetailReq)(nil), "proto.CheckWithdrawDetailReq")
	proto.RegisterType((*CheckWithdrawDetailResp)(nil), "proto.CheckWithdrawDetailResp")
	proto.RegisterType((*MyAssetResp)(nil), "proto.MyAssetResp")
	proto.RegisterType((*GetIncomeDetailListReq)(nil), "proto.GetIncomeDetailListReq")
	proto.RegisterType((*IncomeDetailItem)(nil), "proto.IncomeDetailItem")
	proto.RegisterType((*GetIncomeDetailListResp)(nil), "proto.GetIncomeDetailListResp")
	proto.RegisterType((*CheckIncomeDetailReq)(nil), "proto.CheckIncomeDetailReq")
	proto.RegisterType((*CheckIncomeDetailResp)(nil), "proto.CheckIncomeDetailResp")
	proto.RegisterType((*MyWalletReq)(nil), "proto.MyWalletReq")
	proto.RegisterType((*MyWalletResp)(nil), "proto.MyWalletResp")
}

func init() {
	proto.RegisterFile("finance/pay.proto", fileDescriptor_c6a5cfb949fd1ce9)
}

var fileDescriptor_c6a5cfb949fd1ce9 = []byte{
	// 1018 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0xf7, 0x27, 0x3f, 0x67, 0x4b, 0x68, 0x87, 0x26, 0x31, 0x51, 0x81, 0xc8, 0x42, 0x28,
	0x02, 0x91, 0x08, 0xca, 0x1d, 0x42, 0x22, 0xd9, 0xa0, 0xd5, 0x22, 0x08, 0x2b, 0xa7, 0xa8, 0x52,
	0xef, 0x66, 0xed, 0x93, 0x5d, 0x2b, 0xb6, 0xc7, 0xb1, 0x67, 0xa1, 0xae, 0x78, 0x0c, 0x2e, 0xb9,
	0xe2, 0x21, 0xb8, 0xeb, 0x15, 0x2f, 0xc2, 0x25, 0x8f, 0x81, 0x66, 0x7c, 0xec, 0x9d, 0x71, 0x4c,
	0x23, 0x55, 0x48, 0xf4, 0x6a, 0xe7, 0x7c, 0x73, 0x7c, 0x66, 0xe6, 0xfb, 0xbe, 0xf9, 0x59, 0x78,
	0x70, 0x15, 0xa5, 0x3c, 0x0d, 0xf0, 0x24, 0xe3, 0xe5, 0x71, 0x96, 0x0b, 0x29, 0xd8, 0x50, 0xff,
	0x78, 0x7f, 0x3a, 0x30, 0x9a, 0xf1, 0xf2, 0x49, 0x99, 0xe1, 0x54, 0x62, 0xc2, 0x0e, 0x61, 0x94,
	0x55, 0xe1, 0x58, 0x84, 0xe8, 0x3a, 0x87, 0xce, 0xd1, 0xb6, 0x6f, 0x42, 0x46, 0xc6, 0x05, 0x4f,
	0xd0, 0xed, 0x59, 0x19, 0x0a, 0x32, 0x32, 0xa6, 0x81, 0x48, 0xdd, 0xbe, 0x95, 0xa1, 0x20, 0xf6,
	0x21, 0xbc, 0x15, 0x62, 0x11, 0xe4, 0xd1, 0x1c, 0x9f, 0x44, 0x32, 0x46, 0x77, 0xa0, 0x73, 0x6c,
	0x90, 0x1d, 0xc1, 0xdb, 0x35, 0x30, 0x16, 0xa9, 0xc4, 0x54, 0xba, 0x43, 0x9d, 0xd7, 0x86, 0xbd,
	0x33, 0x80, 0x19, 0x2f, 0xc7, 0x4b, 0x9e, 0xa6, 0x18, 0xab, 0xf1, 0x83, 0xaa, 0x69, 0xae, 0xc1,
	0x80, 0x18, 0x83, 0xc1, 0x0b, 0x91, 0xd6, 0x93, 0xd7, 0x6d, 0xef, 0xb7, 0x1e, 0xec, 0x4e, 0x50,
	0xfa, 0x18, 0x2c, 0x79, 0xbe, 0xc0, 0x31, 0xa6, 0x12, 0x73, 0x1f, 0x8b, 0x8c, 0x1d, 0xc0, 0x56,
	0x20, 0xa2, 0xd4, 0x28, 0xd6, 0xc4, 0x7a, 0x2c, 0xb1, 0x4a, 0x65, 0x5e, 0xea, 0x6e, 0x62, 0xc3,
	0x80, 0x98, 0x0b, 0x9b, 0x73, 0x1e, 0x2b, 0xf6, 0x89, 0x89, 0x3a, 0x54, 0x3d, 0x61, 0xc4, 0x13,
	0x91, 0x86, 0xb4, 0xfe, 0x3a, 0x64, 0x1f, 0xc1, 0x0e, 0x3e, 0x57, 0x13, 0x5e, 0xe0, 0x69, 0xa2,
	0x6a, 0xb9, 0x1b, 0x3a, 0xa1, 0x85, 0xb2, 0x2f, 0x1a, 0xa6, 0xbf, 0x8b, 0x0a, 0xe9, 0x6e, 0x1e,
	0xf6, 0x8f, 0x46, 0x9f, 0xb3, 0x4a, 0xe1, 0x63, 0x43, 0x56, 0xdf, 0x4c, 0x63, 0x8f, 0x1b, 0x7e,
	0xf4, 0x57, 0x5b, 0xfa, 0xab, 0x07, 0xeb, 0xaf, 0x88, 0x47, 0xdf, 0xcc, 0xf2, 0xbe, 0x84, 0xfd,
	0x09, 0xca, 0x67, 0x22, 0xc5, 0xb3, 0x72, 0xb6, 0xb6, 0x83, 0x8f, 0x37, 0x77, 0x7b, 0xc6, 0xfb,
	0x01, 0xdc, 0xee, 0x8f, 0x8b, 0xec, 0xf5, 0x66, 0xf3, 0x31, 0x3c, 0x9c, 0xa0, 0x9c, 0xf1, 0xd2,
	0xe7, 0x69, 0x28, 0x92, 0xa6, 0x18, 0x83, 0x41, 0xb0, 0x9e, 0x83, 0x6e, 0x7b, 0xa7, 0xf0, 0xce,
	0x79, 0xc5, 0xeb, 0x37, 0xc4, 0x9e, 0x76, 0xfa, 0x7d, 0xe8, 0xff, 0x78, 0x79, 0xae, 0x33, 0x87,
	0xbe, 0x6a, 0x2a, 0x3d, 0x28, 0x51, 0xeb, 0x38, 0xf4, 0xeb, 0xd0, 0xfb, 0xc3, 0x81, 0x9d, 0x09,
	0x4a, 0x0a, 0xf5, 0x48, 0x86, 0xac, 0xce, 0xbf, 0xca, 0xda, 0xbb, 0x4b, 0xd6, 0x7e, 0xa7, 0xac,
	0x2e, 0x6c, 0xc6, 0xf8, 0x13, 0xc6, 0xd3, 0xca, 0x18, 0x43, 0xbf, 0x0e, 0xd9, 0x31, 0x0c, 0x62,
	0xc5, 0xd2, 0x50, 0xb3, 0x74, 0x40, 0x2c, 0x75, 0x2c, 0xcf, 0xd7, 0x79, 0xde, 0xd7, 0xc0, 0x5a,
	0x9d, 0x4a, 0xb0, 0xce, 0xa5, 0x87, 0xf6, 0xd2, 0x29, 0xf4, 0x2e, 0x61, 0xb7, 0xde, 0x12, 0x3e,
	0x06, 0x22, 0x0f, 0x15, 0xff, 0xaa, 0xc8, 0xfb, 0x00, 0x19, 0x5f, 0xe0, 0xc5, 0x2a, 0x99, 0x63,
	0x4e, 0xb5, 0x0c, 0x44, 0xed, 0x1a, 0x15, 0x5d, 0x46, 0x2f, 0x90, 0x6a, 0x36, 0xb1, 0xf7, 0xab,
	0x03, 0xcc, 0xae, 0xaa, 0x25, 0xd9, 0x81, 0x5e, 0x14, 0x52, 0xa9, 0x5e, 0x14, 0xb2, 0x3d, 0xd8,
	0x98, 0x47, 0x71, 0x7c, 0x21, 0x88, 0x48, 0x8a, 0x94, 0xe1, 0x44, 0x1e, 0x62, 0x6e, 0x91, 0x68,
	0x42, 0xec, 0x11, 0x6c, 0x07, 0x39, 0x72, 0x89, 0xe1, 0xa9, 0xa4, 0xcd, 0xb5, 0x06, 0x54, 0xdd,
	0x42, 0x72, 0xb9, 0x2a, 0xe8, 0x3c, 0xa1, 0xc8, 0x7b, 0xe9, 0xc0, 0x5e, 0xd7, 0x62, 0x8b, 0x4c,
	0x0d, 0x29, 0x85, 0xe4, 0x71, 0x05, 0xd3, 0x1c, 0x4d, 0x48, 0x0d, 0xa9, 0xc3, 0x19, 0x5f, 0xd4,
	0x0b, 0x5e, 0x03, 0x16, 0x1b, 0x7d, 0x9b, 0x0d, 0x45, 0x3e, 0xf1, 0x56, 0xcb, 0x4d, 0x21, 0xfb,
	0xd4, 0x92, 0xfb, 0x5d, 0x92, 0xfb, 0x36, 0x73, 0xa4, 0xf6, 0x25, 0xec, 0x3e, 0x8d, 0xe4, 0x32,
	0xcc, 0xf9, 0xcf, 0xff, 0xad, 0x56, 0x76, 0xd5, 0x37, 0x46, 0xab, 0xae, 0xc5, 0xbe, 0x61, 0x5a,
	0xdd, 0x66, 0x8e, 0xb4, 0x3a, 0x82, 0xbd, 0xf1, 0x12, 0x83, 0xeb, 0x3a, 0xe1, 0x1c, 0x25, 0x8f,
	0x62, 0x25, 0x56, 0x8b, 0x59, 0xef, 0x33, 0xd8, 0xef, 0xcc, 0x2c, 0x32, 0x45, 0x4e, 0x8e, 0x09,
	0xcf, 0xaf, 0xe9, 0x0c, 0xa2, 0xc8, 0x0b, 0x60, 0xf4, 0x7d, 0x79, 0x5a, 0x14, 0x28, 0x5f, 0xfb,
	0xac, 0x3a, 0x84, 0x51, 0x81, 0x69, 0x58, 0x1f, 0x88, 0xa4, 0x9b, 0x01, 0x79, 0xbf, 0x3b, 0xb0,
	0x37, 0x41, 0x39, 0x4d, 0x03, 0x91, 0x60, 0x35, 0xa9, 0xda, 0x6f, 0x8f, 0x60, 0xfb, 0x66, 0x85,
	0xb9, 0x3e, 0xe8, 0x69, 0x25, 0x6b, 0x40, 0x1d, 0xd2, 0x21, 0x97, 0xcd, 0xed, 0xab, 0xda, 0x2d,
	0x87, 0xf6, 0x5f, 0xe9, 0xd0, 0x41, 0x4b, 0x93, 0x03, 0xd8, 0x92, 0x51, 0x82, 0xea, 0x7a, 0x21,
	0x93, 0x34, 0xb1, 0xf7, 0x0b, 0xdc, 0x37, 0x27, 0xd8, 0x69, 0x5d, 0x7d, 0x87, 0xa7, 0xc5, 0x2a,
	0xb1, 0x5e, 0x34, 0x06, 0x64, 0xd2, 0xd4, 0xb7, 0x8e, 0xc7, 0x57, 0x9b, 0xd7, 0xfb, 0xcb, 0xd1,
	0xb7, 0xe6, 0x6d, 0x8a, 0xfe, 0x37, 0x97, 0x7a, 0x70, 0x4f, 0x97, 0xa8, 0x75, 0x1d, 0xea, 0x6e,
	0x0b, 0x63, 0x9f, 0x90, 0x93, 0x37, 0xb4, 0x93, 0xf7, 0xc9, 0xc9, 0x6d, 0x1a, 0xc9, 0xc7, 0xe7,
	0xf0, 0x50, 0xbb, 0xd3, 0xec, 0xbe, 0xdb, 0x02, 0x95, 0x04, 0xbd, 0xc6, 0xe3, 0x2f, 0x1d, 0xd8,
	0xed, 0x28, 0x53, 0x79, 0xb7, 0xa6, 0xde, 0xb1, 0xa9, 0x3f, 0x80, 0x2d, 0x9e, 0x06, 0x4b, 0x91,
	0x4f, 0xeb, 0x4a, 0x4d, 0xac, 0x6e, 0xda, 0xaa, 0x7d, 0x11, 0x05, 0xd7, 0x5a, 0x55, 0xba, 0x69,
	0x6d, 0x54, 0x3d, 0x31, 0x49, 0xe7, 0xe6, 0x41, 0x5b, 0x89, 0xd8, 0x86, 0x6d, 0xa1, 0x87, 0x6d,
	0xa1, 0xbf, 0x52, 0x1b, 0xee, 0x29, 0x8f, 0x63, 0xd4, 0xfe, 0xaf, 0x1d, 0xee, 0x18, 0x0e, 0x37,
	0x5d, 0xda, 0x6b, 0xb9, 0xf4, 0x6f, 0x07, 0xee, 0xad, 0xbf, 0xaf, 0x9e, 0x9c, 0x5a, 0x92, 0xfa,
	0x9a, 0x56, 0xc9, 0x14, 0xab, 0xc7, 0x33, 0xcf, 0xb2, 0x5c, 0x3c, 0x8f, 0x12, 0x2e, 0x31, 0x2e,
	0xa9, 0x9a, 0x0d, 0xb2, 0x63, 0x60, 0x52, 0x84, 0xbc, 0x24, 0x42, 0xad, 0x6d, 0xdc, 0xd1, 0xa3,
	0x18, 0x33, 0x50, 0x35, 0x6e, 0x45, 0x44, 0x0b, 0x55, 0x3c, 0xe4, 0x42, 0x24, 0xfa, 0x70, 0xa9,
	0x79, 0x68, 0x00, 0x65, 0xea, 0x2b, 0x9e, 0x44, 0x71, 0x75, 0xf8, 0xd0, 0xab, 0xd5, 0x84, 0xce,
	0x3e, 0x78, 0xf6, 0xde, 0xcd, 0x0a, 0x57, 0xf8, 0xad, 0x98, 0x9f, 0x64, 0xd7, 0x8b, 0x13, 0x6d,
	0xae, 0xf9, 0xea, 0xea, 0x84, 0xfe, 0xa2, 0xcc, 0x37, 0x34, 0xf2, 0xf8, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0x18, 0x13, 0x4d, 0xb4, 0x0c, 0x00, 0x00,
}
